// test.idl,v 1.2 1999/08/05 21:03:46 schmidt Exp

interface Stopwatch 
{
   void start ();
   // Start the Stop watch

   void stop ();
   // Stop the watch

  void shutdown ();
  // Shutdown the ORB
};
