LIBRARY Xp
VERSION LIBRARY_VERSION
EXPORTS
 XpCancelDoc
 XpCancelJob
 XpCancelPage
 XpCreateContext
 XpDestroyContext
 XpEndDoc
 XpEndJob
 XpEndPage
 XpFreePrinterList
 XpGetAttributes
 XpGetAuthParams
 XpGetContext
 XpGetDocumentData
 XpGetLocaleHinter
 XpGetLocaleNetString
 XpGetOneAttribute
 XpGetPageDimensions
 XpGetPdmStartParams
 XpGetPrinterList
 XpGetScreenOfContext
 XpInputSelected
 XpNotifyPdm
 XpPutDocumentData
 XpQueryExtension
 XpQueryScreens
 XpQueryVersion
 XpRehashPrinterList
 XpSelectInput
 XpSendAuth
 XpSendOneTicket
 XpSetAttributes
 XpSetContext
 XpSetLocaleHinter
 XpStartDoc
 XpStartJob
 XpStartPage
/* $XConsortium: Xp-def.cpp /main/1 1996/11/13 14:44:46 lehors $ */
