.\" $XFree86: xc/programs/Xserver/hw/xfree86/reconfig/reconfig.man,v 3.6 1996/12/23 06:51:44 dawes Exp $
.TH reconfig 1 "Version 3.2" "XFree86"
.SH NAME
reconfig \- convert old Xconfig to new XF86Config
.SH SYNOPSIS
.B reconfig
<
.I Xconfig
>
.I XF86Config
.SH DESCRIPTION
The \fIreconfig\fP program converts the Xconfig file format used
in XFree86 versions prior to 3.1 into the XF86Config format currently
used.  The XF86Config format contains more information than the Xconfig
format, so manual editing is required after converting.
.SH "SEE ALSO"
XFree86(1), XF86Config(4/5), xf86config(1)
.SH AUTHOR
Gertjan Akkerman.
.SH BUGS
Comment lines are stripped out when converting.
.\" $XConsortium: reconfig.man /main/8 1996/12/09 17:37:58 kaleb $
