/* Generated by Together */

#ifndef NOTOOLKITFOUNDEXCEPTION_H
#define NOTOOLKITFOUNDEXCEPTION_H




class APPKIT_API NoToolKitFoundException : public VCF::BasicException {
public:
	
	NoToolKitFoundException(const VCF::String & message):
	  VCF::BasicException( message ){};

	  NoToolKitFoundException():
		VCF::BasicException( NO_TOOLKIT_ERROR ){};

	virtual ~NoToolKitFoundException(){};
};

#endif //NOTOOLKITFOUNDEXCEPTION_H_H