// Diamond.idl,v 1.1 1999/07/14 07:32:40 nanbor Exp

module Diamond
{
  interface Top
    {
      string shape ();
    };

  interface Left : Top
    {
      string color ();
    };

  interface Right : Top
    {
      long width ();
    };

  interface Buttom : Left, Right
    {
      string name ();
    };
};
