//
// test.idl,v 1.2 2001/09/18 00:06:00 irfan Exp
//

interface Test
{
  void test_method (in boolean client_propagated,
                    in short client_priority);

  oneway void shutdown ();
};
