// -*- IDL -*-

//=============================================================================
/**
 * @file test.idl
 *
 * test.idl,v 1.1 2001/03/01 18:11:13 othman Exp
 *
 * "test" IDL interface for the Codec test.
 *
 * @author Ossama Othman <ossama@uci.edu>
 */
//=============================================================================

module Foo
{

  struct Bar
  {
    string A;
    long B;
    string C;
  };

};
