.TH ACE_Malloc_LIFO_Iterator 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Malloc_LIFO_Iterator \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Malloc_T.h>\fR
.PP
Inherits \fBACE_Malloc_LIFO_Iterator_T< ACE_MEM_POOL_2,ACE_LOCK,ACE_Control_Block >\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Malloc_LIFO_Iterator\fR (\fBACE_Malloc\fR<ACE_MEM_POOL_2, ACE_LOCK> &malloc, const char *name = 0)"
.br
.RI "\fIif <name> = 0 it will iterate through everything else only through those entries whose <name> match.\fR"
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<ACE_MEM_POOL_1, classACE_LOCK> ACE_Malloc_LIFO_Iterator<, ACE_LOCK>::ACE_Malloc_LIFO_Iterator<, ACE_LOCK> (\fBACE_Malloc\fR< ACE_MEM_POOL_2,ACE_LOCK >& malloc, const char * name = 0)
.PP
if <name> = 0 it will iterate through everything else only through those entries whose <name> match.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.