.TH ACE_CDR::Double 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_CDR::Double \- 
.SH SYNOPSIS
.br
.PP
\fC#include <CDR_Base.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "char \fBf\fR [8]"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS char ACE_CDR::Double::f[8]
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.