.TH ACE_OutputCDR::from_string 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_OutputCDR::from_string \- 
.SH SYNOPSIS
.br
.PP
\fC#include <CDR_Stream.h>\fR
.PP
.SS Helper classes

.in +1c
.ti -1c
.RI "\fBfrom_string\fR (\fBACE_CDR::Char\fR* s, \fBACE_CDR::ULong\fR b, \fBACE_CDR::Boolean\fR nocopy = 0)"
.br
.ti -1c
.RI "\fBfrom_string\fR (const \fBACE_CDR::Char\fR* s, \fBACE_CDR::ULong\fR b, \fBACE_CDR::Boolean\fR nocopy = 0)"
.br
.ti -1c
.RI "\fBACE_CDR::Char\fR* \fBval_\fR"
.br
.ti -1c
.RI "\fBACE_CDR::ULong\fR \fBbound_\fR"
.br
.ti -1c
.RI "\fBACE_CDR::Boolean\fR \fBnocopy_\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_OutputCDR::from_string::from_string (\fBACE_CDR::Char\fR * s, \fBACE_CDR::ULong\fR b, \fBACE_CDR::Boolean\fR nocopy = 0)
.PP
.SS ACE_OutputCDR::from_string::from_string (const \fBACE_CDR::Char\fR * s, \fBACE_CDR::ULong\fR b, \fBACE_CDR::Boolean\fR nocopy = 0)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_CDR::ULong\fR ACE_OutputCDR::from_string::bound_
.PP
.SS \fBACE_CDR::Boolean\fR ACE_OutputCDR::from_string::nocopy_
.PP
.SS \fBACE_CDR::Char\fR * ACE_OutputCDR::from_string::val_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.