.TH ACE_BoolCapEntry 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_BoolCapEntry \- This class implement the \fBACE\fR Bool Capability subclass. 
.SH SYNOPSIS
.br
.PP
\fC#include <Capabilities.h>\fR
.PP
Inherits \fBACE_CapEntry\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_BoolCapEntry\fR (int val)"
.br
.ti -1c
.RI "int \fBgetval\fR (void) const"
.br
.in -1c
.SS Protected Attributes

.in +1c
.ti -1c
.RI "int \fBval_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
This class implement the \fBACE\fR Bool Capability subclass.
.PP
.PP
 This is a container class for \fBACE\fR Capabilities bool container values. 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_BoolCapEntry::ACE_BoolCapEntry (int val)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS int ACE_BoolCapEntry::getval (void) const
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int ACE_BoolCapEntry::val_\fC [protected]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.