.TH ACE_MT_MEM_IO::Channel 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_MT_MEM_IO::Channel \- 
.SH SYNOPSIS
.br
.PP
\fC#include <MEM_IO.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "ACE_SYNCH_PROCESS_SEMAPHORE* \fBsema_\fR"
.br
.ti -1c
.RI "ACE_SYNCH_PROCESS_MUTEX* \fBlock_\fR"
.br
.ti -1c
.RI "\fBSimple_Queue\fR \fBqueue_\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS ACE_SYNCH_PROCESS_MUTEX * ACE_MT_MEM_IO::Channel::lock_
.PP
.SS \fBSimple_Queue\fR ACE_MT_MEM_IO::Channel::queue_
.PP
.SS ACE_SYNCH_PROCESS_SEMAPHORE * ACE_MT_MEM_IO::Channel::sema_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.