.TH ACE_YYSTYPE 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_YYSTYPE \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Svc_Conf.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBtype_\fR"
.br
.ti -1c
.RI "\fBACE_Location_Node\fR* \fBlocation_node_\fR"
.br
.ti -1c
.RI "\fBACE_Parse_Node\fR* \fBparse_node_\fR"
.br
.ti -1c
.RI "\fBACE_Static_Node\fR* \fBstatic_node_\fR"
.br
.ti -1c
.RI "\fBACE_Service_Type\fR* \fBsvc_record_\fR"
.br
.ti -1c
.RI "\fBACE_TCHAR\fR* \fBident_\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_TCHAR\fR * ACE_YYSTYPE::ident_
.PP
.SS \fBACE_Location_Node\fR * ACE_YYSTYPE::location_node_
.PP
.SS \fBACE_Parse_Node\fR * ACE_YYSTYPE::parse_node_
.PP
.SS \fBACE_Static_Node\fR * ACE_YYSTYPE::static_node_
.PP
.SS \fBACE_Service_Type\fR * ACE_YYSTYPE::svc_record_
.PP
.SS int ACE_YYSTYPE::type_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.