.TH ACE_CapEntry 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_CapEntry \- This class is the base class for all \fBACE\fR Capabilities entry subclasses. 
.SH SYNOPSIS
.br
.PP
\fC#include <Capabilities.h>\fR
.PP
Inherited by \fBACE_BoolCapEntry\fR, \fBACE_IntCapEntry\fR, and \fBACE_StringCapEntry\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "virtual \fB~ACE_CapEntry\fR (void)"
.br
.in -1c
.SS Protected Types

.in +1c
.ti -1c
.RI "enum { \fBACE_INTCAP\fR = 0, \fBACE_STRINGCAP\fR = 1, \fBACE_BOOLCAP\fR = 2 }"
.br
.in -1c
.SS Protected Methods

.in +1c
.ti -1c
.RI "\fBACE_CapEntry\fR (int captype)"
.br
.in -1c
.SS Protected Attributes

.in +1c
.ti -1c
.RI "int \fBcaptype_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
This class is the base class for all \fBACE\fR Capabilities entry subclasses.
.PP
.PP
 This class is not instantiable and does not provide accessors or methods. If you want to add a new kind of attribute you subclasses of this class and dynamic cast to proper subclass. 
.PP
.SH MEMBER ENUMERATION DOCUMENTATION
.PP 
.SS anonymous enum\fC [protected]\fR
.PP
\fBEnumeration values:\fR
.in +1c
.TP
\fB\fIACE_INTCAP\fR \fR
.TP
\fB\fIACE_STRINGCAP\fR \fR
.TP
\fB\fIACE_BOOLCAP\fR \fR
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS virtual ACE_CapEntry::~ACE_CapEntry (void)\fC [virtual]\fR
.PP
.SS ACE_CapEntry::ACE_CapEntry (int captype)\fC [protected]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int ACE_CapEntry::captype_\fC [protected]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.