.TH ACE_Null_Condition 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Null_Condition \- Implement a do nothing  variable wrapper, i.e., all methods are no ops. This class is necessary since some C++ compilers are *very* lame... 
.SH SYNOPSIS
.br
.PP
\fC#include <Synch.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Null_Condition\fR (const \fBACE_Null_Mutex\fR &m, const \fBACE_TCHAR\fR * = 0, void * = 0)"
.br
.ti -1c
.RI "\fB~ACE_Null_Condition\fR (void)"
.br
.ti -1c
.RI "int \fBremove\fR (void)"
.br
.RI "\fIReturns 0.\fR"
.ti -1c
.RI "int \fBwait\fR (\fBACE_Time_Value\fR * = 0)"
.br
.RI "\fIReturns -1 with <errno> == <ETIME>.\fR"
.ti -1c
.RI "int \fBsignal\fR (void)"
.br
.RI "\fIReturns 0.\fR"
.ti -1c
.RI "int \fBbroadcast\fR (void)"
.br
.RI "\fIReturns 0.\fR"
.ti -1c
.RI "\fBACE_Null_Mutex\fR& \fBmutex\fR (void)"
.br
.ti -1c
.RI "void \fBdump\fR (void) const"
.br
.RI "\fIDump the state of an object.\fR"
.in -1c
.SS Protected Attributes

.in +1c
.ti -1c
.RI "\fBACE_Null_Mutex\fR& \fBmutex_\fR"
.br
.in -1c
.SS Private Methods

.in +1c
.ti -1c
.RI "void \fBoperator=\fR (const ACE_Null_Condition &)"
.br
.ti -1c
.RI "\fBACE_Null_Condition\fR (const ACE_Null_Condition &)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Implement a do nothing  variable wrapper, i.e., all methods are no ops. This class is necessary since some C++ compilers are *very* lame...
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Null_Condition::ACE_Null_Condition (const \fBACE_Null_Mutex\fR & m, const \fBACE_TCHAR\fR * = 0, void * = 0)
.PP
.SS ACE_Null_Condition::~ACE_Null_Condition (void)
.PP
.SS ACE_Null_Condition::ACE_Null_Condition (const ACE_Null_Condition &)\fC [private]\fR
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS int ACE_Null_Condition::broadcast (void)
.PP
Returns 0.
.PP
.SS void ACE_Null_Condition::dump (void) const
.PP
Dump the state of an object.
.PP
.SS \fBACE_Null_Mutex\fR& ACE_Null_Condition::mutex (void)
.PP
.SS void ACE_Null_Condition::operator= (const ACE_Null_Condition &)\fC [private]\fR
.PP
.SS int ACE_Null_Condition::remove (void)
.PP
Returns 0.
.PP
.SS int ACE_Null_Condition::signal (void)
.PP
Returns 0.
.PP
.SS int ACE_Null_Condition::wait (\fBACE_Time_Value\fR * = 0)
.PP
Returns -1 with <errno> == <ETIME>.
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_Null_Mutex\fR & ACE_Null_Condition::mutex_\fC [protected]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.