.TH ACE_Acquire_Method 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Acquire_Method \- An enum class. 
.SH SYNOPSIS
.br
.PP
\fC#include <Synch_T.h>\fR
.PP
.SS Public Types

.in +1c
.ti -1c
.RI "enum \fBMETHOD_TYPE\fR { \fBACE_REGULAR\fR, \fBACE_READ\fR, \fBACE_WRITE\fR }"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
An enum class.
.PP
.PP
 These enums should have been inside the reverse lock class, but some lame compilers cannot handle enums inside template classes.
.PP
The METHOD_TYPE is used to indicate which acquire() method will be called on the real lock when the release() method is called on the reverse lock. REGULAR indicated the acquire() method, READ indicates the acquire_read() method, and WRITE indicates the acquire_write() method. Note that the try_*() methods are not represented here because we have to make sure that the release() method on the reverse lock acquires a lock on the real lock. 
.PP
.SH MEMBER ENUMERATION DOCUMENTATION
.PP 
.SS enum ACE_Acquire_Method::METHOD_TYPE
.PP
\fBEnumeration values:\fR
.in +1c
.TP
\fB\fIACE_REGULAR\fR \fR
.TP
\fB\fIACE_READ\fR \fR
.TP
\fB\fIACE_WRITE\fR \fR


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.