.TH ACE_Dumpable_Ptr 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Dumpable_Ptr \- A smart pointer stored in the in-memory object database \fBACE_ODB\fR. The pointee (if any) is deleted when reassigned. 
.SH SYNOPSIS
.br
.PP
\fC#include <Dump.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Dumpable_Ptr\fR (const \fBACE_Dumpable\fR *dumper = 0)"
.br
.ti -1c
.RI "const \fBACE_Dumpable\fR* \fBoperator->\fR () const"
.br
.ti -1c
.RI "void \fBoperator=\fR (const \fBACE_Dumpable\fR *dumper) const"
.br
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "const \fBACE_Dumpable\fR* \fBdumper_\fR"
.br
.RI "\fI"Real" pointer to the underlying abstract base class pointer that does the real work.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
A smart pointer stored in the in-memory object database \fBACE_ODB\fR. The pointee (if any) is deleted when reassigned.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Dumpable_Ptr::ACE_Dumpable_Ptr (const \fBACE_Dumpable\fR * dumper = 0)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS const \fBACE_Dumpable\fR* ACE_Dumpable_Ptr::operator-> (void) const
.PP
.SS void ACE_Dumpable_Ptr::operator= (const \fBACE_Dumpable\fR * dumper) const
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS const \fBACE_Dumpable\fR * ACE_Dumpable_Ptr::dumper_\fC [private]\fR
.PP
"Real" pointer to the underlying abstract base class pointer that does the real work.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.