.TH ACE_Condition_Attributes 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Condition_Attributes \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Synch.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Condition_Attributes\fR (int type = ACE_DEFAULT_SYNCH_TYPE)"
.br
.RI "\fIConstructor.\fR"
.ti -1c
.RI "\fB~ACE_Condition_Attributes\fR (void)"
.br
.RI "\fIDestructor.\fR"
.in -1c
.SS Private Methods

.in +1c
.ti -1c
.RI "void \fBoperator=\fR (const ACE_Condition_Attributes &)"
.br
.ti -1c
.RI "\fBACE_Condition_Attributes\fR (const ACE_Condition_Attributes &)"
.br
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "ACE_condattr_t \fBattributes_\fR"
.br
.RI "\fIThe attributes.\fR"
.in -1c
.SS Friends

.in +1c
.ti -1c
.RI "class \fBACE_Condition_Thread_Mutex\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Condition_Attributes::ACE_Condition_Attributes (int type = ACE_DEFAULT_SYNCH_TYPE)
.PP
Constructor.
.PP
.SS ACE_Condition_Attributes::~ACE_Condition_Attributes (void)
.PP
Destructor.
.PP
.SS ACE_Condition_Attributes::ACE_Condition_Attributes (const ACE_Condition_Attributes &)\fC [private]\fR
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void ACE_Condition_Attributes::operator= (const ACE_Condition_Attributes &)\fC [private]\fR
.PP
.SH FRIENDS AND RELATED FUNCTION DOCUMENTATION
.PP 
.SS class ACE_Condition_Thread_Mutex\fC [friend]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS ACE_condattr_t ACE_Condition_Attributes::attributes_\fC [private]\fR
.PP
The attributes.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.