.TH ACE_OS_Memory 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_OS_Memory \- This class is a wrapper for dynamic memory operations. 
.SH SYNOPSIS
.br
.PP
\fC#include <OS_Memory.h>\fR
.PP
Inherited by \fBACE_OS\fR.
.PP
.SS Static Public Methods

.in +1c
.ti -1c
.RI "void* \fBsbrk\fR (int brk)"
.br
.ti -1c
.RI "void* \fBcalloc\fR (size_t elements, size_t sizeof_elements)"
.br
.ti -1c
.RI "void* \fBmalloc\fR (size_t)"
.br
.ti -1c
.RI "void* \fBrealloc\fR (void *, size_t)"
.br
.ti -1c
.RI "void \fBfree\fR (void *)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
This class is a wrapper for dynamic memory operations.
.PP
.PP
 
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void* ACE_OS_Memory::calloc (size_t elements, size_t sizeof_elements)\fC [static]\fR
.PP
.SS void ACE_OS_Memory::free (void *)\fC [static]\fR
.PP
.SS void* ACE_OS_Memory::malloc (size_t)\fC [static]\fR
.PP
.SS void* ACE_OS_Memory::realloc (void *, size_t)\fC [static]\fR
.PP
.SS void* ACE_OS_Memory::sbrk (int brk)\fC [static]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.