.TH ACE_Dynamic_Service 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Dynamic_Service \- Provides a general interface to retrieve arbitrary objects from the \fBACE\fR service repository. 
.SH SYNOPSIS
.br
.PP
\fC#include <Dynamic_Service.h>\fR
.PP
Inherits \fBACE_Dynamic_Service_Base\fR.
.PP
.SS Static Public Methods

.in +1c
.ti -1c
.RI "TYPE* \fBinstance\fR (const \fBACE_TCHAR\fR *name)"
.br
.RI "\fIReturn instance using <name> to search the Service_Repository.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class TYPE>  template class ACE_Dynamic_Service
Provides a general interface to retrieve arbitrary objects from the \fBACE\fR service repository.
.PP
.PP
 Uses "name" for lookup in the \fBACE\fR service repository. Obtains the object and returns it as the appropriate type. 
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classTYPE> TYPE * ACE_Dynamic_Service<TYPE>::instance (const \fBACE_TCHAR\fR * name)\fC [static]\fR
.PP
Return instance using <name> to search the Service_Repository.
.PP
Reimplemented from \fBACE_Dynamic_Service_Base\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.