.TH ACE_Name_Request::Transfer 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Name_Request::Transfer \- 
.SH SYNOPSIS
.br
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "ACE_UINT32 \fBlength_\fR"
.br
.ti -1c
.RI "ACE_UINT32 \fBmsg_type_\fR"
.br
.ti -1c
.RI "ACE_UINT32 \fBblock_forever_\fR"
.br
.ti -1c
.RI "ACE_UINT32 \fBsec_timeout_\fR"
.br
.ti -1c
.RI "ACE_UINT32 \fBusec_timeout_\fR"
.br
.ti -1c
.RI "ACE_UINT32 \fBname_len_\fR"
.br
.ti -1c
.RI "ACE_UINT32 \fBvalue_len_\fR"
.br
.ti -1c
.RI "ACE_UINT32 \fBtype_len_\fR"
.br
.ti -1c
.RI "\fBACE_USHORT16\fR \fBdata_\fR [MAX_NAME_LENGTH + MAXPATHLEN + MAXPATHLEN + 2]"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS ACE_UINT32 ACE_Name_Request::Transfer::block_forever_
.PP
.SS \fBACE_USHORT16\fR ACE_Name_Request::Transfer::data_[MAX_NAME_LENGTH+MAXPATHLEN+MAXPATHLEN+2]
.PP
.SS ACE_UINT32 ACE_Name_Request::Transfer::length_
.PP
.SS ACE_UINT32 ACE_Name_Request::Transfer::msg_type_
.PP
.SS ACE_UINT32 ACE_Name_Request::Transfer::name_len_
.PP
.SS ACE_UINT32 ACE_Name_Request::Transfer::sec_timeout_
.PP
.SS ACE_UINT32 ACE_Name_Request::Transfer::type_len_
.PP
.SS ACE_UINT32 ACE_Name_Request::Transfer::usec_timeout_
.PP
.SS ACE_UINT32 ACE_Name_Request::Transfer::value_len_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.