.TH ACE_Token::ACE_Token_Queue 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Token::ACE_Token_Queue \- 
.SH SYNOPSIS
.br
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Token_Queue\fR (void)"
.br
.ti -1c
.RI "void \fBremove_entry\fR (\fBACE_Token_Queue_Entry\fR *)"
.br
.ti -1c
.RI "void \fBinsert_entry\fR (\fBACE_Token_Queue_Entry\fR &entry, int requeue_position = -1)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBACE_Token_Queue_Entry\fR* \fBhead_\fR"
.br
.ti -1c
.RI "\fBACE_Token_Queue_Entry\fR* \fBtail_\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Token::ACE_Token_Queue::ACE_Token_Queue (void)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void ACE_Token::ACE_Token_Queue::insert_entry (\fBACE_Token_Queue_Entry\fR & entry, int requeue_position = -1)
.PP
.SS void ACE_Token::ACE_Token_Queue::remove_entry (\fBACE_Token_Queue_Entry\fR *)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_Token_Queue_Entry\fR * ACE_Token::ACE_Token_Queue::head_
.PP
.SS \fBACE_Token_Queue_Entry\fR * ACE_Token::ACE_Token_Queue::tail_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.