.TH ACE_Stream_Iterator 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Stream_Iterator \- Iterate through an . 
.SH SYNOPSIS
.br
.PP
\fC#include <Stream.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Stream_Iterator\fR (const \fBACE_Stream\fR<ACE_SYNCH_USE> &sr)"
.br
.ti -1c
.RI "int \fBnext\fR (const \fBACE_Module\fR<ACE_SYNCH_USE> *&next_item)"
.br
.RI "\fIPass back the <next_item> that hasn't been seen in the set. Returns 0 when all items have been seen, else 1.\fR"
.ti -1c
.RI "int \fBdone\fR (void) const"
.br
.RI "\fIReturns 1 when all items have been seen, else 0.\fR"
.ti -1c
.RI "int \fBadvance\fR (void)"
.br
.RI "\fIMove forward by one element in the set. Returns 0 when all the items in the set have been seen, else 1.\fR"
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "\fBACE_Module\fR<ACE_SYNCH_USE>* \fBnext_\fR"
.br
.RI "\fINext <Module> that we haven't yet seen.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<ACE_SYNCH_DECL>  template class ACE_Stream_Iterator
Iterate through an .
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<ACE_SYNCH_DECL> ACE_Stream_Iterator<>::ACE_Stream_Iterator<> (const \fBACE_Stream\fR< ACE_SYNCH_USE >& sr)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<ACE_SYNCH_DECL> int ACE_Stream_Iterator<>::advance (void)
.PP
Move forward by one element in the set. Returns 0 when all the items in the set have been seen, else 1.
.PP
.SS template<ACE_SYNCH_DECL> int ACE_Stream_Iterator<>::done (void) const
.PP
Returns 1 when all items have been seen, else 0.
.PP
.SS template<ACE_SYNCH_DECL> int ACE_Stream_Iterator<>::next (const \fBACE_Module\fR< ACE_SYNCH_USE >*& next_item)
.PP
Pass back the <next_item> that hasn't been seen in the set. Returns 0 when all items have been seen, else 1.
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS template<ACE_SYNCH_DECL> \fBACE_Module\fR< ACE_SYNCH_USE >* ACE_Stream_Iterator<>::next_\fC [private]\fR
.PP
Next <Module> that we haven't yet seen.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.