.TH ACE_Asynch_Write_Stream 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Asynch_Write_Stream \- This class is a factory for starting off asynchronous writes on a stream. This class forwards all methods to its implementation class. 
.SH SYNOPSIS
.br
.PP
\fC#include <Asynch_IO.h>\fR
.PP
Inherits \fBACE_Asynch_Operation\fR.
.PP
Inherited by \fBACE_Asynch_Write_File\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Asynch_Write_Stream\fR (void)"
.br
.RI "\fIA do nothing constructor.\fR"
.ti -1c
.RI "virtual \fB~ACE_Asynch_Write_Stream\fR (void)"
.br
.RI "\fIDestructor.\fR"
.ti -1c
.RI "int \fBopen\fR (\fBACE_Handler\fR &handler, ACE_HANDLE handle = ACE_INVALID_HANDLE, const void *completion_key = 0, \fBACE_Proactor\fR *proactor = 0)"
.br
.ti -1c
.RI "int \fBwrite\fR (\fBACE_Message_Block\fR &message_block, u_long bytes_to_write, const void *act = 0, int priority = 0, int signal_number = ACE_SIGRTMIN)"
.br
.ti -1c
.RI "\fBACE_Asynch_Write_Stream_Impl\fR* \fBimplementation\fR (void) const"
.br
.RI "\fIReturn the underlying implementation class.\fR"
.in -1c
.SS Protected Methods

.in +1c
.ti -1c
.RI "void \fBimplementation\fR (\fBACE_Asynch_Write_Stream_Impl\fR *implementation)"
.br
.RI "\fISet the implementation class.\fR"
.in -1c
.SS Protected Attributes

.in +1c
.ti -1c
.RI "\fBACE_Asynch_Write_Stream_Impl\fR* \fBimplementation_\fR"
.br
.RI "\fIImplementation class that all methods will be forwarded to.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
This class is a factory for starting off asynchronous writes on a stream. This class forwards all methods to its implementation class.
.PP
.PP
 Once <open> is called, multiple asynchronous <writes>s can started using this class. An \fBACE_Asynch_Write_Stream::Result\fR will be passed back to the <handler> when the asynchronous write completes through the  callback. 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Asynch_Write_Stream::ACE_Asynch_Write_Stream (void)
.PP
A do nothing constructor.
.PP
.SS ACE_Asynch_Write_Stream::~ACE_Asynch_Write_Stream (void)\fC [virtual]\fR
.PP
Destructor.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void ACE_Asynch_Write_Stream::implementation (\fBACE_Asynch_Write_Stream_Impl\fR * implementation)\fC [protected]\fR
.PP
Set the implementation class.
.PP
.SS \fBACE_Asynch_Write_Stream_Impl\fR * ACE_Asynch_Write_Stream::implementation (void) const
.PP
Return the underlying implementation class.
.PP
Reimplemented from \fBACE_Asynch_Operation\fR.
.PP
Reimplemented in \fBACE_Asynch_Write_File\fR.
.SS int ACE_Asynch_Write_Stream::open (\fBACE_Handler\fR & handler, ACE_HANDLE handle = ACE_INVALID_HANDLE, const void * completion_key = 0, \fBACE_Proactor\fR * proactor = 0)
.PP
Initializes the factory with information which will be used with each asynchronous call. If (<handle> == ACE_INVALID_HANDLE),  will be called on the <handler> to get the correct handle. 
.PP
Reimplemented from \fBACE_Asynch_Operation\fR.
.PP
Reimplemented in \fBACE_Asynch_Write_File\fR.
.SS int ACE_Asynch_Write_Stream::write (\fBACE_Message_Block\fR & message_block, u_long bytes_to_write, const void * act = 0, int priority = 0, int signal_number = ACE_SIGRTMIN)
.PP
This starts off an asynchronous write. Upto <bytes_to_write> will be written from the <message_block>. Upon successful completion of the write operation, <message_block>'s <rd_ptr> is updated to reflect the data that was written. Priority of the operation is specified by <priority>. On POSIX4-Unix, this is supported. Works like <nice> in Unix. Negative values are not allowed. 0 means priority of the operation same as the process priority. 1 means priority of the operation is one less than process. And so forth. On Win32, this argument is a no-op. <signal_number> is the POSIX4 real-time signal number to be used for the operation. <signal_number> ranges from ACE_SIGRTMIN to ACE_SIGRTMAX. This argument is a no-op on non-POSIX4 systems. 
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_Asynch_Write_Stream_Impl\fR * ACE_Asynch_Write_Stream::implementation_\fC [protected]\fR
.PP
Implementation class that all methods will be forwarded to.
.PP
Reimplemented from \fBACE_Asynch_Operation\fR.
.PP
Reimplemented in \fBACE_Asynch_Write_File\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.