.TH ACE_RB_Tree_Base 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_RB_Tree_Base \- 
.SH SYNOPSIS
.br
.PP
\fC#include <RB_Tree.h>\fR
.PP
Inherited by \fBACE_RB_Tree\fR.
.PP
.SS Public Types

.in +1c
.ti -1c
.RI "enum \fBRB_SearchResult\fR { \fBLEFT\fR, \fBEXACT\fR, \fBRIGHT\fR }"
.br
.RI "\fISearch result enumeration.\fR"
.in -1c
.SH MEMBER ENUMERATION DOCUMENTATION
.PP 
.SS enum ACE_RB_Tree_Base::RB_SearchResult
.PP
Search result enumeration.
.PP
\fBEnumeration values:\fR
.in +1c
.TP
\fB\fILEFT\fR \fR
.TP
\fB\fIEXACT\fR \fR
.TP
\fB\fIRIGHT\fR \fR


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.