.TH ACE_Iterator_Impl 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Iterator_Impl \- Defines a abstract iterator. 
.SH SYNOPSIS
.br
.PP
\fC#include <Map_T.h>\fR
.PP
Inherited by \fBACE_Active_Map_Manager_Iterator_Adapter\fR, \fBACE_Hash_Map_Manager_Ex_Iterator_Adapter\fR, \fBACE_Map_Impl_Iterator_Adapter\fR, and \fBACE_Map_Manager_Iterator_Adapter\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "virtual \fB~ACE_Iterator_Impl\fR (void)"
.br
.RI "\fIDestructor.\fR"
.ti -1c
.RI "virtual ACE_Iterator_Impl<T>* \fBclone\fR (void) const = 0"
.br
.RI "\fIClone.\fR"
.ti -1c
.RI "virtual int \fBcompare\fR (const ACE_Iterator_Impl<T> &rhs) const = 0"
.br
.RI "\fIComparison.\fR"
.ti -1c
.RI "virtual T \fBdereference\fR (void) const = 0"
.br
.RI "\fIDereference.\fR"
.ti -1c
.RI "virtual void \fBplus_plus\fR (void) = 0"
.br
.RI "\fIAdvance.\fR"
.ti -1c
.RI "virtual void \fBminus_minus\fR (void) = 0"
.br
.RI "\fIReverse.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class T>  template class ACE_Iterator_Impl
Defines a abstract iterator.
.PP
.PP
 Implementation to be provided by subclasses. 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classT> ACE_Iterator_Impl<T>::~ACE_Iterator_Impl<T> (void)\fC [virtual]\fR
.PP
Destructor.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classT> ACE_Iterator_Impl< T >* ACE_Iterator_Impl<T>::clone (void) const\fC [pure virtual]\fR
.PP
Clone.
.PP
Reimplemented in \fBACE_Map_Impl_Iterator_Adapter\fR, \fBACE_Active_Map_Manager_Iterator_Adapter\fR, \fBACE_Hash_Map_Manager_Ex_Iterator_Adapter\fR, and \fBACE_Map_Manager_Iterator_Adapter\fR.
.SS template<classT> int ACE_Iterator_Impl<T>::compare (const ACE_Iterator_Impl< T >& rhs) const\fC [pure virtual]\fR
.PP
Comparison.
.PP
Reimplemented in \fBACE_Map_Impl_Iterator_Adapter\fR, \fBACE_Active_Map_Manager_Iterator_Adapter\fR, \fBACE_Hash_Map_Manager_Ex_Iterator_Adapter\fR, and \fBACE_Map_Manager_Iterator_Adapter\fR.
.SS template<classT> T ACE_Iterator_Impl<T>::dereference (void) const\fC [pure virtual]\fR
.PP
Dereference.
.PP
Reimplemented in \fBACE_Map_Impl_Iterator_Adapter\fR, \fBACE_Active_Map_Manager_Iterator_Adapter\fR, \fBACE_Hash_Map_Manager_Ex_Iterator_Adapter\fR, and \fBACE_Map_Manager_Iterator_Adapter\fR.
.SS template<classT> void ACE_Iterator_Impl<T>::minus_minus (void)\fC [pure virtual]\fR
.PP
Reverse.
.PP
Reimplemented in \fBACE_Map_Impl_Iterator_Adapter\fR, \fBACE_Active_Map_Manager_Iterator_Adapter\fR, \fBACE_Hash_Map_Manager_Ex_Iterator_Adapter\fR, and \fBACE_Map_Manager_Iterator_Adapter\fR.
.SS template<classT> void ACE_Iterator_Impl<T>::plus_plus (void)\fC [pure virtual]\fR
.PP
Advance.
.PP
Reimplemented in \fBACE_Map_Impl_Iterator_Adapter\fR, \fBACE_Active_Map_Manager_Iterator_Adapter\fR, \fBACE_Hash_Map_Manager_Ex_Iterator_Adapter\fR, and \fBACE_Map_Manager_Iterator_Adapter\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.