.TH ACE_Pagefile_Memory_Pool_Options 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Pagefile_Memory_Pool_Options \- Helper class for Pagefile Memory Pool constructor options. 
.SH SYNOPSIS
.br
.PP
\fC#include <Memory_Pool.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Pagefile_Memory_Pool_Options\fR (void *base_addr = ACE_DEFAULT_PAGEFILE_POOL_BASE, size_t max_size = ACE_DEFAULT_PAGEFILE_POOL_SIZE)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "void* \fBbase_addr_\fR"
.br
.RI "\fIBase address of the memory-mapped backing store.\fR"
.ti -1c
.RI "size_t \fBmax_size_\fR"
.br
.RI "\fIMaximum size the pool may grow.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Helper class for Pagefile Memory Pool constructor options.
.PP
.PP
 This should be a nested class, but that breaks too many compilers. 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Pagefile_Memory_Pool_Options::ACE_Pagefile_Memory_Pool_Options (void * base_addr = ACE_DEFAULT_PAGEFILE_POOL_BASE, size_t max_size = ACE_DEFAULT_PAGEFILE_POOL_SIZE)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS void * ACE_Pagefile_Memory_Pool_Options::base_addr_
.PP
Base address of the memory-mapped backing store.
.PP
.SS size_t ACE_Pagefile_Memory_Pool_Options::max_size_
.PP
Maximum size the pool may grow.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.