.TH ACE_ODB::Tuple 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_ODB::Tuple \- 
.SH SYNOPSIS
.br
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBTuple\fR (void)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "const void* \fBthis_\fR"
.br
.ti -1c
.RI "const \fBACE_Dumpable_Ptr\fR \fBdumper_\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_ODB::Tuple::Tuple (void)\fC [inline]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS const \fBACE_Dumpable_Ptr\fR ACE_ODB::Tuple::dumper_
.PP
.SS const void * ACE_ODB::Tuple::this_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.