.TH ACE_OS_TLI 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_OS_TLI \- This class is a wrapper for the TLI operations. 
.SH SYNOPSIS
.br
.PP
\fC#include <OS_TLI.h>\fR
.PP
Inherited by \fBACE_OS\fR.
.PP
.SS Static Public Methods

.in +1c
.ti -1c
.RI "int \fBt_accept\fR (ACE_HANDLE fildes, ACE_HANDLE resfd, struct t_call *call)"
.br
.ti -1c
.RI "char* \fBt_alloc\fR (ACE_HANDLE fildes, int struct_type, int fields)"
.br
.ti -1c
.RI "int \fBt_bind\fR (ACE_HANDLE fildes, struct t_bind *req, struct t_bind *ret)"
.br
.ti -1c
.RI "int \fBt_close\fR (ACE_HANDLE fildes)"
.br
.ti -1c
.RI "int \fBt_connect\fR (ACE_HANDLE fildes, struct t_call *sndcall, struct t_call *rcvcall)"
.br
.ti -1c
.RI "void \fBt_error\fR (const char *errmsg)"
.br
.ti -1c
.RI "int \fBt_free\fR (char *ptr, int struct_type)"
.br
.ti -1c
.RI "int \fBt_getinfo\fR (ACE_HANDLE fildes, struct t_info *info)"
.br
.ti -1c
.RI "int \fBt_getname\fR (ACE_HANDLE fildes, struct netbuf *namep, int type)"
.br
.ti -1c
.RI "int \fBt_getstate\fR (ACE_HANDLE fildes)"
.br
.ti -1c
.RI "int \fBt_listen\fR (ACE_HANDLE fildes, struct t_call *call)"
.br
.ti -1c
.RI "int \fBt_look\fR (ACE_HANDLE fildes)"
.br
.ti -1c
.RI "ACE_HANDLE \fBt_open\fR (char *path, int oflag, struct t_info *info)"
.br
.ti -1c
.RI "int \fBt_optmgmt\fR (ACE_HANDLE fildes, struct t_optmgmt *req, struct t_optmgmt *ret)"
.br
.ti -1c
.RI "int \fBt_rcv\fR (ACE_HANDLE fildes, char *buf, unsigned int nbytes, int *flags)"
.br
.ti -1c
.RI "int \fBt_rcvdis\fR (ACE_HANDLE fildes, struct t_discon *discon)"
.br
.ti -1c
.RI "int \fBt_rcvrel\fR (ACE_HANDLE fildes)"
.br
.ti -1c
.RI "int \fBt_rcvudata\fR (ACE_HANDLE fildes, struct t_unitdata *unitdata, int *flags)"
.br
.ti -1c
.RI "int \fBt_rcvuderr\fR (ACE_HANDLE fildes, struct t_uderr *uderr)"
.br
.ti -1c
.RI "int \fBt_snd\fR (ACE_HANDLE fildes, const char *buf, unsigned int nbytes, int flags)"
.br
.ti -1c
.RI "int \fBt_snddis\fR (ACE_HANDLE fildes, struct t_call *call)"
.br
.ti -1c
.RI "int \fBt_sndrel\fR (ACE_HANDLE fildes)"
.br
.ti -1c
.RI "int \fBt_sync\fR (ACE_HANDLE fildes)"
.br
.ti -1c
.RI "int \fBt_unbind\fR (ACE_HANDLE fildes)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
This class is a wrapper for the TLI operations.
.PP
.PP
 
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS int ACE_OS_TLI::t_accept (ACE_HANDLE fildes, ACE_HANDLE resfd, struct t_call * call)\fC [static]\fR
.PP
.SS char* ACE_OS_TLI::t_alloc (ACE_HANDLE fildes, int struct_type, int fields)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_bind (ACE_HANDLE fildes, struct t_bind * req, struct t_bind * ret)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_close (ACE_HANDLE fildes)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_connect (ACE_HANDLE fildes, struct t_call * sndcall, struct t_call * rcvcall)\fC [static]\fR
.PP
.SS void ACE_OS_TLI::t_error (const char * errmsg)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_free (char * ptr, int struct_type)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_getinfo (ACE_HANDLE fildes, struct t_info * info)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_getname (ACE_HANDLE fildes, struct netbuf * namep, int type)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_getstate (ACE_HANDLE fildes)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_listen (ACE_HANDLE fildes, struct t_call * call)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_look (ACE_HANDLE fildes)\fC [static]\fR
.PP
.SS ACE_HANDLE ACE_OS_TLI::t_open (char * path, int oflag, struct t_info * info)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_optmgmt (ACE_HANDLE fildes, struct t_optmgmt * req, struct t_optmgmt * ret)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_rcv (ACE_HANDLE fildes, char * buf, unsigned int nbytes, int * flags)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_rcvdis (ACE_HANDLE fildes, struct t_discon * discon)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_rcvrel (ACE_HANDLE fildes)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_rcvudata (ACE_HANDLE fildes, struct t_unitdata * unitdata, int * flags)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_rcvuderr (ACE_HANDLE fildes, struct t_uderr * uderr)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_snd (ACE_HANDLE fildes, const char * buf, unsigned int nbytes, int flags)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_snddis (ACE_HANDLE fildes, struct t_call * call)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_sndrel (ACE_HANDLE fildes)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_sync (ACE_HANDLE fildes)\fC [static]\fR
.PP
.SS int ACE_OS_TLI::t_unbind (ACE_HANDLE fildes)\fC [static]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.