.TH ACE_Hash< char > 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Hash< char > \- Function object for hashing a char. 
.SH SYNOPSIS
.br
.PP
\fC#include <Functor.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "u_long \fBoperator()\fR (char t) const"
.br
.RI "\fISimply returns t.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Function object for hashing a char.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS u_long \fBACE_Hash\fR< char >::operator() (char t) const
.PP
Simply returns t.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.