.TH ACE_Log_Msg_NT_Event_Log 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Log_Msg_NT_Event_Log \- Implements an \fBACE_Log_Msg_Backend\fR that logs to the WinNT system event log. 
.SH SYNOPSIS
.br
.PP
\fC#include <Log_Msg_NT_Event_Log.h>\fR
.PP
Inherits \fBACE_Log_Msg_Backend\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Log_Msg_NT_Event_Log\fR (void)"
.br
.RI "\fIConstructor.\fR"
.ti -1c
.RI "virtual \fB~ACE_Log_Msg_NT_Event_Log\fR (void)"
.br
.RI "\fIDestructor.\fR"
.ti -1c
.RI "virtual int \fBopen\fR (const \fBACE_TCHAR\fR *logger_key)"
.br
.RI "\fIOpen a new event log.\fR"
.ti -1c
.RI "virtual int \fBreset\fR (void)"
.br
.RI "\fIReset the backend.\fR"
.ti -1c
.RI "virtual int \fBclose\fR (void)"
.br
.RI "\fIClose the backend completely.\fR"
.ti -1c
.RI "virtual int \fBlog\fR (\fBACE_Log_Record\fR &log_record)"
.br
.RI "\fIThis is called when we want to log a message.\fR"
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "HANDLE \fBevlog_handle_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Implements an \fBACE_Log_Msg_Backend\fR that logs to the WinNT system event log.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Log_Msg_NT_Event_Log::ACE_Log_Msg_NT_Event_Log (void)
.PP
Constructor.
.PP
.SS ACE_Log_Msg_NT_Event_Log::~ACE_Log_Msg_NT_Event_Log (void)\fC [virtual]\fR
.PP
Destructor.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS int ACE_Log_Msg_NT_Event_Log::close (void)\fC [virtual]\fR
.PP
Close the backend completely.
.PP
Reimplemented from \fBACE_Log_Msg_Backend\fR.
.SS int ACE_Log_Msg_NT_Event_Log::log (\fBACE_Log_Record\fR & log_record)\fC [virtual]\fR
.PP
This is called when we want to log a message.
.PP
Reimplemented from \fBACE_Log_Msg_Backend\fR.
.SS int ACE_Log_Msg_NT_Event_Log::open (const \fBACE_TCHAR\fR * logger_key)\fC [virtual]\fR
.PP
Open a new event log.
.PP
Reimplemented from \fBACE_Log_Msg_Backend\fR.
.SS int ACE_Log_Msg_NT_Event_Log::reset (void)\fC [virtual]\fR
.PP
Reset the backend.
.PP
Reimplemented from \fBACE_Log_Msg_Backend\fR.
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS HANDLE ACE_Log_Msg_NT_Event_Log::evlog_handle_\fC [private]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.