.TH ACE_Configuration_Section_Key 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Configuration_Section_Key \- Referenced counted wrapper for . 
.SH SYNOPSIS
.br
.PP
\fC#include <Configuration.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Configuration_Section_Key\fR (void)"
.br
.RI "\fIDefault ctor.\fR"
.ti -1c
.RI "ACE_EXPLICIT \fBACE_Configuration_Section_Key\fR (\fBACE_Section_Key_Internal\fR *key)"
.br
.RI "\fIctor based on a pointer to a concrete internal key, does an add_ref on <key>.\fR"
.ti -1c
.RI "\fBACE_Configuration_Section_Key\fR (const ACE_Configuration_Section_Key &rhs)"
.br
.RI "\fICopy ctor, does an add_ref on rhs.key_.\fR"
.ti -1c
.RI "\fB~ACE_Configuration_Section_Key\fR (void)"
.br
.RI "\fIdestructor, does a <dec_ref> on <key_>.\fR"
.ti -1c
.RI "ACE_Configuration_Section_Key& \fBoperator=\fR (const ACE_Configuration_Section_Key &rhs)"
.br
.RI "\fIassignment operator, does a <dec_ref> on <key_> and  to <rhs.key_>.\fR"
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "\fBACE_Section_Key_Internal\fR* \fBkey_\fR"
.br
.in -1c
.SS Friends

.in +1c
.ti -1c
.RI "class \fBACE_Configuration\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Referenced counted wrapper for .
.PP
.PP
 Reference counted wrapper class for the abstract internal section key. A user gets one of these to represent a section in the configuration database. 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Configuration_Section_Key::ACE_Configuration_Section_Key (void)
.PP
Default ctor.
.PP
.SS ACE_EXPLICIT ACE_Configuration_Section_Key::ACE_Configuration_Section_Key (\fBACE_Section_Key_Internal\fR * key)
.PP
ctor based on a pointer to a concrete internal key, does an add_ref on <key>.
.PP
.SS ACE_Configuration_Section_Key::ACE_Configuration_Section_Key (const ACE_Configuration_Section_Key & rhs)
.PP
Copy ctor, does an add_ref on rhs.key_.
.PP
.SS ACE_Configuration_Section_Key::~ACE_Configuration_Section_Key (void)
.PP
destructor, does a <dec_ref> on <key_>.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS ACE_Configuration_Section_Key & ACE_Configuration_Section_Key::operator= (const ACE_Configuration_Section_Key & rhs)
.PP
assignment operator, does a <dec_ref> on <key_> and  to <rhs.key_>.
.PP
.SH FRIENDS AND RELATED FUNCTION DOCUMENTATION
.PP 
.SS class ACE_Configuration\fC [friend]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_Section_Key_Internal\fR * ACE_Configuration_Section_Key::key_\fC [private]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.