.TH ACE_Flow_Spec 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Flow_Spec \- Wrapper class that defines the flow spec QoS information, which is used by IntServ (RSVP) and DiffServ. 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Flow_Spec\fR (void)"
.br
.RI "\fIDefault constructor.\fR"
.ti -1c
.RI "\fBACE_Flow_Spec\fR (u_long token_rate, u_long token_bucket_size, u_long peak_bandwidth, u_long latency, u_long delay_variation, \fBACE_SERVICE_TYPE\fR service_type, u_long max_sdu_size, u_long minimum_policed_size, int ttl, int priority)"
.br
.RI "\fIConstructor that initializes all the fields.\fR"
.ti -1c
.RI "u_long \fBtoken_rate\fR (void) const"
.br
.ti -1c
.RI "void \fBtoken_rate\fR (u_long tr)"
.br
.ti -1c
.RI "u_long \fBtoken_bucket_size\fR (void) const"
.br
.ti -1c
.RI "void \fBtoken_bucket_size\fR (u_long tbs)"
.br
.ti -1c
.RI "u_long \fBpeak_bandwidth\fR (void) const"
.br
.ti -1c
.RI "void \fBpeak_bandwidth\fR (u_long pb)"
.br
.ti -1c
.RI "u_long \fBlatency\fR (void) const"
.br
.ti -1c
.RI "void \fBlatency\fR (u_long l)"
.br
.ti -1c
.RI "u_long \fBdelay_variation\fR (void) const"
.br
.ti -1c
.RI "void \fBdelay_variation\fR (u_long dv)"
.br
.ti -1c
.RI "\fBACE_SERVICE_TYPE\fR \fBservice_type\fR (void) const"
.br
.ti -1c
.RI "void \fBservice_type\fR (\fBACE_SERVICE_TYPE\fR st)"
.br
.ti -1c
.RI "u_long \fBmax_sdu_size\fR (void) const"
.br
.ti -1c
.RI "void \fBmax_sdu_size\fR (u_long mss)"
.br
.ti -1c
.RI "u_long \fBminimum_policed_size\fR (void) const"
.br
.ti -1c
.RI "void \fBminimum_policed_size\fR (u_long mps)"
.br
.ti -1c
.RI "int \fBttl\fR (void) const"
.br
.ti -1c
.RI "void \fBttl\fR (int t)"
.br
.ti -1c
.RI "int \fBpriority\fR (void) const"
.br
.ti -1c
.RI "void \fBpriority\fR (int p)"
.br
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "u_long \fBtoken_rate_\fR"
.br
.ti -1c
.RI "u_long \fBtoken_bucket_size_\fR"
.br
.ti -1c
.RI "u_long \fBpeak_bandwidth_\fR"
.br
.ti -1c
.RI "u_long \fBlatency_\fR"
.br
.ti -1c
.RI "u_long \fBdelay_variation_\fR"
.br
.ti -1c
.RI "\fBACE_SERVICE_TYPE\fR \fBservice_type_\fR"
.br
.ti -1c
.RI "u_long \fBmax_sdu_size_\fR"
.br
.ti -1c
.RI "u_long \fBminimum_policed_size_\fR"
.br
.ti -1c
.RI "int \fBttl_\fR"
.br
.ti -1c
.RI "int \fBpriority_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Wrapper class that defines the flow spec QoS information, which is used by IntServ (RSVP) and DiffServ.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Flow_Spec::ACE_Flow_Spec (void)
.PP
Default constructor.
.PP
.SS ACE_Flow_Spec::ACE_Flow_Spec (u_long token_rate, u_long token_bucket_size, u_long peak_bandwidth, u_long latency, u_long delay_variation, \fBACE_SERVICE_TYPE\fR service_type, u_long max_sdu_size, u_long minimum_policed_size, int ttl, int priority)
.PP
Constructor that initializes all the fields.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void ACE_Flow_Spec::delay_variation (u_long dv)
.PP
.SS u_long ACE_Flow_Spec::delay_variation (void) const
.PP
.SS void ACE_Flow_Spec::latency (u_long l)
.PP
.SS u_long ACE_Flow_Spec::latency (void) const
.PP
.SS void ACE_Flow_Spec::max_sdu_size (u_long mss)
.PP
.SS u_long ACE_Flow_Spec::max_sdu_size (void) const
.PP
.SS void ACE_Flow_Spec::minimum_policed_size (u_long mps)
.PP
.SS u_long ACE_Flow_Spec::minimum_policed_size (void) const
.PP
.SS void ACE_Flow_Spec::peak_bandwidth (u_long pb)
.PP
.SS u_long ACE_Flow_Spec::peak_bandwidth (void) const
.PP
.SS void ACE_Flow_Spec::priority (int p)
.PP
.SS int ACE_Flow_Spec::priority (void) const
.PP
.SS void ACE_Flow_Spec::service_type (\fBACE_SERVICE_TYPE\fR st)
.PP
.SS \fBACE_SERVICE_TYPE\fR ACE_Flow_Spec::service_type (void) const
.PP
.SS void ACE_Flow_Spec::token_bucket_size (u_long tbs)
.PP
.SS u_long ACE_Flow_Spec::token_bucket_size (void) const
.PP
.SS void ACE_Flow_Spec::token_rate (u_long tr)
.PP
.SS u_long ACE_Flow_Spec::token_rate (void) const
.PP
.SS void ACE_Flow_Spec::ttl (int t)
.PP
.SS int ACE_Flow_Spec::ttl (void) const
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS u_long ACE_Flow_Spec::delay_variation_\fC [private]\fR
.PP
.SS u_long ACE_Flow_Spec::latency_\fC [private]\fR
.PP
.SS u_long ACE_Flow_Spec::max_sdu_size_\fC [private]\fR
.PP
.SS u_long ACE_Flow_Spec::minimum_policed_size_\fC [private]\fR
.PP
.SS u_long ACE_Flow_Spec::peak_bandwidth_\fC [private]\fR
.PP
.SS int ACE_Flow_Spec::priority_\fC [private]\fR
.PP
.SS \fBACE_SERVICE_TYPE\fR ACE_Flow_Spec::service_type_\fC [private]\fR
.PP
.SS u_long ACE_Flow_Spec::token_bucket_size_\fC [private]\fR
.PP
.SS u_long ACE_Flow_Spec::token_rate_\fC [private]\fR
.PP
.SS int ACE_Flow_Spec::ttl_\fC [private]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.