.TH ACE_Bcast_Node 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Bcast_Node \- Linked list of broadcast interfaces. 
.SH SYNOPSIS
.br
.PP
\fC#include <SOCK_Dgram_Bcast.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Bcast_Node\fR (\fBACE_INET_Addr\fR &, ACE_Bcast_Node *)"
.br
.RI "\fIDefault dtor.\fR"
.ti -1c
.RI "\fB~ACE_Bcast_Node\fR (void)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBACE_INET_Addr\fR \fBbcast_addr_\fR"
.br
.RI "\fIBroadcast address for the interface.\fR"
.ti -1c
.RI "ACE_Bcast_Node* \fBnext_\fR"
.br
.RI "\fIPointer to the next interface in the chain.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Linked list of broadcast interfaces.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Bcast_Node::ACE_Bcast_Node (\fBACE_INET_Addr\fR &, ACE_Bcast_Node *)
.PP
Default dtor.
.PP
.SS ACE_Bcast_Node::~ACE_Bcast_Node (void)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_INET_Addr\fR ACE_Bcast_Node::bcast_addr_
.PP
Broadcast address for the interface.
.PP
.SS ACE_Bcast_Node * ACE_Bcast_Node::next_
.PP
Pointer to the next interface in the chain.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.