.TH ACE_Hash_Map_Reverse_Iterator 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Hash_Map_Reverse_Iterator \- Wrapper for backward compatibility. 
.SH SYNOPSIS
.br
.PP
\fC#include <Hash_Map_Manager_T.h>\fR
.PP
Inherits \fBACE_Hash_Map_Reverse_Iterator_Ex< EXT_ID,INT_ID,ACE_Hash< EXT_ID >,ACE_Equal_To< EXT_ID >,ACE_LOCK >\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Hash_Map_Reverse_Iterator\fR (\fBACE_Hash_Map_Manager\fR<EXT_ID, INT_ID, ACE_LOCK> &mm, int head = 0)"
.br
.ti -1c
.RI "\fBACE_Hash_Map_Reverse_Iterator\fR (const \fBACE_Hash_Map_Reverse_Iterator_Ex\fR<EXT_ID, INT_ID, \fBACE_Hash\fR<EXT_ID>, \fBACE_Equal_To\fR<EXT_ID>, ACE_LOCK> &base)"
.br
.RI "\fIConstruct from base.\fR"
.ti -1c
.RI "ACE_Hash_Map_Reverse_Iterator<EXT_ID, INT_ID, ACE_LOCK>& \fBoperator=\fR (const \fBACE_Hash_Map_Reverse_Iterator_Ex\fR<EXT_ID, INT_ID, \fBACE_Hash\fR<EXT_ID>, \fBACE_Equal_To\fR<EXT_ID>, ACE_LOCK> &base)"
.br
.RI "\fIAssignment from base.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class EXT_ID, class INT_ID, class ACE_LOCK>  template class ACE_Hash_Map_Reverse_Iterator
Wrapper for backward compatibility.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classEXT_ID, classINT_ID, classACE_LOCK> ACE_Hash_Map_Reverse_Iterator<EXT_ID, INT_ID, ACE_LOCK>::ACE_Hash_Map_Reverse_Iterator<EXT_ID, INT_ID, ACE_LOCK> (\fBACE_Hash_Map_Manager\fR< EXT_ID,INT_ID,ACE_LOCK >& mm, int head = 0)
.PP
.SS template<classEXT_ID, classINT_ID, classACE_LOCK> ACE_Hash_Map_Reverse_Iterator<EXT_ID, INT_ID, ACE_LOCK>::ACE_Hash_Map_Reverse_Iterator<EXT_ID, INT_ID, ACE_LOCK> (const \fBACE_Hash_Map_Reverse_Iterator_Ex\fR< EXT_ID,INT_ID,\fBACE_Hash\fR< EXT_ID >,\fBACE_Equal_To\fR< EXT_ID >,ACE_LOCK >& base)
.PP
Construct from base.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classEXT_ID, classINT_ID, classACE_LOCK> ACE_Hash_Map_Reverse_Iterator< EXT_ID,INT_ID,ACE_LOCK >& ACE_Hash_Map_Reverse_Iterator<EXT_ID, INT_ID, ACE_LOCK>::operator= (const \fBACE_Hash_Map_Reverse_Iterator_Ex\fR< EXT_ID,INT_ID,\fBACE_Hash\fR< EXT_ID >,\fBACE_Equal_To\fR< EXT_ID >,ACE_LOCK >& base)
.PP
Assignment from base.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.