.TH ACE_InputCDR::Transfer_Contents 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_InputCDR::Transfer_Contents \- Helper class to transfer the contents from one input CDR to another without requiring any extra memory allocations, data copies or too many temporaries. 
.SH SYNOPSIS
.br
.PP
\fC#include <CDR_Stream.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBTransfer_Contents\fR (\fBACE_InputCDR\fR &rhs)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBACE_InputCDR\fR& \fBrhs_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Helper class to transfer the contents from one input CDR to another without requiring any extra memory allocations, data copies or too many temporaries.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_InputCDR::Transfer_Contents::Transfer_Contents (\fBACE_InputCDR\fR & rhs)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_InputCDR\fR & ACE_InputCDR::Transfer_Contents::rhs_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.