.TH ACE_Null_Cleanup_Strategy 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Null_Cleanup_Strategy \- Defines a do-nothing implementation of the cleanup strategy. 
.SH SYNOPSIS
.br
.PP
\fC#include <Cleanup_Strategies_T.h>\fR
.PP
Inherits \fBACE_Cleanup_Strategy< KEY,VALUE,CONTAINER >\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "virtual int \fBcleanup\fR (CONTAINER &container, KEY *key, VALUE *value)"
.br
.RI "\fIThe dummy cleanup method.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class KEY, class VALUE, class CONTAINER>  template class ACE_Null_Cleanup_Strategy
Defines a do-nothing implementation of the cleanup strategy.
.PP
.PP
 This class simply does nothing at all! Can be used to nullify the effect of the Cleanup Strategy. 
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classKEY, classVALUE, classCONTAINER> int ACE_Null_Cleanup_Strategy<KEY, VALUE, CONTAINER>::cleanup (CONTAINER & container, KEY * key, VALUE * value)\fC [virtual]\fR
.PP
The dummy cleanup method.
.PP
Reimplemented from \fBACE_Cleanup_Strategy\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.