.TH ACE_OutputCDR::from_wchar 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_OutputCDR::from_wchar \- 
.SH SYNOPSIS
.br
.PP
\fC#include <CDR_Stream.h>\fR
.PP
.SS Helper classes

.in +1c
.ti -1c
.RI "\fBfrom_wchar\fR (\fBACE_CDR::WChar\fR wc)"
.br
.ti -1c
.RI "\fBACE_CDR::WChar\fR \fBval_\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_OutputCDR::from_wchar::from_wchar (\fBACE_CDR::WChar\fR wc)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_CDR::WChar\fR ACE_OutputCDR::from_wchar::val_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.