.TH ACE_QoS 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_QoS \- Wrapper class that holds the sender and receiver flow spec information, which is used by IntServ (RSVP) and DiffServ. 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_QoS\fR (void)"
.br
.ti -1c
.RI "\fBACE_Flow_Spec\fR* \fBsending_flowspec\fR (void) const"
.br
.ti -1c
.RI "void \fBsending_flowspec\fR (\fBACE_Flow_Spec\fR *fs)"
.br
.ti -1c
.RI "\fBACE_Flow_Spec\fR* \fBreceiving_flowspec\fR (void) const"
.br
.ti -1c
.RI "void \fBreceiving_flowspec\fR (\fBACE_Flow_Spec\fR *fs)"
.br
.ti -1c
.RI "\fBiovec\fR \fBprovider_specific\fR (void) const"
.br
.ti -1c
.RI "void \fBprovider_specific\fR (const \fBiovec\fR &ps)"
.br
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "\fBACE_Flow_Spec\fR* \fBsending_flowspec_\fR"
.br
.ti -1c
.RI "\fBACE_Flow_Spec\fR* \fBreceiving_flowspec_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Wrapper class that holds the sender and receiver flow spec information, which is used by IntServ (RSVP) and DiffServ.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_QoS::ACE_QoS (void)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void ACE_QoS::provider_specific (const \fBiovec\fR & ps)
.PP
.SS \fBiovec\fR ACE_QoS::provider_specific (void) const
.PP
.SS void ACE_QoS::receiving_flowspec (\fBACE_Flow_Spec\fR * fs)
.PP
.SS \fBACE_Flow_Spec\fR* ACE_QoS::receiving_flowspec (void) const
.PP
.SS void ACE_QoS::sending_flowspec (\fBACE_Flow_Spec\fR * fs)
.PP
.SS \fBACE_Flow_Spec\fR* ACE_QoS::sending_flowspec (void) const
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_Flow_Spec\fR * ACE_QoS::receiving_flowspec_\fC [private]\fR
.PP
.SS \fBACE_Flow_Spec\fR * ACE_QoS::sending_flowspec_\fC [private]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.