.TH ACE_Section_Key_Win32 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Section_Key_Win32 \- The Win32 registry implementation of an internal section key. 
.SH SYNOPSIS
.br
.PP
\fC#include <Configuration.h>\fR
.PP
Inherits \fBACE_Section_Key_Internal\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Section_Key_Win32\fR (HKEY hKey)"
.br
.RI "\fIconstructor based on an HKEY.\fR"
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "HKEY \fBhKey_\fR"
.br
.in -1c
.SS Protected Methods

.in +1c
.ti -1c
.RI "virtual \fB~ACE_Section_Key_Win32\fR (void)"
.br
.RI "\fIdestructor - invokes <RegCloseKey>.\fR"
.ti -1c
.RI "\fBACE_Section_Key_Win32\fR (const ACE_Section_Key_Win32& rhs)"
.br
.ti -1c
.RI "ACE_Section_Key_Win32& \fBoperator=\fR (const ACE_Section_Key_Win32& rhs)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
The Win32 registry implementation of an internal section key.
.PP
.PP
 Holds the HKEY for a section (registry key). 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Section_Key_Win32::ACE_Section_Key_Win32 (HKEY hKey)
.PP
constructor based on an HKEY.
.PP
.SS ACE_Section_Key_Win32::~ACE_Section_Key_Win32 (void)\fC [protected, virtual]\fR
.PP
destructor - invokes <RegCloseKey>.
.PP
.SS ACE_Section_Key_Win32::ACE_Section_Key_Win32 (const ACE_Section_Key_Win32 & rhs)\fC [protected]\fR
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS ACE_Section_Key_Win32& ACE_Section_Key_Win32::operator= (const ACE_Section_Key_Win32 & rhs)\fC [protected]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS HKEY ACE_Section_Key_Win32::hKey_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.