.TH ACE_Timer_Wheel_Iterator_T 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Timer_Wheel_Iterator_T \- Iterates over an . 
.SH SYNOPSIS
.br
.PP
\fC#include <Timer_Wheel_T.h>\fR
.PP
Inherits \fBACE_Timer_Queue_Iterator_T< TYPE,FUNCTOR,ACE_LOCK >\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Timer_Wheel_Iterator_T\fR (\fBACE_Timer_Wheel_T\fR<TYPE, FUNCTOR, ACE_LOCK> &)"
.br
.RI "\fIConstructor.\fR"
.ti -1c
.RI "\fB~ACE_Timer_Wheel_Iterator_T\fR (void)"
.br
.RI "\fIDestructor.\fR"
.ti -1c
.RI "virtual void \fBfirst\fR (void)"
.br
.RI "\fIPositions the iterator at the earliest node in the Timer Queue.\fR"
.ti -1c
.RI "virtual void \fBnext\fR (void)"
.br
.RI "\fIPositions the iterator at the next node in the Timer Queue.\fR"
.ti -1c
.RI "virtual int \fBisdone\fR (void) const"
.br
.RI "\fIReturns true when there are no more nodes in the sequence.\fR"
.ti -1c
.RI "virtual \fBACE_Timer_Node_T\fR<TYPE>* \fBitem\fR (void)"
.br
.RI "\fIReturns the node at the current position in the sequence.\fR"
.in -1c
.SS Protected Attributes

.in +1c
.ti -1c
.RI "\fBACE_Timer_Wheel_T\fR<TYPE, FUNCTOR, ACE_LOCK>& \fBtimer_wheel_\fR"
.br
.RI "\fIPointer to the  that we are iterating over.\fR"
.ti -1c
.RI "size_t \fBpos_\fR"
.br
.RI "\fICurrent position in the timing wheel.\fR"
.ti -1c
.RI "\fBACE_Timer_Node_T\fR<TYPE>* \fBlist_item_\fR"
.br
.RI "\fIPointer to the position in the the <pos_>th list.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class TYPE, class FUNCTOR, class ACE_LOCK>  template class ACE_Timer_Wheel_Iterator_T
Iterates over an .
.PP
.PP
 This is a generic iterator that can be used to visit every node of a timer queue. Be aware that it doesn't transverse in the order of timeout values. 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classTYPE, classFUNCTOR, classACE_LOCK> ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK>::ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK> (\fBACE_Timer_Wheel_T\fR< TYPE,FUNCTOR,ACE_LOCK >&)
.PP
Constructor.
.PP
.SS template<classTYPE, classFUNCTOR, classACE_LOCK> ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK>::~ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK> (void)
.PP
Destructor.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classTYPE, classFUNCTOR, classACE_LOCK> void ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK>::first (void)\fC [virtual]\fR
.PP
Positions the iterator at the earliest node in the Timer Queue.
.PP
Reimplemented from \fBACE_Timer_Queue_Iterator_T\fR.
.SS template<classTYPE, classFUNCTOR, classACE_LOCK> int ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK>::isdone (void) const\fC [virtual]\fR
.PP
Returns true when there are no more nodes in the sequence.
.PP
Reimplemented from \fBACE_Timer_Queue_Iterator_T\fR.
.SS template<classTYPE, classFUNCTOR, classACE_LOCK> \fBACE_Timer_Node_T\fR< TYPE >* ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK>::item (void)\fC [virtual]\fR
.PP
Returns the node at the current position in the sequence.
.PP
Reimplemented from \fBACE_Timer_Queue_Iterator_T\fR.
.SS template<classTYPE, classFUNCTOR, classACE_LOCK> void ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK>::next (void)\fC [virtual]\fR
.PP
Positions the iterator at the next node in the Timer Queue.
.PP
Reimplemented from \fBACE_Timer_Queue_Iterator_T\fR.
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS template<classTYPE, classFUNCTOR, classACE_LOCK> \fBACE_Timer_Node_T\fR< TYPE >* ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK>::list_item_\fC [protected]\fR
.PP
Pointer to the position in the the <pos_>th list.
.PP
.SS template<classTYPE, classFUNCTOR, classACE_LOCK> size_t ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK>::pos_\fC [protected]\fR
.PP
Current position in the timing wheel.
.PP
.SS template<classTYPE, classFUNCTOR, classACE_LOCK> \fBACE_Timer_Wheel_T\fR< TYPE,FUNCTOR,ACE_LOCK >& ACE_Timer_Wheel_Iterator_T<TYPE, FUNCTOR, ACE_LOCK>::timer_wheel_\fC [protected]\fR
.PP
Pointer to the  that we are iterating over.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.