.TH ACE_Hash 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Hash \- Function object for hashing. 
.SH SYNOPSIS
.br
.PP
\fC#include <Functor_T.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "u_long \fBoperator()\fR (const TYPE &t) const"
.br
.RI "\fISimply calls t.hash ().\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class TYPE>  template class ACE_Hash
Function object for hashing.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classTYPE> u_long ACE_Hash<TYPE>::operator() (const TYPE & t) const
.PP
Simply calls t.hash ().
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.