.TH ACE_Recyclable 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Recyclable \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Strategies.h>\fR
.PP
Inherited by \fBACE_Refcounted_Hash_Recyclable\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "virtual \fB~ACE_Recyclable\fR (void)"
.br
.RI "\fIDestructor.\fR"
.ti -1c
.RI "\fBACE_Recyclable_State\fR \fBrecycle_state\fR (void) const"
.br
.ti -1c
.RI "void \fBrecycle_state\fR (\fBACE_Recyclable_State\fR new_state)"
.br
.in -1c
.SS Protected Methods

.in +1c
.ti -1c
.RI "\fBACE_Recyclable\fR (\fBACE_Recyclable_State\fR initial_state)"
.br
.RI "\fIProtected constructor.\fR"
.in -1c
.SS Protected Attributes

.in +1c
.ti -1c
.RI "\fBACE_Recyclable_State\fR \fBrecycle_state_\fR"
.br
.RI "\fIOur state.\fR"
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Recyclable::~ACE_Recyclable (void)\fC [virtual]\fR
.PP
Destructor.
.PP
.SS ACE_Recyclable::ACE_Recyclable (\fBACE_Recyclable_State\fR initial_state)\fC [protected]\fR
.PP
Protected constructor.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void ACE_Recyclable::recycle_state (\fBACE_Recyclable_State\fR new_state)
.PP
.SS \fBACE_Recyclable_State\fR ACE_Recyclable::recycle_state (void) const
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_Recyclable_State\fR ACE_Recyclable::recycle_state_\fC [protected]\fR
.PP
Our state.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.