.TH ACE_OutputCDR::from_wstring 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_OutputCDR::from_wstring \- 
.SH SYNOPSIS
.br
.PP
\fC#include <CDR_Stream.h>\fR
.PP
.SS Helper classes

.in +1c
.ti -1c
.RI "\fBfrom_wstring\fR (\fBACE_CDR::WChar\fR* ws, \fBACE_CDR::ULong\fR b, \fBACE_CDR::Boolean\fR nocopy = 0)"
.br
.ti -1c
.RI "\fBfrom_wstring\fR (const \fBACE_CDR::WChar\fR* ws, \fBACE_CDR::ULong\fR b, \fBACE_CDR::Boolean\fR nocopy = 0)"
.br
.ti -1c
.RI "\fBACE_CDR::WChar\fR* \fBval_\fR"
.br
.ti -1c
.RI "\fBACE_CDR::ULong\fR \fBbound_\fR"
.br
.ti -1c
.RI "\fBACE_CDR::Boolean\fR \fBnocopy_\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_OutputCDR::from_wstring::from_wstring (\fBACE_CDR::WChar\fR * ws, \fBACE_CDR::ULong\fR b, \fBACE_CDR::Boolean\fR nocopy = 0)
.PP
.SS ACE_OutputCDR::from_wstring::from_wstring (const \fBACE_CDR::WChar\fR * ws, \fBACE_CDR::ULong\fR b, \fBACE_CDR::Boolean\fR nocopy = 0)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_CDR::ULong\fR ACE_OutputCDR::from_wstring::bound_
.PP
.SS \fBACE_CDR::Boolean\fR ACE_OutputCDR::from_wstring::nocopy_
.PP
.SS \fBACE_CDR::WChar\fR * ACE_OutputCDR::from_wstring::val_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.