.TH ACE_Dynamic_Service_Base 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Dynamic_Service_Base \- Base class for all \fBACE_Dynamic_Service\fR instantiations. 
.SH SYNOPSIS
.br
.PP
\fC#include <Dynamic_Service_Base.h>\fR
.PP
Inherited by \fBACE_Dynamic_Service\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "void \fBdump\fR (void) const"
.br
.RI "\fIDump the current static of the object.\fR"
.in -1c
.SS Static Protected Methods

.in +1c
.ti -1c
.RI "void* \fBinstance\fR (const \fBACE_TCHAR\fR *name)"
.br
.RI "\fIReturn instance using <name> to search the Service_Repository.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Base class for all \fBACE_Dynamic_Service\fR instantiations.
.PP
.PP
 Factors out common code shared by all \fBACE_Dynamic_Service\fR instantiations, this avoid code bloat. 
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void ACE_Dynamic_Service_Base::dump (void) const
.PP
Dump the current static of the object.
.PP
.SS void * ACE_Dynamic_Service_Base::instance (const \fBACE_TCHAR\fR * name)\fC [static, protected]\fR
.PP
Return instance using <name> to search the Service_Repository.
.PP
Reimplemented in \fBACE_Dynamic_Service\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.