.TH ACE_Registry::Binding_Iterator::Iteration_State 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Registry::Binding_Iterator::Iteration_State \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Registry.h>\fR
.PP
Inherited by \fBACE_Registry::Binding_Iterator::Context_Iteration\fR, \fBACE_Registry::Binding_Iterator::Iteration_Complete\fR, and \fBACE_Registry::Binding_Iterator::Object_Iteration\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBIteration_State\fR (\fBBinding_Iterator\fR &iterator)"
.br
.ti -1c
.RI "virtual int \fBnext_n\fR (u_long how_many, \fBBinding_List\fR &list) = 0"
.br
.RI "\fINext <how_many> entries.\fR"
.ti -1c
.RI "void \fBreset\fR (void)"
.br
.RI "\fIReset state.\fR"
.in -1c
.SS Protected Attributes

.in +1c
.ti -1c
.RI "\fBBinding_Iterator\fR* \fBparent_\fR"
.br
.RI "\fIPointer to parent iterator.\fR"
.ti -1c
.RI "u_long \fBindex_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Base class for state 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Registry::Binding_Iterator::Iteration_State::Iteration_State (\fBBinding_Iterator\fR & iterator)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS int ACE_Registry::Binding_Iterator::Iteration_State::next_n (u_long how_many, \fBBinding_List\fR & list)\fC [pure virtual]\fR
.PP
Next <how_many> entries.
.PP
Reimplemented in \fBACE_Registry::Binding_Iterator::Object_Iteration\fR, \fBACE_Registry::Binding_Iterator::Context_Iteration\fR, and \fBACE_Registry::Binding_Iterator::Iteration_Complete\fR.
.SS void ACE_Registry::Binding_Iterator::Iteration_State::reset (void)
.PP
Reset state.
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS u_long ACE_Registry::Binding_Iterator::Iteration_State::index_\fC [protected]\fR
.PP
.SS \fBBinding_Iterator\fR * ACE_Registry::Binding_Iterator::Iteration_State::parent_\fC [protected]\fR
.PP
Pointer to parent iterator.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.