.TH ACE_SPIPE_Addr::SPIPE_Addr 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_SPIPE_Addr::SPIPE_Addr \- Contains security attributes. 
.SH SYNOPSIS
.br
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBgid_t\fR \fBgid_\fR"
.br
.ti -1c
.RI "\fBuid_t\fR \fBuid_\fR"
.br
.ti -1c
.RI "\fBACE_TCHAR\fR \fBrendezvous_\fR [MAXNAMLEN + 1]"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Contains security attributes.
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBgid_t\fR ACE_SPIPE_Addr::SPIPE_Addr::gid_
.PP
.SS \fBACE_TCHAR\fR ACE_SPIPE_Addr::SPIPE_Addr::rendezvous_[MAXNAMLEN+1]
.PP
.SS \fBuid_t\fR ACE_SPIPE_Addr::SPIPE_Addr::uid_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.