.TH ACE_Protocol_Info 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Protocol_Info \- 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "u_long \fBdwServiceFlags1\fR"
.br
.ti -1c
.RI "int \fBiAddressFamily\fR"
.br
.ti -1c
.RI "int \fBiProtocol\fR"
.br
.ti -1c
.RI "char \fBszProtocol\fR [255+1]"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS u_long ACE_Protocol_Info::dwServiceFlags1
.PP
.SS int ACE_Protocol_Info::iAddressFamily
.PP
.SS int ACE_Protocol_Info::iProtocol
.PP
.SS char ACE_Protocol_Info::szProtocol[255+1]
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.