.TH ACE_Managed_Process 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Managed_Process \- A process easily managed by \fBACE_Process_Manager\fR. 
.SH SYNOPSIS
.br
.PP
\fC#include <Process.h>\fR
.PP
Inherits \fBACE_Process\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Managed_Process\fR ()"
.br
.ti -1c
.RI "virtual void \fBunmanage\fR (void)"
.br
.RI "\fICalled by a <Process_Manager> that is removing this Process from its table of managed Processes. Default is to do nothing.\fR"
.in -1c
.SS Private Methods

.in +1c
.ti -1c
.RI "virtual \fB~ACE_Managed_Process\fR (void)"
.br
.in -1c
.SS Friends

.in +1c
.ti -1c
.RI "class \fBace_dewarn_gplusplus\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
A process easily managed by \fBACE_Process_Manager\fR.
.PP
.PP
 
.TP
 ACE_Managed_Process is just an 
.TP
 \fBACE_Process\fR with an 
.TP
 unmanage method that deletes the instance. This class is only valid for use as a dynamically-allocated object! 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Managed_Process::ACE_Managed_Process ()
.PP
.SS virtual ACE_Managed_Process::~ACE_Managed_Process (void)\fC [private, virtual]\fR
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS virtual void ACE_Managed_Process::unmanage (void)\fC [virtual]\fR
.PP
Called by a <Process_Manager> that is removing this Process from its table of managed Processes. Default is to do nothing.
.PP
Reimplemented from \fBACE_Process\fR.
.SH FRIENDS AND RELATED FUNCTION DOCUMENTATION
.PP 
.SS class ace_dewarn_gplusplus\fC [friend]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.