.TH ACE_Profile_Timer::ACE_Elapsed_Time 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Profile_Timer::ACE_Elapsed_Time \- Keeps track of the various user, system, and elapsed (real) times. 
.SH SYNOPSIS
.br
.PP
\fC#include <Profile_Timer.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBACE_timer_t\fR \fBreal_time\fR"
.br
.ti -1c
.RI "\fBACE_timer_t\fR \fBuser_time\fR"
.br
.ti -1c
.RI "\fBACE_timer_t\fR \fBsystem_time\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Keeps track of the various user, system, and elapsed (real) times.
.PP
.PP
 If  is enabled these values are in microseconds, otherwise, they are in seconds. 
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_timer_t\fR ACE_Profile_Timer::ACE_Elapsed_Time::real_time
.PP
.SS \fBACE_timer_t\fR ACE_Profile_Timer::ACE_Elapsed_Time::system_time
.PP
.SS \fBACE_timer_t\fR ACE_Profile_Timer::ACE_Elapsed_Time::user_time
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.