.TH ACE_Service_Object_Type 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Service_Object_Type \- Define the methods for handling the configuration of . 
.SH SYNOPSIS
.br
.PP
\fC#include <Service_Types.h>\fR
.PP
Inherits \fBACE_Service_Type_Impl\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Service_Object_Type\fR (void *so, const \fBACE_TCHAR\fR *name, u_int flags = 0, \fBACE_Service_Object_Exterminator\fR gobbler = 0)"
.br
.ti -1c
.RI "\fB~ACE_Service_Object_Type\fR (void)"
.br
.ti -1c
.RI "virtual int \fBsuspend\fR (void) const"
.br
.ti -1c
.RI "virtual int \fBresume\fR (void) const"
.br
.ti -1c
.RI "virtual int \fBinit\fR (int argc, \fBACE_TCHAR\fR *argv[]) const"
.br
.ti -1c
.RI "virtual int \fBfini\fR (void) const"
.br
.ti -1c
.RI "virtual int \fBinfo\fR (\fBACE_TCHAR\fR **str, size_t len) const"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Define the methods for handling the configuration of .
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Service_Object_Type::ACE_Service_Object_Type (void * so, const \fBACE_TCHAR\fR * name, u_int flags = 0, \fBACE_Service_Object_Exterminator\fR gobbler = 0)
.PP
.SS ACE_Service_Object_Type::~ACE_Service_Object_Type (void)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS virtual int ACE_Service_Object_Type::fini (void) const\fC [virtual]\fR
.PP
Reimplemented from \fBACE_Service_Type_Impl\fR.
.SS virtual int ACE_Service_Object_Type::info (\fBACE_TCHAR\fR ** str, size_t len) const\fC [virtual]\fR
.PP
Reimplemented from \fBACE_Service_Type_Impl\fR.
.SS virtual int ACE_Service_Object_Type::init (int argc, \fBACE_TCHAR\fR * argv[]) const\fC [virtual]\fR
.PP
Reimplemented from \fBACE_Service_Type_Impl\fR.
.SS virtual int ACE_Service_Object_Type::resume (void) const\fC [virtual]\fR
.PP
Reimplemented from \fBACE_Service_Type_Impl\fR.
.SS virtual int ACE_Service_Object_Type::suspend (void) const\fC [virtual]\fR
.PP
Reimplemented from \fBACE_Service_Type_Impl\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.