.TH ACE_MT_MEM_IO::Simple_Queue 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_MT_MEM_IO::Simple_Queue \- 
.SH SYNOPSIS
.br
.PP
\fC#include <MEM_IO.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "ACE_INLINE_FOR_GNUC \fBSimple_Queue\fR (void)"
.br
.ti -1c
.RI "\fBSimple_Queue\fR (\fBMQ_Struct\fR *mq)"
.br
.ti -1c
.RI "int \fBinit\fR (\fBMQ_Struct\fR *mq, \fBACE_MEM_SAP::MALLOC_TYPE\fR *malloc)"
.br
.ti -1c
.RI "int \fBwrite\fR (\fBACE_MEM_SAP_Node\fR *new_msg)"
.br
.ti -1c
.RI "\fBACE_MEM_SAP_Node\fR* \fBread\fR (void)"
.br
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "\fBMQ_Struct\fR* \fBmq_\fR"
.br
.ti -1c
.RI "\fBACE_MEM_SAP::MALLOC_TYPE\fR* \fBmalloc_\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_INLINE_FOR_GNUC ACE_MT_MEM_IO::Simple_Queue::Simple_Queue (void)
.PP
.SS ACE_MT_MEM_IO::Simple_Queue::Simple_Queue (\fBMQ_Struct\fR * mq)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS int ACE_MT_MEM_IO::Simple_Queue::init (\fBMQ_Struct\fR * mq, \fBACE_MEM_SAP::MALLOC_TYPE\fR * malloc)
.PP
.SS \fBACE_MEM_SAP_Node\fR* ACE_MT_MEM_IO::Simple_Queue::read (void)
.PP
.SS int ACE_MT_MEM_IO::Simple_Queue::write (\fBACE_MEM_SAP_Node\fR * new_msg)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_MEM_SAP::MALLOC_TYPE\fR * ACE_MT_MEM_IO::Simple_Queue::malloc_\fC [private]\fR
.PP
.SS \fBMQ_Struct\fR * ACE_MT_MEM_IO::Simple_Queue::mq_\fC [private]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.