.TH ACE_Pagefile_Memory_Pool::Control_Block::Shared_Control_Block 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Pagefile_Memory_Pool::Control_Block::Shared_Control_Block \- Pool statistics. 
.SH SYNOPSIS
.br
.PP
\fC#include <Memory_Pool.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "size_t \fBmax_size_\fR"
.br
.RI "\fIMaximum size the pool may grow.\fR"
.ti -1c
.RI "int \fBmapped_size_\fR"
.br
.RI "\fISize of mapped shared memory segment.\fR"
.ti -1c
.RI "int \fBfree_offset_\fR"
.br
.RI "\fIOffset to mapped but not yet acquired address space.\fR"
.ti -1c
.RI "int \fBfree_size_\fR"
.br
.RI "\fISize of mapped but not yet acquired address space.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Pool statistics.
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int ACE_Pagefile_Memory_Pool::Control_Block::Shared_Control_Block::free_offset_
.PP
Offset to mapped but not yet acquired address space.
.PP
.SS int ACE_Pagefile_Memory_Pool::Control_Block::Shared_Control_Block::free_size_
.PP
Size of mapped but not yet acquired address space.
.PP
.SS int ACE_Pagefile_Memory_Pool::Control_Block::Shared_Control_Block::mapped_size_
.PP
Size of mapped shared memory segment.
.PP
.SS size_t ACE_Pagefile_Memory_Pool::Control_Block::Shared_Control_Block::max_size_
.PP
Maximum size the pool may grow.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.