.TH ACE_TTY_IO::Serial_Params 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_TTY_IO::Serial_Params \- 
.SH SYNOPSIS
.br
.PP
\fC#include <TTY_IO.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBbaudrate\fR"
.br
.ti -1c
.RI "int \fBparityenb\fR"
.br
.ti -1c
.RI "const char* \fBparitymode\fR"
.br
.ti -1c
.RI "int \fBdatabits\fR"
.br
.ti -1c
.RI "int \fBstopbits\fR"
.br
.ti -1c
.RI "int \fBreadtimeoutmsec\fR"
.br
.ti -1c
.RI "int \fBctsenb\fR"
.br
.ti -1c
.RI "int \fBrtsenb\fR"
.br
.ti -1c
.RI "int \fBxinenb\fR"
.br
.ti -1c
.RI "int \fBxoutenb\fR"
.br
.ti -1c
.RI "int \fBmodem\fR"
.br
.ti -1c
.RI "int \fBrcvenb\fR"
.br
.ti -1c
.RI "int \fBdsrenb\fR"
.br
.ti -1c
.RI "int \fBxonlim\fR"
.br
.ti -1c
.RI "int \fBxofflim\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int ACE_TTY_IO::Serial_Params::baudrate
.PP
.SS int ACE_TTY_IO::Serial_Params::ctsenb
.PP
.SS int ACE_TTY_IO::Serial_Params::databits
.PP
.SS int ACE_TTY_IO::Serial_Params::dsrenb
.PP
.SS int ACE_TTY_IO::Serial_Params::modem
.PP
.SS int ACE_TTY_IO::Serial_Params::parityenb
.PP
.SS const char * ACE_TTY_IO::Serial_Params::paritymode
.PP
.SS int ACE_TTY_IO::Serial_Params::rcvenb
.PP
.SS int ACE_TTY_IO::Serial_Params::readtimeoutmsec
.PP
.SS int ACE_TTY_IO::Serial_Params::rtsenb
.PP
.SS int ACE_TTY_IO::Serial_Params::stopbits
.PP
.SS int ACE_TTY_IO::Serial_Params::xinenb
.PP
.SS int ACE_TTY_IO::Serial_Params::xofflim
.PP
.SS int ACE_TTY_IO::Serial_Params::xonlim
.PP
.SS int ACE_TTY_IO::Serial_Params::xoutenb
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.