.TH ACE_Token::ACE_Token_Queue_Entry 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Token::ACE_Token_Queue_Entry \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Token.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Token_Queue_Entry\fR (\fBACE_Thread_Mutex\fR &m, \fBACE_thread_t\fR t_id)"
.br
.ti -1c
.RI "\fBACE_Token_Queue_Entry\fR (\fBACE_Thread_Mutex\fR &m, \fBACE_thread_t\fR t_id, \fBACE_Condition_Attributes\fR &attributes)"
.br
.ti -1c
.RI "int \fBwait\fR (\fBACE_Time_Value\fR *timeout, \fBACE_Thread_Mutex\fR &lock)"
.br
.ti -1c
.RI "int \fBsignal\fR (void)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "ACE_Token_Queue_Entry* \fBnext_\fR"
.br
.ti -1c
.RI "\fBACE_thread_t\fR \fBthread_id_\fR"
.br
.ti -1c
.RI "\fBACE_Semaphore\fR \fBcv_\fR"
.br
.ti -1c
.RI "int \fBrunable_\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Token::ACE_Token_Queue_Entry::ACE_Token_Queue_Entry (\fBACE_Thread_Mutex\fR & m, \fBACE_thread_t\fR t_id)
.PP
.SS ACE_Token::ACE_Token_Queue_Entry::ACE_Token_Queue_Entry (\fBACE_Thread_Mutex\fR & m, \fBACE_thread_t\fR t_id, \fBACE_Condition_Attributes\fR & attributes)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS int ACE_Token::ACE_Token_Queue_Entry::signal (void)
.PP
.SS int ACE_Token::ACE_Token_Queue_Entry::wait (\fBACE_Time_Value\fR * timeout, \fBACE_Thread_Mutex\fR & lock)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_Semaphore\fR ACE_Token::ACE_Token_Queue_Entry::cv_
.PP
.SS ACE_Token_Queue_Entry * ACE_Token::ACE_Token_Queue_Entry::next_
.PP
.SS int ACE_Token::ACE_Token_Queue_Entry::runable_
.PP
.SS \fBACE_thread_t\fR ACE_Token::ACE_Token_Queue_Entry::thread_id_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.