.TH ACE_TkReactor_Input_Callback 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_TkReactor_Input_Callback \- 
.SH SYNOPSIS
.br
.PP
\fC#include <TkReactor.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBACE_TkReactor\fR* \fBreactor_\fR"
.br
.ti -1c
.RI "ACE_HANDLE \fBhandle_\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS ACE_HANDLE ACE_TkReactor_Input_Callback::handle_
.PP
.SS \fBACE_TkReactor\fR * ACE_TkReactor_Input_Callback::reactor_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.