.TH ACE_OutputCDR::from_boolean 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_OutputCDR::from_boolean \- 
.SH SYNOPSIS
.br
.PP
\fC#include <CDR_Stream.h>\fR
.PP
.SS Helper classes

.in +1c
.ti -1c
.RI "\fBfrom_boolean\fR (\fBACE_CDR::Boolean\fR b)"
.br
.ti -1c
.RI "\fBACE_CDR::Boolean\fR \fBval_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Disambiguate overload when inserting booleans, octets, chars, and bounded strings. 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_OutputCDR::from_boolean::from_boolean (\fBACE_CDR::Boolean\fR b)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_CDR::Boolean\fR ACE_OutputCDR::from_boolean::val_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.