.TH ACE_DLList_Node 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_DLList_Node \- Base implementation of element in a DL list. Needed for \fBACE_Double_Linked_List\fR. 
.SH SYNOPSIS
.br
.PP
\fC#include <Containers.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_DLList_Node\fR (void *&i, ACE_DLList_Node *n = 0, ACE_DLList_Node *p = 0)"
.br
.ti -1c
.RI "\fB~ACE_DLList_Node\fR (void)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBACE_ALLOC_HOOK_DECLARE\fR"
.br
.RI "\fIDeclare the dynamic allocation hooks.\fR"
.ti -1c
.RI "void* \fBitem_\fR"
.br
.ti -1c
.RI "ACE_DLList_Node* \fBnext_\fR"
.br
.ti -1c
.RI "ACE_DLList_Node* \fBprev_\fR"
.br
.in -1c
.SS Protected Methods

.in +1c
.ti -1c
.RI "\fBACE_DLList_Node\fR (void)"
.br
.in -1c
.SS Friends

.in +1c
.ti -1c
.RI "class \fBACE_Double_Linked_List< ACE_DLList_Node >\fR"
.br
.ti -1c
.RI "class \fBACE_Double_Linked_List_Iterator_Base< ACE_DLList_Node >\fR"
.br
.ti -1c
.RI "class \fBACE_Double_Linked_List_Iterator< ACE_DLList_Node >\fR"
.br
.ti -1c
.RI "class \fBACE_Double_Linked_List_Reverse_Iterator< ACE_DLList_Node >\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Base implementation of element in a DL list. Needed for \fBACE_Double_Linked_List\fR.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_DLList_Node::ACE_DLList_Node (void *& i, ACE_DLList_Node * n = 0, ACE_DLList_Node * p = 0)
.PP
.SS ACE_DLList_Node::~ACE_DLList_Node (void)
.PP
.SS ACE_DLList_Node::ACE_DLList_Node (void)\fC [protected]\fR
.PP
.SH FRIENDS AND RELATED FUNCTION DOCUMENTATION
.PP 
.SS class \fBACE_Double_Linked_List\fR\fC [friend]\fR
.PP
.SS class \fBACE_Double_Linked_List_Iterator\fR\fC [friend]\fR
.PP
.SS class \fBACE_Double_Linked_List_Iterator_Base\fR\fC [friend]\fR
.PP
.SS class \fBACE_Double_Linked_List_Reverse_Iterator\fR\fC [friend]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS ACE_DLList_Node::ACE_ALLOC_HOOK_DECLARE
.PP
Declare the dynamic allocation hooks.
.PP
.SS void * ACE_DLList_Node::item_
.PP
.SS ACE_DLList_Node * ACE_DLList_Node::next_
.PP
.SS ACE_DLList_Node * ACE_DLList_Node::prev_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.