.TH ACE_Select_Reactor_Handle_Set 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Select_Reactor_Handle_Set \- Track handles we are interested for various events. 
.SH SYNOPSIS
.br
.PP
\fC#include <Select_Reactor_Base.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBACE_Handle_Set\fR \fBrd_mask_\fR"
.br
.RI "\fIRead events (e.g., input pending, accept pending).\fR"
.ti -1c
.RI "\fBACE_Handle_Set\fR \fBwr_mask_\fR"
.br
.RI "\fIWrite events (e.g., flow control abated, non-blocking connection complete).\fR"
.ti -1c
.RI "\fBACE_Handle_Set\fR \fBex_mask_\fR"
.br
.RI "\fIException events (e.g., SIG_URG).\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Track handles we are interested for various events.
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_Handle_Set\fR ACE_Select_Reactor_Handle_Set::ex_mask_
.PP
Exception events (e.g., SIG_URG).
.PP
.SS \fBACE_Handle_Set\fR ACE_Select_Reactor_Handle_Set::rd_mask_
.PP
Read events (e.g., input pending, accept pending).
.PP
.SS \fBACE_Handle_Set\fR ACE_Select_Reactor_Handle_Set::wr_mask_
.PP
Write events (e.g., flow control abated, non-blocking connection complete).
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.