.TH ACE_Tokenizer::Preserve_Entry 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Tokenizer::Preserve_Entry \- Preserve Entry. 
.SH SYNOPSIS
.br
.PP
\fC#include <SString.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBACE_TCHAR\fR \fBstart_\fR"
.br
.ti -1c
.RI "\fBACE_TCHAR\fR \fBstop_\fR"
.br
.ti -1c
.RI "int \fBstrip_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Preserve Entry.
.PP
.PP
 Defines a set of characters that designate an area that should not be parsed, but should be treated as a complete token. For instance, in: (this is a preserve region), start would be a left paren -(- and stop would be a right paren -)-. The strip determines whether the designators should be removed from the token. 
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_TCHAR\fR ACE_Tokenizer::Preserve_Entry::start_
.PP
E.g., "(". E.g., ")". Whether the designators should be removed from the token. 
.SS \fBACE_TCHAR\fR ACE_Tokenizer::Preserve_Entry::stop_
.PP
.SS int ACE_Tokenizer::Preserve_Entry::strip_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.