.TH ACE_Write_Guard< ACE_Null_Mutex > 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Write_Guard< ACE_Null_Mutex > \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Synch.h>\fR
.PP
Inherits \fBACE_Guard< ACE_Null_Mutex >\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Write_Guard\fR (\fBACE_Null_Mutex\fR &m)"
.br
.ti -1c
.RI "\fBACE_Write_Guard\fR (\fBACE_Null_Mutex\fR &m, int blocked)"
.br
.ti -1c
.RI "int \fBacquire_write\fR (void)"
.br
.ti -1c
.RI "int \fBacquire\fR (void)"
.br
.ti -1c
.RI "int \fBtryacquire_write\fR (void)"
.br
.ti -1c
.RI "int \fBtryacquire\fR (void)"
.br
.ti -1c
.RI "void \fBdump\fR (void) const"
.br
.in -1c
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS ACE_Write_Guard< \fBACE_Null_Mutex\fR >::ACE_Write_Guard< \fBACE_Null_Mutex\fR > (\fBACE_Null_Mutex\fR & m, int blocked)\fC [inline]\fR
.PP
.SS ACE_Write_Guard< \fBACE_Null_Mutex\fR >::ACE_Write_Guard< \fBACE_Null_Mutex\fR > (\fBACE_Null_Mutex\fR & m)\fC [inline]\fR
.PP
.SS int \fBACE_Write_Guard\fR< \fBACE_Null_Mutex\fR >::acquire (void)\fC [inline]\fR
.PP
Reimplemented from \fBACE_Guard< ACE_Null_Mutex >\fR.
.SS int \fBACE_Write_Guard\fR< \fBACE_Null_Mutex\fR >::acquire_write (void)\fC [inline]\fR
.PP
.SS void \fBACE_Write_Guard\fR< \fBACE_Null_Mutex\fR >::dump (void) const\fC [inline]\fR
.PP
Reimplemented from \fBACE_Guard< ACE_Null_Mutex >\fR.
.SS int \fBACE_Write_Guard\fR< \fBACE_Null_Mutex\fR >::tryacquire (void)\fC [inline]\fR
.PP
Reimplemented from \fBACE_Guard< ACE_Null_Mutex >\fR.
.SS int \fBACE_Write_Guard\fR< \fBACE_Null_Mutex\fR >::tryacquire_write (void)\fC [inline]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.