.TH ACE_Node 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Node \- Implementation element in a Queue, Set, and Stack. 
.SH SYNOPSIS
.br
.PP
\fC#include <Node.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fB~ACE_Node\fR (void)"
.br
.RI "\fIThis isn't necessary, but it keeps some compilers happy.\fR"
.in -1c
.SS Private Methods

.in +1c
.ti -1c
.RI "\fBACE_Node\fR (const T &i, ACE_Node<T> *n)"
.br
.ti -1c
.RI "\fBACE_Node\fR (ACE_Node<T> *n = 0, int = 0)"
.br
.ti -1c
.RI "\fBACE_Node\fR (const ACE_Node<T> &n)"
.br
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "ACE_Node<T>* \fBnext_\fR"
.br
.RI "\fIPointer to next element in the list of s.\fR"
.ti -1c
.RI "T \fBitem_\fR"
.br
.RI "\fICurrent value of the item in this node.\fR"
.in -1c
.SS Friends

.in +1c
.ti -1c
.RI "class \fBACE_Unbounded_Queue< T >\fR"
.br
.ti -1c
.RI "class \fBACE_Unbounded_Queue_Iterator< T >\fR"
.br
.ti -1c
.RI "class \fBACE_Unbounded_Set< T >\fR"
.br
.ti -1c
.RI "class \fBACE_Unbounded_Set_Iterator< T >\fR"
.br
.ti -1c
.RI "class \fBACE_Unbounded_Set_Const_Iterator< T >\fR"
.br
.ti -1c
.RI "class \fBACE_Unbounded_Stack< T >\fR"
.br
.ti -1c
.RI "class \fBACE_Unbounded_Stack_Iterator< T >\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class T>  template class ACE_Node
Implementation element in a Queue, Set, and Stack.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classT> ACE_Node<T>::~ACE_Node<T> (void)
.PP
This isn't necessary, but it keeps some compilers happy.
.PP
.SS template<classT> ACE_Node<T>::ACE_Node<T> (const T & i, ACE_Node< T >* n)\fC [private]\fR
.PP
.SS template<classT> ACE_Node<T>::ACE_Node<T> (ACE_Node< T >* n = 0, int = 0)\fC [private]\fR
.PP
.SS template<classT> ACE_Node<T>::ACE_Node<T> (const ACE_Node< T >& n)\fC [private]\fR
.PP
.SH FRIENDS AND RELATED FUNCTION DOCUMENTATION
.PP 
.SS template<classT> class \fBACE_Unbounded_Queue\fR\fC [friend]\fR
.PP
.SS template<classT> class \fBACE_Unbounded_Queue_Iterator\fR\fC [friend]\fR
.PP
.SS template<classT> class \fBACE_Unbounded_Set\fR\fC [friend]\fR
.PP
.SS template<classT> class \fBACE_Unbounded_Set_Const_Iterator\fR\fC [friend]\fR
.PP
.SS template<classT> class \fBACE_Unbounded_Set_Iterator\fR\fC [friend]\fR
.PP
.SS template<classT> class \fBACE_Unbounded_Stack\fR\fC [friend]\fR
.PP
.SS template<classT> class \fBACE_Unbounded_Stack_Iterator\fR\fC [friend]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS template<classT> T ACE_Node<T>::item_\fC [private]\fR
.PP
Current value of the item in this node.
.PP
.SS template<classT> ACE_Node< T >* ACE_Node<T>::next_\fC [private]\fR
.PP
Pointer to next element in the list of s.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.