.TH ACE_Active_Map_Manager_Key::key_data 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Active_Map_Manager_Key::key_data \- Data for the Active Object Map Key. 
.SH SYNOPSIS
.br
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "ACE_UINT32 \fBslot_index_\fR"
.br
.RI "\fISlot index in the active map.\fR"
.ti -1c
.RI "ACE_UINT32 \fBslot_generation_\fR"
.br
.RI "\fISlot generation number of <slot_index_> slot in the active map.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Data for the Active Object Map Key.
.PP
.PP
 This separate structure makes it easier to manage copying the index and the generation to and from the user buffer. 
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS ACE_UINT32 ACE_Active_Map_Manager_Key::key_data::slot_generation_
.PP
Slot generation number of <slot_index_> slot in the active map.
.PP
.SS ACE_UINT32 ACE_Active_Map_Manager_Key::key_data::slot_index_
.PP
Slot index in the active map.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.