.TH ACE_Dumpable_Adapter 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Dumpable_Adapter \- This class inherits the interface of the abstract \fBACE_Dumpable\fR class and is instantiated with the implementation of the concrete component class <class Concrete>. 
.SH SYNOPSIS
.br
.PP
\fC#include <Dump_T.h>\fR
.PP
Inherits \fBACE_Dumpable\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Dumpable_Adapter\fR (const Concrete *t)"
.br
.ti -1c
.RI "\fB~ACE_Dumpable_Adapter\fR (void)"
.br
.ti -1c
.RI "virtual void \fBdump\fR (void) const"
.br
.RI "\fIConcrete dump method (simply delegates to the <dump> method of <class Concrete>).\fR"
.ti -1c
.RI "Concrete* \fBoperator->\fR () const"
.br
.RI "\fIDelegate to methods in the Concrete class.\fR"
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "const Concrete* \fBthis_\fR"
.br
.RI "\fIPointer to <this> of <class Concrete>.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class Concrete>  template class ACE_Dumpable_Adapter
This class inherits the interface of the abstract \fBACE_Dumpable\fR class and is instantiated with the implementation of the concrete component class <class Concrete>.
.PP
.PP
 This design is similar to the Adapter and Decorator patterns from the ``Gang of Four'' book. Note that <class Concrete> need not inherit from a common class since \fBACE_Dumpable\fR provides the uniform virtual interface! 
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classConcrete> ACE_Dumpable_Adapter<Concrete>::ACE_Dumpable_Adapter<Concrete> (const Concrete * t)
.PP
.SS template<classConcrete> ACE_Dumpable_Adapter<Concrete>::~ACE_Dumpable_Adapter<Concrete> (void)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classConcrete> void ACE_Dumpable_Adapter<Concrete>::dump (void) const\fC [virtual]\fR
.PP
Concrete dump method (simply delegates to the <dump> method of <class Concrete>).
.PP
Reimplemented from \fBACE_Dumpable\fR.
.SS template<classConcrete> Concrete * ACE_Dumpable_Adapter<Concrete>::operator-> (void) const
.PP
Delegate to methods in the Concrete class.
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS template<classConcrete> const Concrete * ACE_Dumpable_Adapter<Concrete>::this_\fC [private]\fR
.PP
Pointer to <this> of <class Concrete>.
.PP
Reimplemented from \fBACE_Dumpable\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.