.TH ACE_OS_Thread_Descriptor 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_OS_Thread_Descriptor \- Parent class of all \fBACE_Thread_Descriptor\fR classes. = Container for \fBACE_Thread_Descriptor\fR members that are used in \fBACE_OS\fR. 
.SH SYNOPSIS
.br
.PP
\fC#include <Base_Thread_Adapter.h>\fR
.PP
Inherited by \fBACE_Thread_Descriptor_Base\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "long \fBflags\fR (void) const"
.br
.RI "\fIGet the thread creation flags.\fR"
.in -1c
.SS Protected Methods

.in +1c
.ti -1c
.RI "\fBACE_OS_Thread_Descriptor\fR (long flags = 0)"
.br
.RI "\fIFor use by \fBACE_Thread_Descriptor\fR.\fR"
.in -1c
.SS Protected Attributes

.in +1c
.ti -1c
.RI "long \fBflags_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Parent class of all \fBACE_Thread_Descriptor\fR classes. = Container for \fBACE_Thread_Descriptor\fR members that are used in \fBACE_OS\fR.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_OS_Thread_Descriptor::ACE_OS_Thread_Descriptor (long flags = 0)\fC [protected]\fR
.PP
For use by \fBACE_Thread_Descriptor\fR.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS long ACE_OS_Thread_Descriptor::flags (void) const
.PP
Get the thread creation flags.
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS long ACE_OS_Thread_Descriptor::flags_\fC [protected]\fR
.PP
Keeps track of whether this thread was created "detached" or not. If a thread is *not* created detached then if someone calls , we need to join with that thread (and close down the handle). 

.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.