.TH ACE_Asynch_Write_Dgram::brief 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Asynch_Write_Dgram::brief \- 
.SH SYNOPSIS
.br
.PP
.SH DETAILED DESCRIPTION
.PP 
that class which will be passed back to the <handler> when the asynchronous write completes. This class forwards all the methods to the implementation class.
.PP
This class has all the information necessary for the <handler> to uniquiely identify the completion of the asynchronous write. 
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.