.TH ACE_DNode 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_DNode \- Implementation element in a bilinked list. 
.SH SYNOPSIS
.br
.PP
\fC#include <Containers_T.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fB~ACE_DNode\fR (void)"
.br
.RI "\fIThis isn't necessary, but it keeps some compilers happy.\fR"
.in -1c
.SS Private Methods

.in +1c
.ti -1c
.RI "\fBACE_DNode\fR (const T &i, ACE_DNode<T> *n = 0, ACE_DNode<T> *p = 0)"
.br
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "ACE_DNode<T>* \fBnext_\fR"
.br
.RI "\fIPointer to next element in the list of s.\fR"
.ti -1c
.RI "ACE_DNode<T>* \fBprev_\fR"
.br
.RI "\fIPointer to previous element in the list of s.\fR"
.ti -1c
.RI "T \fBitem_\fR"
.br
.RI "\fICurrent value of the item in this node.\fR"
.in -1c
.SS Friends

.in +1c
.ti -1c
.RI "class \fBACE_Ordered_MultiSet< T >\fR"
.br
.ti -1c
.RI "class \fBACE_Ordered_MultiSet_Iterator< T >\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class T>  template class ACE_DNode
Implementation element in a bilinked list.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classT> ACE_DNode<T>::~ACE_DNode<T> (void)
.PP
This isn't necessary, but it keeps some compilers happy.
.PP
.SS template<classT> ACE_DNode<T>::ACE_DNode<T> (const T & i, ACE_DNode< T >* n = 0, ACE_DNode< T >* p = 0)\fC [private]\fR
.PP
.SH FRIENDS AND RELATED FUNCTION DOCUMENTATION
.PP 
.SS template<classT> class \fBACE_Ordered_MultiSet\fR\fC [friend]\fR
.PP
.SS template<classT> class \fBACE_Ordered_MultiSet_Iterator\fR\fC [friend]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS template<classT> T ACE_DNode<T>::item_\fC [private]\fR
.PP
Current value of the item in this node.
.PP
.SS template<classT> ACE_DNode< T >* ACE_DNode<T>::next_\fC [private]\fR
.PP
Pointer to next element in the list of s.
.PP
.SS template<classT> ACE_DNode< T >* ACE_DNode<T>::prev_\fC [private]\fR
.PP
Pointer to previous element in the list of s.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.