.TH ACE_Obstack 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Obstack \- Define a simple "mark and release" memory allocation utility. 
.SH SYNOPSIS
.br
.PP
\fC#include <Obstack_T.h>\fR
.PP
.SH DETAILED DESCRIPTION
.PP 
Define a simple "mark and release" memory allocation utility.
.PP
.PP
 The implementation is similar to the GNU obstack utility, which is used extensively in the GCC compiler. 
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.