.TH ACE_Noop_Key_Generator 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Noop_Key_Generator \- Defines a noop key generator. 
.SH SYNOPSIS
.br
.PP
\fC#include <Map_T.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "int \fBoperator()\fR (T &)"
.br
.RI "\fIFunctor method: generates a new key.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class T>  template class ACE_Noop_Key_Generator
Defines a noop key generator.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classT> int ACE_Noop_Key_Generator<T>::operator() (T &)
.PP
Functor method: generates a new key.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.