.TH ACE_NOOP_Creation_Strategy 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_NOOP_Creation_Strategy \- Implements a no-op creation strategy in order to defer decisions regarding creation to some later point in time, such as in connect or accept strategy. 
.SH SYNOPSIS
.br
.PP
\fC#include <Strategies_T.h>\fR
.PP
Inherits \fBACE_Creation_Strategy< SVC_HANDLER >\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "virtual int \fBmake_svc_handler\fR (SVC_HANDLER *&)"
.br
.RI "\fIThis is a no-op.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class SVC_HANDLER>  template class ACE_NOOP_Creation_Strategy
Implements a no-op creation strategy in order to defer decisions regarding creation to some later point in time, such as in connect or accept strategy.
.PP
.PP
 An example of the use of this is in the , which only returns a single connection for a given endpoint. 
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classSVC_HANDLER> int ACE_NOOP_Creation_Strategy<SVC_HANDLER>::make_svc_handler (SVC_HANDLER *& sh)\fC [virtual]\fR
.PP
This is a no-op.
.PP
Reimplemented from \fBACE_Creation_Strategy\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.