.TH ACE_Bounded_Set::Search_Structure 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Bounded_Set::Search_Structure \- 
.SH SYNOPSIS
.br
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "T \fBitem_\fR"
.br
.ti -1c
.RI "int \fBis_free_\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int ACE_Bounded_Set::Search_Structure::is_free_
.PP
.SS T ACE_Bounded_Set::Search_Structure::item_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.