.TH ACE_Registry::Name_Component 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Registry::Name_Component \- International string. 
.SH SYNOPSIS
.br
.PP
\fC#include <Registry.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "int \fBoperator==\fR (const Name_Component &rhs) const"
.br
.ti -1c
.RI "int \fBoperator!=\fR (const Name_Component &rhs) const"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "ACE_TString \fBid_\fR"
.br
.ti -1c
.RI "ACE_TString \fBkind_\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
International string.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS int ACE_Registry::Name_Component::operator!= (const Name_Component & rhs) const
.PP
.SS int ACE_Registry::Name_Component::operator== (const Name_Component & rhs) const
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS ACE_TString ACE_Registry::Name_Component::id_
.PP
.SS ACE_TString ACE_Registry::Name_Component::kind_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.