.TH ACE_FIFO_Send 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_FIFO_Send \- Sender side for the bytestream C++ wrapper for UNIX FIFOs. 
.SH SYNOPSIS
.br
.PP
\fC#include <FIFO_Send.h>\fR
.PP
Inherits \fBACE_FIFO\fR.
.PP
Inherited by \fBACE_FIFO_Send_Msg\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_FIFO_Send\fR (void)"
.br
.RI "\fIDefault constructor.\fR"
.ti -1c
.RI "\fBACE_FIFO_Send\fR (const \fBACE_TCHAR\fR *rendezvous, int flags = O_WRONLY, int perms = ACE_DEFAULT_FILE_PERMS, LPSECURITY_ATTRIBUTES sa = 0)"
.br
.RI "\fIOpen up a bytestream named pipe for writing.\fR"
.ti -1c
.RI "int \fBopen\fR (const \fBACE_TCHAR\fR *rendezvous, int flags = O_WRONLY, int perms = ACE_DEFAULT_FILE_PERMS, LPSECURITY_ATTRIBUTES sa = 0)"
.br
.RI "\fIOpen up a bytestream named pipe for writing.\fR"
.ti -1c
.RI "\fBssize_t\fR \fBsend\fR (const void *buf, size_t len)"
.br
.RI "\fISend <buf> of up to <len> bytes.\fR"
.ti -1c
.RI "\fBssize_t\fR \fBsend_n\fR (const void *buf, size_t len)"
.br
.RI "\fISend <buf> of exactly <len> bytes (block until done).\fR"
.ti -1c
.RI "void \fBdump\fR (void) const"
.br
.RI "\fIDump the state of an object.\fR"
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBACE_ALLOC_HOOK_DECLARE\fR"
.br
.RI "\fIDeclare the dynamic allocation hooks.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Sender side for the bytestream C++ wrapper for UNIX FIFOs.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_FIFO_Send::ACE_FIFO_Send (void)
.PP
Default constructor.
.PP
.SS ACE_FIFO_Send::ACE_FIFO_Send (const \fBACE_TCHAR\fR * rendezvous, int flags = O_WRONLY, int perms = ACE_DEFAULT_FILE_PERMS, LPSECURITY_ATTRIBUTES sa = 0)
.PP
Open up a bytestream named pipe for writing.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void ACE_FIFO_Send::dump (void) const
.PP
Dump the state of an object.
.PP
Reimplemented from \fBACE_FIFO\fR.
.PP
Reimplemented in \fBACE_FIFO_Send_Msg\fR.
.SS int ACE_FIFO_Send::open (const \fBACE_TCHAR\fR * rendezvous, int flags = O_WRONLY, int perms = ACE_DEFAULT_FILE_PERMS, LPSECURITY_ATTRIBUTES sa = 0)
.PP
Open up a bytestream named pipe for writing.
.PP
Reimplemented from \fBACE_FIFO\fR.
.PP
Reimplemented in \fBACE_FIFO_Send_Msg\fR.
.SS \fBssize_t\fR ACE_FIFO_Send::send (const void * buf, size_t len)
.PP
Send <buf> of up to <len> bytes.
.PP
Reimplemented in \fBACE_FIFO_Send_Msg\fR.
.SS \fBssize_t\fR ACE_FIFO_Send::send_n (const void * buf, size_t len)
.PP
Send <buf> of exactly <len> bytes (block until done).
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS ACE_FIFO_Send::ACE_ALLOC_HOOK_DECLARE
.PP
Declare the dynamic allocation hooks.
.PP
Reimplemented from \fBACE_FIFO\fR.
.PP
Reimplemented in \fBACE_FIFO_Send_Msg\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.