.TH ACE_Thread_ID 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Thread_ID \- Defines a platform-independent thread ID. 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBACE_Thread_ID\fR (\fBACE_thread_t\fR, \fBACE_hthread_t\fR)"
.br
.ti -1c
.RI "\fBACE_Thread_ID\fR (const ACE_Thread_ID &id)"
.br
.ti -1c
.RI "\fBACE_thread_t\fR \fBid\fR (void)"
.br
.ti -1c
.RI "void \fBid\fR (\fBACE_thread_t\fR)"
.br
.ti -1c
.RI "\fBACE_hthread_t\fR \fBhandle\fR (void)"
.br
.ti -1c
.RI "void \fBhandle\fR (\fBACE_hthread_t\fR)"
.br
.ti -1c
.RI "int \fBoperator==\fR (const ACE_Thread_ID &) const"
.br
.ti -1c
.RI "int \fBoperator!=\fR (const ACE_Thread_ID &) const"
.br
.in -1c
.SS Private Attributes

.in +1c
.ti -1c
.RI "\fBACE_thread_t\fR \fBthread_id_\fR"
.br
.RI "\fIIdentify the thread.\fR"
.ti -1c
.RI "\fBACE_hthread_t\fR \fBthread_handle_\fR"
.br
.RI "\fIHandle to the thread (typically used to "wait" on Win32).\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Defines a platform-independent thread ID.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_Thread_ID::ACE_Thread_ID (\fBACE_thread_t\fR, \fBACE_hthread_t\fR)
.PP
.SS ACE_Thread_ID::ACE_Thread_ID (const ACE_Thread_ID & id)
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void ACE_Thread_ID::handle (\fBACE_hthread_t\fR)
.PP
.SS \fBACE_hthread_t\fR ACE_Thread_ID::handle (void)
.PP
.SS void ACE_Thread_ID::id (\fBACE_thread_t\fR)
.PP
.SS \fBACE_thread_t\fR ACE_Thread_ID::id (void)
.PP
.SS int ACE_Thread_ID::operator!= (const ACE_Thread_ID &) const
.PP
.SS int ACE_Thread_ID::operator== (const ACE_Thread_ID &) const
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_hthread_t\fR ACE_Thread_ID::thread_handle_\fC [private]\fR
.PP
Handle to the thread (typically used to "wait" on Win32).
.PP
.SS \fBACE_thread_t\fR ACE_Thread_ID::thread_id_\fC [private]\fR
.PP
Identify the thread.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.