.TH ACE_Local_Memory_Pool_Options 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_Local_Memory_Pool_Options \- Helper class for Local Memory Pool constructor options. 
.SH SYNOPSIS
.br
.PP
\fC#include <Memory_Pool.h>\fR
.PP
.SH DETAILED DESCRIPTION
.PP 
Helper class for Local Memory Pool constructor options.
.PP
.PP
 This should be a nested class, but that breaks too many compilers. 
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.