.TH ACE_OutputCDR::from_char 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_OutputCDR::from_char \- 
.SH SYNOPSIS
.br
.PP
\fC#include <CDR_Stream.h>\fR
.PP
.SS Helper classes

.in +1c
.ti -1c
.RI "\fBfrom_char\fR (\fBACE_CDR::Char\fR c)"
.br
.ti -1c
.RI "\fBACE_CDR::Char\fR \fBval_\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ACE_OutputCDR::from_char::from_char (\fBACE_CDR::Char\fR c)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBACE_CDR::Char\fR ACE_OutputCDR::from_char::val_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.