.TH ACE_OS::ace_flock_t 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACE_OS::ace_flock_t \- OS file locking structure. 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "void \fBdump\fR (void) const"
.br
.RI "\fIDump state of the object.\fR"
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBACE_OVERLAPPED\fR \fBoverlapped_\fR"
.br
.ti -1c
.RI "const \fBACE_TCHAR\fR* \fBlockname_\fR"
.br
.RI "\fIName of this filelock.\fR"
.ti -1c
.RI "ACE_HANDLE \fBhandle_\fR"
.br
.RI "\fIHandle to the underlying file.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
OS file locking structure.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void ACE_OS::ace_flock_t::dump (void) const
.PP
Dump state of the object.
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS ACE_HANDLE ACE_OS::ace_flock_t::handle_
.PP
Handle to the underlying file.
.PP
.SS const \fBACE_TCHAR\fR * ACE_OS::ace_flock_t::lockname_
.PP
Name of this filelock.
.PP
.SS \fBACE_OVERLAPPED\fR ACE_OS::ace_flock_t::overlapped_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.