.TH Activation_Queue_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Activation_Queue_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Synch_T.h"\fR
.br
\fC#include "ace/Message_Queue.h"\fR
.br
\fC#include "ace/Method_Request.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Activation_Queue\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_Activation_List\fR  \fBACE_Activation_Queue\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBActivation_Queue.h\fR,v 4.18 2001/09/27 22:35:47 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Andres Kruse  and ,  Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_Activation_List  \fBACE_Activation_Queue\fR
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.