.TH Array_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Array_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Containers_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBArray.h\fR,v 4.15 2000/11/01 22:16:18 coryan Exp
.PP
NOTE: this file has been deprecated and will soon go away. You should directly include "\fBContainers_T.h\fR" instead.
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.