.TH Asynch_IO_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asynch_IO_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Asynch_Accept\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Operation\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Read_Dgram\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Read_File\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Read_Stream\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Result\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Transmit_File\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Write_Dgram\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Write_File\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Write_Stream\fR"
.br
.ti -1c
.RI "class \fBACE_Handler\fR"
.br
.ti -1c
.RI "class \fBACE_Service_Handler\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Transmit_File::Header_And_Trailer\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Write_Dgram::Result\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Read_Dgram::Result\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Transmit_File::Result\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Accept::Result\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Write_File::Result\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Read_File::Result\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Write_Stream::Result\fR"
.br
.ti -1c
.RI "class \fBACE_Asynch_Read_Stream::Result\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBAsynch_IO.h\fR,v 4.53 2001/08/08 14:24:17 schmidt Exp
.PP
This works on Win32 (if defined (ACE_WIN32) && !defined (ACE_HAS_WINCE)) platforms and on POSIX4 platforms with  routines (if defined (ACE_HAS_AIO_CALLS))
.PP
On Win32 platforms, the implementation of  and  are only supported if ACE_HAS_WINSOCK2 is defined or you are on WinNT 4.0 or higher.
.PP
\fBAuthor(s): \fR
.in +1c
 Irfan Pyarali <irfan@cs.wustl.edu> ,  Tim Harrison <harrison@cs.wustl.edu> ,  Alexander Babu Arulanthu  ,  Roger Tragin <r.tragin@computer.org>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.