.TH ATM_Connector_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ATM_Connector_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ATM_Stream.h"\fR
.br
\fC#include "ace/ATM_Params.h"\fR
.br
\fC#include "ace/ATM_QoS.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBATM_Connector.h\fR,v 4.10 2001/03/07 12:32:15 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Joe Hoffert <joeh@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.