.TH ATM_Addr_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ATM_Addr_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/Addr.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_ATM_Addr\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef int \fBATM_Addr\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBATM_Addr.h\fR,v 4.12 2000/11/01 22:16:18 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Joe Hoffert <joeh@cs.wustl.edu>
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef int ATM_Addr
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.