.TH ATM_Acceptor_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ATM_Acceptor_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Time_Value.h"\fR
.br
\fC#include "ace/ATM_Stream.h"\fR
.br
\fC#include "ace/ATM_Params.h"\fR
.br
\fC#include "ace/ATM_QoS.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBATM_Acceptor.h\fR,v 4.8 2000/11/01 22:16:18 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Joe Hoffert
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.