.TH Auto_Ptr_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Auto_Ptr_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Auto_Array_Ptr\fR"
.br
.ti -1c
.RI "class \fBACE_Auto_Basic_Array_Ptr\fR"
.br
.ti -1c
.RI "class \fBACE_Auto_Basic_Ptr\fR"
.br
.ti -1c
.RI "class \fBauto_ptr\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_AUTO_PTR_RESET\fR(X,Y,Z) "
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBAuto_Ptr.h\fR,v 4.29 2000/12/08 16:48:56 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt <schmidt@uci.edu> ,  Irfan Pyarali <irfan@cs.wustl.edu> ,  Jack Reeves <jack@fx.com> ,  Dr. Harald M. Mueller <mueller@garwein.hai.siemens.co.at>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_AUTO_PTR_RESET(X, Y, Z)
.PP
\fBInitializer:\fR
.PP
.nf
\
      do { \
         X.reset (Y); \
      } while (0)
.fi
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.