.TH auto_ptr 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auto_ptr \- Implements the draft C++ standard auto_ptr abstraction. 
.SH SYNOPSIS
.br
.PP
\fC#include <Auto_Ptr.h>\fR
.PP
Inherits \fBACE_Auto_Basic_Ptr< X >\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "ACE_EXPLICIT \fBauto_ptr\fR (X *p = 0)"
.br
.ti -1c
.RI "X* \fBoperator->\fR () const"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class X>  template class auto_ptr
Implements the draft C++ standard auto_ptr abstraction.
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classX> ACE_EXPLICIT auto_ptr<X>::auto_ptr<X> (X * p = 0)\fC [inline]\fR
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classX> X* auto_ptr<X>::operator-> () const
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.