.TH Based_Pointer_Repository_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Based_Pointer_Repository_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Singleton.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Based_Pointer_Repository\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Singleton\fR<\fBACE_Based_Pointer_Repository\fR, ACE_SYNCH_RW_MUTEX> \fBACE_BASED_POINTER_REPOSITORY\fR"
.br
.RI "\fIProvide a Singleton access point to the based pointer repository.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBBased_Pointer_Repository.h\fR,v 4.7 2000/11/01 22:16:21 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Dietrich Quehl <Dietrich.Quehl@med.siemens.de> ,  Douglas C. Schmidt <schmidt@.cs.wustl.edu>
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Singleton\fR<\fBACE_Based_Pointer_Repository\fR, ACE_SYNCH_RW_MUTEX> ACE_BASED_POINTER_REPOSITORY
.PP
Provide a Singleton access point to the based pointer repository.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.