.TH Based_Pointer_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Based_Pointer_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Based_Pointer\fR"
.br
.ti -1c
.RI "class \fBACE_Based_Pointer_Basic\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBBased_Pointer_T.h\fR,v 4.14 2001/04/23 14:09:42 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Dietrich Quehl <Dietrich.Quehl@med.siemens.de> ,  Douglas C. Schmidt <schmidt@.cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.