.TH Bound_Ptr_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bound_Ptr_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Auto_Ptr.h"\fR
.br
\fC#include "ace/Bound_Ptr.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Bound_Ptr_Counter\fR"
.br
.ti -1c
.RI "class \fBACE_Strong_Bound_Ptr\fR"
.br
.ti -1c
.RI "class \fBACE_Weak_Bound_Ptr\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBBound_Ptr.h\fR,v 4.1 2001/08/29 14:01:06 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Christopher Kohlhoff <chris@kohlhoff.com>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.