.TH Caching_Strategies_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Caching_Strategies_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Caching_Utility_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Caching_Strategy\fR"
.br
.ti -1c
.RI "class \fBACE_Caching_Strategy_Adapter\fR"
.br
.ti -1c
.RI "class \fBACE_FIFO_Caching_Strategy\fR"
.br
.ti -1c
.RI "class \fBACE_LFU_Caching_Strategy\fR"
.br
.ti -1c
.RI "class \fBACE_LRU_Caching_Strategy\fR"
.br
.ti -1c
.RI "class \fBACE_Null_Caching_Strategy\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_Caching_Strategy\fR  ACS"
.br
.ti -1c
.RI "#define \fBACE_Caching_Strategy_Adapter\fR  ACSA"
.br
.ti -1c
.RI "#define \fBACE_LRU_Caching_Strategy\fR  ALRU"
.br
.ti -1c
.RI "#define \fBACE_LFU_Caching_Strategy\fR  ALFU"
.br
.ti -1c
.RI "#define \fBACE_FIFO_Caching_Strategy\fR  AFIFO"
.br
.ti -1c
.RI "#define \fBACE_Null_Caching_Strategy\fR  ANULL"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBCaching_Strategies_T.h\fR,v 4.16 2001/09/27 22:35:48 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Kirthika Parameswaran <kirthika@cs.wustl.edu>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_Caching_Strategy  ACS
.PP
.SS #define ACE_Caching_Strategy_Adapter  ACSA
.PP
.SS #define ACE_FIFO_Caching_Strategy  AFIFO
.PP
.SS #define ACE_LFU_Caching_Strategy  ALFU
.PP
.SS #define ACE_LRU_Caching_Strategy  ALRU
.PP
.SS #define ACE_Null_Caching_Strategy  ANULL
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.