.TH Caching_Utility_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Caching_Utility_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Cleanup_Strategies_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Handler_Caching_Utility\fR"
.br
.ti -1c
.RI "class \fBACE_Null_Caching_Utility\fR"
.br
.ti -1c
.RI "class \fBACE_Pair_Caching_Utility\fR"
.br
.ti -1c
.RI "class \fBACE_Recyclable_Handler_Caching_Utility\fR"
.br
.ti -1c
.RI "class \fBACE_Refcounted_Recyclable_Handler_Caching_Utility\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_LACKS_PRAGMA_ONCE\fR"
.br
.ti -1c
.RI "#define \fBACE_Pair_Caching_Utility\fR  APUTIL"
.br
.ti -1c
.RI "#define \fBACE_Recyclable_Handler_Caching_Utility\fR  ARHUTIL"
.br
.ti -1c
.RI "#define \fBACE_Refcounted_Recyclable_Handler_Caching_Utility\fR  ARRHUTIL"
.br
.ti -1c
.RI "#define \fBACE_Null_Caching_Utility\fR  ANUTIL"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBCaching_Utility_T.h\fR,v 4.11 2001/01/12 11:31:58 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Kirthika Parameswaran <kirthika@cs.wustl.edu>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_LACKS_PRAGMA_ONCE
.PP
.SS #define ACE_Null_Caching_Utility  ANUTIL
.PP
.SS #define ACE_Pair_Caching_Utility  APUTIL
.PP
.SS #define ACE_Recyclable_Handler_Caching_Utility  ARHUTIL
.PP
.SS #define ACE_Refcounted_Recyclable_Handler_Caching_Utility  ARRHUTIL
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.