.TH Cache_Map_Manager_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cache_Map_Manager_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Pair_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Cache_Map_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_Cache_Map_Manager\fR"
.br
.ti -1c
.RI "class \fBACE_Cache_Map_Reverse_Iterator\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_LACKS_PRAGMA_ONCE\fR"
.br
.ti -1c
.RI "#define \fBACE_Cache_Map_Iterator\fR  ACMI"
.br
.ti -1c
.RI "#define \fBACE_Cache_Map_Reverse_Iterator\fR  ACMRI"
.br
.ti -1c
.RI "#define \fBACE_T1\fR  class KEY, class VALUE, class MAP, class ITERATOR_IMPL, class REVERSE_ITERATOR_IMPL, class CACHING_STRATEGY, class ATTRIBUTES"
.br
.ti -1c
.RI "#define \fBACE_T2\fR  KEY, VALUE, MAP, ITERATOR_IMPL, REVERSE_ITERATOR_IMPL, CACHING_STRATEGY, ATTRIBUTES"
.br
.ti -1c
.RI "#define \fBACE_Cache_Map_Manager\fR  ACMM"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBCache_Map_Manager_T.h\fR,v 4.23 2000/11/12 20:30:31 brunsch Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Kirthika Parameswaran <kirthika@cs.wustl.edu>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_Cache_Map_Iterator  ACMI
.PP
.SS #define ACE_Cache_Map_Manager  ACMM
.PP
.SS #define ACE_Cache_Map_Reverse_Iterator  ACMRI
.PP
.SS #define ACE_LACKS_PRAGMA_ONCE
.PP
.SS #define ACE_T1  class KEY, class VALUE, class MAP, class ITERATOR_IMPL, class REVERSE_ITERATOR_IMPL, class CACHING_STRATEGY, class ATTRIBUTES
.PP
.SS #define ACE_T2  KEY, VALUE, MAP, ITERATOR_IMPL, REVERSE_ITERATOR_IMPL, CACHING_STRATEGY, ATTRIBUTES
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.