.TH cancel_state 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cancel_state \- 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBcancelstate\fR"
.br
.ti -1c
.RI "int \fBcanceltype\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int cancel_state::cancelstate
.PP
.SS int cancel_state::canceltype
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.