.TH Configuration_Import_Export_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration_Import_Export_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Configuration.h"\fR
.br
\fC#include "ace/SString.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Config_ImpExp_Base\fR"
.br
.ti -1c
.RI "class \fBACE_Ini_ImpExp\fR"
.br
.ti -1c
.RI "class \fBACE_Registry_ImpExp\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBConfiguration_Import_Export.h\fR,v 4.5 2001/08/22 22:13:00 shuston Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Jerry D. Odenwelder Jr. <jerry.o@mindspring.com> Chris Hafey <chris@stentorsoft.com>
.PP
Classes defined in this file provide the ability to import and export  \fBACE\fR Configuration objects to/from disk files. The base class  \fBACE_Config_ImpExp_Base\fR provides the common functionality and the derived  classes implement the import/export functionality for the specific format.
.PP
.TP
* - * - 
.PP
\fB\fBTodo: \fR\fR
.in +1c
 Add locking for thread safety. Provide ability to read file in one format and write in another. See todo's in each class 
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.