.TH Containers_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Containers_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/Containers.h"\fR
.br
\fC#include "ace/Node.h"\fR
.br
\fC#include "ace/Array_Base.h"\fR
.br
\fC#include "ace/Unbounded_Set.h"\fR
.br
\fC#include "ace/Unbounded_Queue.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Array\fR"
.br
.ti -1c
.RI "class \fBACE_Bounded_Set\fR"
.br
.ti -1c
.RI "class \fBACE_Bounded_Set_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_Bounded_Stack\fR"
.br
.ti -1c
.RI "class \fBACE_DLList\fR"
.br
.ti -1c
.RI "class \fBACE_DLList_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_DLList_Reverse_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_DNode\fR"
.br
.ti -1c
.RI "class \fBACE_Double_Linked_List\fR"
.br
.ti -1c
.RI "class \fBACE_Double_Linked_List_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_Double_Linked_List_Iterator_Base\fR"
.br
.ti -1c
.RI "class \fBACE_Double_Linked_List_Reverse_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_Fixed_Set\fR"
.br
.ti -1c
.RI "class \fBACE_Fixed_Set_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_Fixed_Stack\fR"
.br
.ti -1c
.RI "class \fBACE_Ordered_MultiSet\fR"
.br
.ti -1c
.RI "class \fBACE_Ordered_MultiSet_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_Unbounded_Stack\fR"
.br
.ti -1c
.RI "class \fBACE_Unbounded_Stack_Iterator\fR"
.br
.ti -1c
.RI "struct \fBACE_Bounded_Set::Search_Structure\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Double_Linked_List\fR<\fBACE_DLList_Node\fR> \fBACE_DLList_Base\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBContainers_T.h\fR,v 1.50 2001/07/24 16:50:02 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Double_Linked_List\fR<\fBACE_DLList_Node\fR> ACE_DLList_Base
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.