.TH CORBA_Handler_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORBA_Handler_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Service_Config.h"\fR
.br
\fC#include "ace/Pipe.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBCORBA_Handler.h\fR,v 4.23 2000/11/01 22:16:21 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt (schmidt@cs.wustl.edu) ,  Irfan Pyarali (irfan@cs.wustl.edu)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.