.TH Date_Time_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Date_Time_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/Date_Time.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Date_Time\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBDate_Time.h\fR,v 4.11 2000/12/16 19:57:28 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Tim Harrison (harrison@cs.wustl.edu) (and he's darn proud of this ;-))
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.