.TH DEV_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DEV_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/IO_SAP.h"\fR
.br
\fC#include "ace/DEV_Addr.h"\fR
.br
\fC#include "ace/DEV.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_DEV\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_DEV_CONNECTOR\fR  \fBACE_DEV_Connector\fR, \fBACE_DEV_Addr\fR"
.br
.ti -1c
.RI "#define \fBACE_DEV_STREAM\fR  ACE_DEV_Stream, \fBACE_DEV_Addr\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBDEV.h\fR,v 4.10 2000/11/01 22:16:22 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Gerhard Lenzer
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_DEV_CONNECTOR  \fBACE_DEV_Connector\fR, \fBACE_DEV_Addr\fR
.PP
.SS #define ACE_DEV_STREAM  ACE_DEV_Stream, \fBACE_DEV_Addr\fR
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.