.TH DEV_Connector_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DEV_Connector_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/DEV_IO.h"\fR
.br
\fC#include "ace/Log_Msg.h"\fR
.br
\fC#include "ace/DEV_Connector.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_DEV_Connector\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBDEV_Connector.h\fR,v 4.15 2001/03/07 12:32:16 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Gerhard Lenzer and Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.