.TH Dirent_Selector_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dirent_Selector_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Dirent_Selector\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBDirent_Selector.h\fR,v 4.3 2001/07/09 23:48:07 othman Exp
.PP
Define a portable C++ interface to the  method.
.PP
\fBAuthor(s): \fR
.in +1c
 Rich Newman <RNewman@directv.com>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.