.TH DLL_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DLL_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_DLL\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBDLL.h\fR,v 4.21 2000/11/01 22:16:22 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Kirthika Parameswaran <kirthika@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.