.TH Dump_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dump_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Dump.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Dumpable_Adapter\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_REGISTER_OBJECT\fR(CLASS) "
.br
.ti -1c
.RI "#define \fBACE_REMOVE_OBJECT\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBDump_T.h\fR,v 4.12 2000/11/12 20:30:31 brunsch Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_REGISTER_OBJECT(CLASS)
.PP
\fBInitializer:\fR
.PP
.nf
\
        ACE_ODB::instance ()->register_object \
          (new ACE_Dumpable_Adapter<CLASS> (this));
.fi
.SS #define ACE_REMOVE_OBJECT
.PP
\fBInitializer:\fR
.PP
.nf
\
        ACE_ODB::instance ()->remove_object    \
          ((void *) this);
.fi
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.