.TH Dynamic_Service_Base_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dynamic_Service_Base_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Dynamic_Service_Base\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBDynamic_Service_Base.h\fR,v 4.2 2001/10/01 00:44:55 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Prashant Jain <pjain@cs.wustl.edu> ,  Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.