.TH Event_Handler_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Event_Handler_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Event_Handler\fR"
.br
.ti -1c
.RI "class \fBACE_Notification_Buffer\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef u_long \fBACE_Reactor_Mask\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBEvent_Handler.h\fR,v 4.41 2001/09/22 22:20:13 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef u_long ACE_Reactor_Mask
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.