.TH Filecache_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Filecache_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Mem_Map.h"\fR
.br
\fC#include "ace/Synch_T.h"\fR
.br
\fC#include "ace/Hash_Map_Manager.h"\fR
.br
\fC#include "ace/SString.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Filecache\fR"
.br
.ti -1c
.RI "class \fBACE_Filecache_Handle\fR"
.br
.ti -1c
.RI "class \fBACE_Filecache_Object\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Hash_Map_Entry\fR<ACE_TString, \fBACE_Filecache_Object\fR *> \fBACE_Filecache_Hash_Entry\fR"
.br
.ti -1c
.RI "typedef \fBACE_Hash_Map_Manager\fR<ACE_TString, \fBACE_Filecache_Object\fR *, \fBACE_Null_Mutex\fR> \fBACE_Filecache_Hash\fR"
.br
.in -1c
.SS Enumerations

.in +1c
.ti -1c
.RI "enum \fBACE_Filecache_Flag\fR { \fBACE_NOMAP\fR = 0, \fBACE_MAPIT\fR = 1 }"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBFilecache.h\fR,v 4.37 2001/01/24 22:39:08 nanbor Exp
.PP
\fBAuthor(s): \fR
.in +1c
 James Hu
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Hash_Map_Manager\fR<ACE_TString, \fBACE_Filecache_Object\fR *, \fBACE_Null_Mutex\fR> ACE_Filecache_Hash
.PP
.SS typedef \fBACE_Hash_Map_Entry\fR<ACE_TString, \fBACE_Filecache_Object\fR *> ACE_Filecache_Hash_Entry
.PP
.SH ENUMERATION TYPE DOCUMENTATION
.PP 
.SS enum ACE_Filecache_Flag
.PP
\fBEnumeration values:\fR
.in +1c
.TP
\fB\fIACE_NOMAP\fR \fR
.TP
\fB\fIACE_MAPIT\fR \fR
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.