.TH Future_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Future_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Unbounded_Set.h"\fR
.br
\fC#include "ace/Synch.h"\fR
.br
\fC#include "ace/Strategies_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Future\fR"
.br
.ti -1c
.RI "class \fBACE_Future_Holder\fR"
.br
.ti -1c
.RI "class \fBACE_Future_Observer\fR"
.br
.ti -1c
.RI "class \fBACE_Future_Rep\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBFuture.h\fR,v 4.32 2001/09/19 10:04:02 doccvs Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Andres Kruse  ,  Douglas C. Schmidt <schmidt@cs.wustl.edu> ,  Per Andersson <Per.Andersson@hfera.ericsson.se> ,  and John Tucker <jtucker@infoglide.com>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.