.TH Future_Set_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Future_Set_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Thread.h"\fR
.br
\fC#include "ace/Message_Queue.h"\fR
.br
\fC#include "ace/Future.h"\fR
.br
\fC#include "ace/Hash_Map_Manager.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Future_Set\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBFuture_Set.h\fR,v 4.11 2000/11/01 22:16:22 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 John Tucker <jtucker@infoglide.com>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.