.TH Handle_Gobbler_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Handle_Gobbler_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Unbounded_Set.h"\fR
.br
\fC#include "ace/Handle_Gobbler.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Handle_Gobbler\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBHandle_Gobbler.h\fR,v 1.6 2001/03/26 21:18:41 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Kirthika Parameswaran <kirthika@cs.wustl.edu> ,  Irfan Pyarali <irfan@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.