.TH Hash_Map_With_Allocator_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hash_Map_With_Allocator_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Hash_Map_Manager.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Hash_Map_With_Allocator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBHash_Map_With_Allocator_T.h\fR,v 4.7 2001/09/30 14:57:49 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Marina Spivak <marina@cs.wustl.edu> ,  Irfan Pyarali <irfan@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.