.TH High_Res_Timer_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
High_Res_Timer_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_High_Res_Timer\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_HR_SCALE_CONVERSION\fR  (ACE_ONE_SECOND_IN_MSECS)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBHigh_Res_Timer.h\fR,v 4.54 2001/09/23 15:09:01 bala Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_HR_SCALE_CONVERSION  (ACE_ONE_SECOND_IN_MSECS)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.