.TH IO_SAP_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO_SAP_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Flag_Manip.h"\fR
.br
\fC#include "ace/IO_SAP.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_IO_SAP\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBIO_SAP.h\fR,v 4.12 2000/11/01 22:16:39 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.