.TH iosfwd_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iosfwd_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/config-all.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBiosfwd.h\fR,v 1.11 2000/11/01 22:17:39 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Irfan Pyarali
.PP
This file contains the portability ugliness for the Standard C++ Library. As implementations of the "standard" emerge, this file will need to be updated.
.PP
This files deals with forward declaration for the stream classes. Remember that since the new Standard C++ Library code for streams uses templates, simple forward declaration will not work.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.