.TH iovec 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iovec \- 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "size_t \fBiov_len\fR"
.br
.ti -1c
.RI "char* \fBiov_base\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS char * iovec::iov_base
.PP
.SS size_t iovec::iov_len
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.