.TH ip_mreq 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ip_mreq \- 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "struct in_addr \fBimr_multiaddr\fR"
.br
.ti -1c
.RI "struct in_addr \fBimr_interface\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS struct in_addr ip_mreq::imr_interface
.PP
.SS struct in_addr ip_mreq::imr_multiaddr
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.