.TH IPC_SAP_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPC_SAP_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Flag_Manip.h"\fR
.br
\fC#include "ace/IPC_SAP.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_IPC_SAP\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBIPC_SAP.h\fR,v 4.17 2001/07/10 17:30:41 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.