.TH Local_Tokens_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Local_Tokens_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Synch_T.h"\fR
.br
\fC#include "ace/Containers.h"\fR
.br
\fC#include "ace/Synch_Options.h"\fR
.br
\fC#include "ace/Map_Manager.h"\fR
.br
\fC#include "ace/Log_Msg.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBLocal_Tokens.h\fR,v 4.39 2001/02/18 16:21:21 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Karl-Heinz Dorn <kdorn@erlh.siemens.de> ,  Douglas C. Schmidt <schmidt@cs.wustl.edu> ,  and Tim Harrison <harrison@cs.wustl.edu>
.PP
This file contains definitions for the following classes:
.PP
public: 7. ACE_Token_Proxy 8. ACE_Null_Token : public ACE_Token_Proxy 9. ACE_Local_Mutex : public ACE_Token_Proxy *. ACE_Local_RLock : public ACE_Local_Mutex &. ACE_Local_WLock : public ACE_Local_Mutex private: 1. ACE_TOKEN_CONST 3. ACE_TPQ_Entry b. ACE_TSS_TPQ_Entry c. ACE_TPQ_Iterator 4. ACE_Token_Proxy_Queue 5. ACE_Tokens 6. ACE_Mutex_Token : public ACE_Tokens 12. ACE_RW_Token : public ACE_Tokens a. ACE_Token_Name
.PP
Note that the locking classes defined in this file are *not* intended to be used as general-purpose synchronization mechanisms, such as mutexes or semaphores. Instead, you should use the , , , etc., that are defined in $\fBACE_ROOT/ace/Synch.h\fR and $\fBACE_ROOT/ace/Synch_T.h\fR or the  that's defined in $\fBACE_ROOT/ace/Token.h\fR.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.