.TH Local_Name_Space_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Local_Name_Space_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Name_Space.h"\fR
.br
\fC#include "ace/Naming_Context.h"\fR
.br
\fC#include "ace/SString.h"\fR
.br
\fC#include "ace/Local_Name_Space.h"\fR
.br
\fC#include "ace/Hash_Map_Manager.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Local_Name_Space\fR"
.br
.ti -1c
.RI "class \fBACE_Name_Space_Map\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Unbounded_Set\fR<\fBACE_WString\fR> \fBACE_WSTRING_SET\fR"
.br
.ti -1c
.RI "typedef \fBACE_Hash_Map_Manager\fR<\fBACE_NS_String\fR, \fBACE_NS_Internal\fR, \fBACE_Null_Mutex\fR> \fBMAP_MANAGER\fR"
.br
.ti -1c
.RI "typedef \fBACE_Hash_Map_Iterator\fR<\fBACE_NS_String\fR, \fBACE_NS_Internal\fR, \fBACE_Null_Mutex\fR> \fBMAP_ITERATOR\fR"
.br
.ti -1c
.RI "typedef \fBACE_Hash_Map_Entry\fR<\fBACE_NS_String\fR, \fBACE_NS_Internal\fR> \fBMAP_ENTRY\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBLocal_Name_Space_T.h\fR,v 4.30 2000/11/01 22:16:39 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Prashant Jain (pjain@cs.wustl.edu) ,  Irfan Pyarali (irfan@wuerl.wustl.edu) ,  and Douglas C. Schmidt (schmidt@cs.wustl.edu).
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Unbounded_Set\fR<\fBACE_WString\fR> ACE_WSTRING_SET
.PP
.SS typedef \fBACE_Hash_Map_Entry\fR<\fBACE_NS_String\fR, \fBACE_NS_Internal\fR> MAP_ENTRY
.PP
.SS typedef \fBACE_Hash_Map_Iterator\fR<\fBACE_NS_String\fR, \fBACE_NS_Internal\fR, \fBACE_Null_Mutex\fR> MAP_ITERATOR
.PP
.SS typedef \fBACE_Hash_Map_Manager\fR<\fBACE_NS_String\fR, \fBACE_NS_Internal\fR, \fBACE_Null_Mutex\fR> MAP_MANAGER
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.