.TH Log_Msg_IPC_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log_Msg_IPC_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Log_Msg_Backend.h"\fR
.br
\fC#include "ace/SOCK_Connector.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Log_Msg_IPC\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_SOCK_Stream\fR \fBACE_LOG_MSG_IPC_STREAM\fR"
.br
.ti -1c
.RI "typedef \fBACE_SOCK_Connector\fR \fBACE_LOG_MSG_IPC_CONNECTOR\fR"
.br
.ti -1c
.RI "typedef \fBACE_INET_Addr\fR \fBACE_LOG_MSG_IPC_ADDR\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBLog_Msg_IPC.h\fR,v 4.2 2000/11/01 22:16:39 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Carlos O'Ryan
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_INET_Addr\fR ACE_LOG_MSG_IPC_ADDR
.PP
.SS typedef \fBACE_SOCK_Connector\fR ACE_LOG_MSG_IPC_CONNECTOR
.PP
.SS typedef \fBACE_SOCK_Stream\fR ACE_LOG_MSG_IPC_STREAM
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.