.TH Log_Record_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log_Record_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Log_Priority.h"\fR
.br
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Log_Record.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Log_Record\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBLog_Record.h\fR,v 4.43 2001/08/26 13:18:13 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.