.TH Log_Msg_UNIX_Syslog_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log_Msg_UNIX_Syslog_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/config-all.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBLog_Msg_UNIX_Syslog.h\fR,v 4.1 2001/07/06 16:27:05 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Jerry D. De Master <jdemaster@rite-solutions.com>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.