.TH Logging_Strategy_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logging_Strategy_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/Service_Object.h"\fR
.br
\fC#include "ace/Log_Msg.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Logging_Strategy\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_DEFAULT_LOGFILE_POLL_INTERVAL\fR  600"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBLogging_Strategy.h\fR,v 4.11 2001/08/26 16:58:53 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Prashant Jain <pjain@cs.wustl.edu>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_DEFAULT_LOGFILE_POLL_INTERVAL  600
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.