.TH LSOCK_Acceptor_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LSOCK_Acceptor_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/SOCK_Acceptor.h"\fR
.br
\fC#include "ace/UNIX_Addr.h"\fR
.br
\fC#include "ace/LSOCK_Stream.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_LSOCK_Acceptor\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBLSOCK_Acceptor.h\fR,v 4.12 2000/11/12 20:30:31 brunsch Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.