.TH Malloc_Base_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Malloc_Base_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Allocator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBMalloc_Base.h\fR,v 4.12 2001/03/26 21:18:50 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt and Irfan Pyarali
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.