.TH Malloc_Allocator_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Malloc_Allocator_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/Malloc_Base.h"\fR
.br
\fC#include "ace/Log_Msg.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_New_Allocator\fR"
.br
.ti -1c
.RI "class \fBACE_Static_Allocator_Base\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_MALLOC_STATS\fR(X)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBMalloc_Allocator.h\fR,v 4.4 2001/04/13 12:26:00 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Priyanka Gontla <pgontla@ece.uci.edu>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_MALLOC_STATS(X)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.