.TH Malloc_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Malloc_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/Synch.h"\fR
.br
\fC#include "ace/Malloc.h"\fR
.br
\fC#include "ace/Malloc_Allocator.h"\fR
.br
\fC#include "ace/Free_List.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Allocator_Adapter\fR"
.br
.ti -1c
.RI "class \fBACE_Cached_Allocator\fR"
.br
.ti -1c
.RI "class \fBACE_Cached_Mem_Pool_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Malloc\fR"
.br
.ti -1c
.RI "class \fBACE_Malloc_FIFO_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_Malloc_FIFO_Iterator_T\fR"
.br
.ti -1c
.RI "class \fBACE_Malloc_LIFO_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_Malloc_LIFO_Iterator_T\fR"
.br
.ti -1c
.RI "class \fBACE_Malloc_T\fR"
.br
.ti -1c
.RI "class \fBACE_Static_Allocator\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_Malloc_Iterator\fR  \fBACE_Malloc_LIFO_Iterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBMalloc_T.h\fR,v 4.63 2001/04/25 08:37:56 nanbor Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt and Irfan Pyarali
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_Malloc_Iterator  \fBACE_Malloc_LIFO_Iterator\fR
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.