.TH Message_Queue_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Message_Queue_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Message_Queue.h"\fR
.br
\fC#include "ace/Synch.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Dynamic_Message_Queue\fR"
.br
.ti -1c
.RI "class \fBACE_Message_Queue\fR"
.br
.ti -1c
.RI "class \fBACE_Message_Queue_Ex\fR"
.br
.ti -1c
.RI "class \fBACE_Message_Queue_Factory\fR"
.br
.ti -1c
.RI "class \fBACE_Message_Queue_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_Message_Queue_Reverse_Iterator\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Message_Queue\fR<ACE_SYNCH> \fBACE_DEFAULT_MESSAGE_QUEUE_TYPE\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBMessage_Queue_T.h\fR,v 4.33 2001/08/14 12:16:51 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Message_Queue\fR<ACE_SYNCH> ACE_DEFAULT_MESSAGE_QUEUE_TYPE
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.