.TH Method_Object_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Method_Object_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Method_Request.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Method_Request\fR \fBACE_Method_Object\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBMethod_Object.h\fR,v 4.9 2000/11/01 22:16:42 coryan Exp
.PP
This file just includes "\fBace/Method_Request.h\fR" and is just here for backwards compatibility with earlier versions of \fBACE\fR. Please don't use it directly since it may go away at some point.
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Method_Request\fR ACE_Method_Object
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.