.TH msghdr 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msghdr \- 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "sockaddr* \fBmsg_name\fR"
.br
.ti -1c
.RI "int \fBmsg_namelen\fR"
.br
.ti -1c
.RI "\fBiovec\fR* \fBmsg_iov\fR"
.br
.ti -1c
.RI "int \fBmsg_iovlen\fR"
.br
.ti -1c
.RI "\fBcaddr_t\fR \fBmsg_accrights\fR"
.br
.ti -1c
.RI "int \fBmsg_accrightslen\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBcaddr_t\fR msghdr::msg_accrights
.PP
.SS int msghdr::msg_accrightslen
.PP
.SS \fBiovec\fR * msghdr::msg_iov
.PP
.SS int msghdr::msg_iovlen
.PP
.SS sockaddr * msghdr::msg_name
.PP
.SS int msghdr::msg_namelen
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.