.TH Name_Request_Reply_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Name_Request_Reply_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Time_Value.h"\fR
.br
\fC#include "ace/SString.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Name_Reply\fR"
.br
.ti -1c
.RI "class \fBACE_Name_Request\fR"
.br
.ti -1c
.RI "struct \fBACE_Name_Reply::Transfer\fR"
.br
.ti -1c
.RI "struct \fBACE_Name_Request::Transfer\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBName_Request_Reply.h\fR,v 4.15 2000/11/02 20:12:53 coryan Exp
.PP
Define the format used to exchange messages between the ACE_Name Server and its clients.
.PP
\fBAuthor(s): \fR
.in +1c
 Gerhard Lenzer ,  Douglas C. Schmidt ,  and Prashant Jain
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.