.TH Name_Space_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Name_Space_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/SString.h"\fR
.br
\fC#include "ace/Unbounded_Set.h"\fR
.br
\fC#include "ace/Name_Proxy.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Name_Binding\fR"
.br
.ti -1c
.RI "class \fBACE_Name_Space\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Unbounded_Set\fR<\fBACE_Name_Binding\fR> \fBACE_BINDING_SET\fR"
.br
.ti -1c
.RI "typedef \fBACE_Unbounded_Set_Iterator\fR<\fBACE_Name_Binding\fR> \fBACE_BINDING_ITERATOR\fR"
.br
.ti -1c
.RI "typedef \fBACE_Unbounded_Set\fR<\fBACE_WString\fR> \fBACE_PWSTRING_SET\fR"
.br
.ti -1c
.RI "typedef \fBACE_Unbounded_Set_Iterator\fR<\fBACE_WString\fR> \fBACE_PWSTRING_ITERATOR\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBName_Space.h\fR,v 4.12 2001/03/26 21:18:50 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Prashant Jain
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Unbounded_Set_Iterator\fR<\fBACE_Name_Binding\fR> ACE_BINDING_ITERATOR
.PP
.SS typedef \fBACE_Unbounded_Set\fR<\fBACE_Name_Binding\fR> ACE_BINDING_SET
.PP
.SS typedef \fBACE_Unbounded_Set_Iterator\fR<\fBACE_WString\fR> ACE_PWSTRING_ITERATOR
.PP
.SS typedef \fBACE_Unbounded_Set\fR<\fBACE_WString\fR> ACE_PWSTRING_SET
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.