.TH Naming_Context_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Naming_Context_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/SString.h"\fR
.br
\fC#include "ace/Containers.h"\fR
.br
\fC#include "ace/Service_Object.h"\fR
.br
\fC#include "ace/Name_Proxy.h"\fR
.br
\fC#include "ace/Name_Space.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Name_Options\fR"
.br
.ti -1c
.RI "class \fBACE_Naming_Context\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBNaming_Context.h\fR,v 4.26 2001/09/15 13:18:12 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Gerhard Lenzer ,  Douglas C. Schmidt ,  and Prashant Jain
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.