.TH Obstack_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Obstack_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Obchunk.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Obstack_T\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBObstack_T.h\fR,v 4.1 2001/06/13 15:53:16 nanbor Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt, Nanbor Wang
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.