.TH Obstack_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Obstack_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Obstack_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Obstack_T\fR<char> \fBACE_Obstack\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBObstack.h\fR,v 4.14 2001/09/25 19:06:33 nanbor Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Obstack_T\fR<char> ACE_Obstack
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.