.TH OS_Errno_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OS_Errno_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/config.h"\fR
.br
\fC#include "ace/OS_Export.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Errno_Guard\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBENOSYS\fR  EFAULT"
.br
.ti -1c
.RI "#define \fBENOTSUP\fR  ENOSYS"
.br
.ti -1c
.RI "#define \fBACE_ERRNO_TYPE\fR  int"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBOS_Errno.h\fR,v 4.1 2000/11/13 01:04:55 brunsch Exp
.PP
\fBAuthor(s): \fR
.in +1c
 (Originally in \fBOS.h\fR)Doug Schmidt <schmidt@cs.wustl.edu> ,  Jesper S. M|ller<stophph@diku.dk> ,  and a cast of thousands...
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_ERRNO_TYPE  int
.PP
.SS #define ENOSYS  EFAULT
.PP
.SS #define ENOTSUP  ENOSYS
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.