.TH OS_TLI_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OS_TLI_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/config-all.h"\fR
.br
\fC#include "ace/OS_Export.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_OS_TLI\fR"
.br
.in -1c
.SS Functions

.in +1c
.ti -1c
.RI "int \fBt_accept\fR (int fildes, int resfd, struct t_call *call)"
.br
.ti -1c
.RI "char* \fBt_alloc\fR (int fildes, int struct_type, int fields)"
.br
.ti -1c
.RI "int \fBt_bind\fR (int fildes, struct t_bind *req, struct t_bind *ret)"
.br
.ti -1c
.RI "int \fBt_close\fR (int fildes)"
.br
.ti -1c
.RI "int \fBt_connect\fR (int fildes, struct t_call *sndcall, struct t_call *rcvcall)"
.br
.ti -1c
.RI "void \fBt_error\fR (const char *errmsg)"
.br
.ti -1c
.RI "int \fBt_free\fR (char *ptr, int struct_type)"
.br
.ti -1c
.RI "int \fBt_getinfo\fR (int fildes, struct t_info *info)"
.br
.ti -1c
.RI "int \fBt_getname\fR (int fildes, struct netbuf *namep, int type)"
.br
.ti -1c
.RI "int \fBt_getstate\fR (int fildes)"
.br
.ti -1c
.RI "int \fBt_listen\fR (int fildes, struct t_call *call)"
.br
.ti -1c
.RI "int \fBt_look\fR (int fildes)"
.br
.ti -1c
.RI "int \fBt_open\fR (char *path, int oflag, struct t_info *info)"
.br
.ti -1c
.RI "int \fBt_optmgmt\fR (int fildes, struct t_optmgmt *req, struct t_optmgmt *ret)"
.br
.ti -1c
.RI "int \fBt_rcv\fR (int fildes, char *buf, unsigned int nbytes, int *flags)"
.br
.ti -1c
.RI "int \fBt_rcvconnect\fR (int fildes, struct t_call *call)"
.br
.ti -1c
.RI "int \fBt_rcvdis\fR (int fildes, struct t_discon *discon)"
.br
.ti -1c
.RI "int \fBt_rcvrel\fR (int fildes)"
.br
.ti -1c
.RI "int \fBt_rcvudata\fR (int fildes, struct t_unitdata *unitdata, int *flags)"
.br
.ti -1c
.RI "int \fBt_rcvuderr\fR (int fildes, struct t_uderr *uderr)"
.br
.ti -1c
.RI "int \fBt_snd\fR (int fildes, const char *buf, unsigned int nbytes, int flags)"
.br
.ti -1c
.RI "int \fBt_snddis\fR (int fildes, struct t_call *call)"
.br
.ti -1c
.RI "int \fBt_sndrel\fR (int fildes)"
.br
.ti -1c
.RI "int \fBt_sndudata\fR (int fildes, struct t_unitdata *unitdata)"
.br
.ti -1c
.RI "int \fBt_sync\fR (int fildes)"
.br
.ti -1c
.RI "int \fBt_unbind\fR (int fildes)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBOS_TLI.h\fR,v 4.7 2001/07/11 12:14:35 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt <schmidt@cs.wustl.edu>
.PP
.SH FUNCTION DOCUMENTATION
.PP 
.SS int t_accept (int fildes, int resfd, struct t_call * call)
.PP
.SS char* t_alloc (int fildes, int struct_type, int fields)
.PP
.SS int t_bind (int fildes, struct t_bind * req, struct t_bind * ret)
.PP
.SS int t_close (int fildes)
.PP
.SS int t_connect (int fildes, struct t_call * sndcall, struct t_call * rcvcall)
.PP
.SS void t_error (const char * errmsg)
.PP
.SS int t_free (char * ptr, int struct_type)
.PP
.SS int t_getinfo (int fildes, struct t_info * info)
.PP
.SS int t_getname (int fildes, struct netbuf * namep, int type)
.PP
.SS int t_getstate (int fildes)
.PP
.SS int t_listen (int fildes, struct t_call * call)
.PP
.SS int t_look (int fildes)
.PP
.SS int t_open (char * path, int oflag, struct t_info * info)
.PP
.SS int t_optmgmt (int fildes, struct t_optmgmt * req, struct t_optmgmt * ret)
.PP
.SS int t_rcv (int fildes, char * buf, unsigned int nbytes, int * flags)
.PP
.SS int t_rcvconnect (int fildes, struct t_call * call)
.PP
.SS int t_rcvdis (int fildes, struct t_discon * discon)
.PP
.SS int t_rcvrel (int fildes)
.PP
.SS int t_rcvudata (int fildes, struct t_unitdata * unitdata, int * flags)
.PP
.SS int t_rcvuderr (int fildes, struct t_uderr * uderr)
.PP
.SS int t_snd (int fildes, const char * buf, unsigned int nbytes, int flags)
.PP
.SS int t_snddis (int fildes, struct t_call * call)
.PP
.SS int t_sndrel (int fildes)
.PP
.SS int t_sndudata (int fildes, struct t_unitdata * unitdata)
.PP
.SS int t_sync (int fildes)
.PP
.SS int t_unbind (int fildes)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.