.TH Pair_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pair_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Pair_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBPair.h\fR,v 4.5 2000/11/01 22:17:02 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Irfan Pyarali
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.