.TH Pair_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pair_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Pair.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Pair\fR"
.br
.ti -1c
.RI "class \fBACE_Reference_Pair\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBPair_T.h\fR,v 4.7 2000/11/01 22:17:02 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Irfan Pyarali <irfan@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.