.TH Parse_Node_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parse_Node_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Service_Types.h"\fR
.br
\fC#include "ace/DLL.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Dummy_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Dynamic_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Function_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Location_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Object_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Parse_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Remove_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Resume_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Static_Function_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Static_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Stream_Node\fR"
.br
.ti -1c
.RI "class \fBACE_Suspend_Node\fR"
.br
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "int \fBace_yyerrno\fR"
.br
.ti -1c
.RI "\fBACE_Service_Config\fR* \fBace_this_svc\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBParse_Node.h\fR,v 4.21 2001/05/10 22:44:43 shuston Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH VARIABLE DOCUMENTATION
.PP 
.SS \fBACE_Service_Config\fR * ace_this_svc
.PP
.SS int ace_yyerrno
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.