.TH pre_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pre_h \- 
.SH SYNOPSIS
.br
.PP
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBpre.h\fR,v 4.3 2001/07/09 09:19:04 doccvs Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Christopher Kohlhoff <chris@kohlhoff.com>
.PP
This file save the original alignment rules and changes the alignment boundary to \fBACE\fR's default.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.