.TH Proactor_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Proactor_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Asynch_IO.h"\fR
.br
\fC#include "ace/Asynch_IO_Impl.h"\fR
.br
\fC#include "ace/Thread_Manager.h"\fR
.br
\fC#include "ace/Timer_Queue.h"\fR
.br
\fC#include "ace/Timer_List.h"\fR
.br
\fC#include "ace/Timer_Heap.h"\fR
.br
\fC#include "ace/Timer_Wheel.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Proactor\fR"
.br
.ti -1c
.RI "class \fBACE_Proactor_Handle_Timeout_Upcall\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBProactor.h\fR,v 4.66 2001/06/26 22:39:11 bala Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Irfan Pyarali <irfan@cs.wustl.edu> ,  Tim Harrison <harrison@cs.wustl.edu> ,  Alexander Babu Arulanthu 
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.