.TH Process_Manager_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Process_Manager_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Synch.h"\fR
.br
\fC#include "ace/Reactor.h"\fR
.br
\fC#include "ace/Event_Handler.h"\fR
.br
\fC#include "ace/Process.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Process_Descriptor\fR"
.br
.ti -1c
.RI "class \fBACE_Process_Manager\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBProcess_Manager.h\fR,v 4.31 2001/06/25 05:05:32 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.