.TH Process_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Process_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Handle_Set.h"\fR
.br
\fC#include "ace/SString.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Managed_Process\fR"
.br
.ti -1c
.RI "class \fBACE_Process\fR"
.br
.ti -1c
.RI "class \fBACE_Process_Options\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBProcess.h\fR,v 4.65 2001/08/16 23:34:16 shuston Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Tim Harrison <harrison@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.