.TH Profile_Timer_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Profile_Timer_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/Time_Value.h"\fR
.br
\fC#include "ace/High_Res_Timer.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Profile_Timer::ACE_Elapsed_Time\fR"
.br
.ti -1c
.RI "class \fBACE_Profile_Timer\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBProfile_Timer.h\fR,v 4.21 2000/11/01 22:17:02 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.