.TH QtReactor_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QtReactor_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Select_Reactor.h"\fR
.br
\fC#include "ace/Map_Manager.h"\fR
.br
\fC#include <qapplication.h>\fR
.br
\fC#include <qobject.h>\fR
.br
\fC#include <qsocketnotifier.h>\fR
.br
\fC#include <qtimer.h>\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_QtReactor\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBQtReactor.h\fR,v 4.6 2001/09/22 15:28:14 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Hamish Friedlander <ullexco@wave.co.nz> ,  Balachandran Natarajan <bala@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.