.TH Read_Buffer_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Read_Buffer_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/Malloc.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Read_Buffer\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBRead_Buffer.h\fR,v 4.15 2000/11/01 22:17:03 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt and Seth Widoff
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.