.TH Refcounted_Auto_Ptr_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Refcounted_Auto_Ptr_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Auto_Ptr.h"\fR
.br
\fC#include "ace/Refcounted_Auto_Ptr.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Refcounted_Auto_Ptr\fR"
.br
.ti -1c
.RI "class \fBACE_Refcounted_Auto_Ptr_Rep\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBRefcounted_Auto_Ptr.h\fR,v 4.4 2001/07/03 15:33:33 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 John Tucker <JTucker@infoglide.com>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.