.TH Remote_Name_Space_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Remote_Name_Space_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/SString.h"\fR
.br
\fC#include "ace/Name_Proxy.h"\fR
.br
\fC#include "ace/Name_Space.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Remote_Name_Space\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBRemote_Name_Space.h\fR,v 4.15 2001/03/26 21:18:50 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Prashant Jain
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.