.TH Remote_Tokens_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Remote_Tokens_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/INET_Addr.h"\fR
.br
\fC#include "ace/SOCK_Connector.h"\fR
.br
\fC#include "ace/SOCK_Stream.h"\fR
.br
\fC#include "ace/Synch_Options.h"\fR
.br
\fC#include "ace/Local_Tokens.h"\fR
.br
\fC#include "ace/Token_Request_Reply.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBRemote_Tokens.h\fR,v 4.15 2001/02/18 16:21:22 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt (schmidt@cs.wustl.edu) ,  Tim Harrison (harrison@cs.wustl.edu)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.