.TH rusage 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rusage \- 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "FILETIME \fBru_utime\fR"
.br
.ti -1c
.RI "FILETIME \fBru_stime\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS FILETIME rusage::ru_stime
.PP
.SS FILETIME rusage::ru_utime
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.