.TH Select_Reactor_Base_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Select_Reactor_Base_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Signal.h"\fR
.br
\fC#include "ace/Timer_Queue.h"\fR
.br
\fC#include "ace/Event_Handler.h"\fR
.br
\fC#include "ace/Handle_Set.h"\fR
.br
\fC#include "ace/Token.h"\fR
.br
\fC#include "ace/Pipe.h"\fR
.br
\fC#include "ace/Reactor_Impl.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Event_Tuple\fR"
.br
.ti -1c
.RI "class \fBACE_Select_Reactor_Handle_Set\fR"
.br
.ti -1c
.RI "class \fBACE_Select_Reactor_Handler_Repository\fR"
.br
.ti -1c
.RI "class \fBACE_Select_Reactor_Handler_Repository_Iterator\fR"
.br
.ti -1c
.RI "class \fBACE_Select_Reactor_Impl\fR"
.br
.ti -1c
.RI "class \fBACE_Select_Reactor_Notify\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef void (ACE_Handle_Set::* \fBACE_FDS_PTMF\fR )(ACE_HANDLE)"
.br
.ti -1c
.RI "typedef int (ACE_Event_Handler::* \fBACE_EH_PTMF\fR )(ACE_HANDLE)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBSelect_Reactor_Base.h\fR,v 4.29 2001/09/09 13:22:32 bala Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef int (ACE_Event_Handler::* ACE_EH_PTMF)(ACE_HANDLE)
.PP
.SS typedef void (ACE_Handle_Set::* ACE_FDS_PTMF)(ACE_HANDLE)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.