.TH Select_Reactor_T_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Select_Reactor_T_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Select_Reactor_Base.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Select_Reactor_T\fR"
.br
.ti -1c
.RI "class \fBACE_Select_Reactor_Token_T\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBSelect_Reactor_T.h\fR,v 4.32 2001/09/22 15:28:14 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.