.TH semun 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semun \- 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBval\fR"
.br
.ti -1c
.RI "struct semid_ds* \fBbuf\fR"
.br
.ti -1c
.RI "u_short* \fBarray\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS u_short * semun::array
.PP
.SS struct semid_ds * semun::buf
.PP
.SS int semun::val
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.