.TH Service_Object_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Service_Object_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Shared_Object.h"\fR
.br
\fC#include "ace/Event_Handler.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Service_Object\fR"
.br
.ti -1c
.RI "class \fBACE_Service_Object_Ptr\fR"
.br
.ti -1c
.RI "class \fBACE_Service_Type\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_Component\fR  \fBACE_Service_Object\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBService_Object.h\fR,v 4.27 2001/09/30 14:57:49 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_Component  \fBACE_Service_Object\fR
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.