.TH Service_Templates_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Service_Templates_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Svc_Conf.h"\fR
.br
\fC#include "ace/Auto_Ptr.h"\fR
.br
\fC#include "ace/Thread_Manager.h"\fR
.br
\fC#include "ace/Stream_Modules.h"\fR
.br
\fC#include "ace/Stream.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBService_Templates.h\fR,v 4.3 2000/11/01 22:17:03 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Priyanka Gontla <pgontla@ece.uci.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.