.TH Shared_Memory_SV_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shared_Memory_SV_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Shared_Memory.h"\fR
.br
\fC#include "ace/SV_Shared_Memory.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Shared_Memory_SV\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBShared_Memory_SV.h\fR,v 4.10 2000/11/01 22:17:03 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.