.TH siginfo_t 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
siginfo_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBsiginfo_t\fR (ACE_HANDLE handle)"
.br
.ti -1c
.RI "\fBsiginfo_t\fR (ACE_HANDLE *handles)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "ACE_HANDLE \fBsi_handle_\fR"
.br
.ti -1c
.RI "ACE_HANDLE* \fBsi_handles_\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS siginfo_t::siginfo_t (ACE_HANDLE handle)
.PP
.SS siginfo_t::siginfo_t (ACE_HANDLE * handles)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS ACE_HANDLE siginfo_t::si_handle_
.PP
.SS ACE_HANDLE * siginfo_t::si_handles_
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.