.TH Signal_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Signal_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Synch.h"\fR
.br
\fC#include "ace/Event_Handler.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Sig_Action\fR"
.br
.ti -1c
.RI "class \fBACE_Sig_Adapter\fR"
.br
.ti -1c
.RI "class \fBACE_Sig_Guard\fR"
.br
.ti -1c
.RI "class \fBACE_Sig_Handler\fR"
.br
.ti -1c
.RI "class \fBACE_Sig_Handlers\fR"
.br
.ti -1c
.RI "class \fBACE_Sig_Set\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef struct sigaction \fBACE_SIGACTION\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBSignal.h\fR,v 4.39 2001/03/26 21:18:50 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef struct sigaction ACE_SIGACTION
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.