.TH SOCK_Dgram_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOCK_Dgram_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/SOCK.h"\fR
.br
\fC#include "ace/Addr.h"\fR
.br
\fC#include "ace/SOCK_Dgram.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_SOCK_Dgram\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBSOCK_Dgram.h\fR,v 4.30 2001/09/05 18:32:35 doccvs Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.