.TH SOCK_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOCK_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/Addr.h"\fR
.br
\fC#include "ace/IPC_SAP.h"\fR
.br
\fC#include "ace/SOCK.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_SOCK\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBSOCK.h\fR,v 4.30 2001/08/20 17:20:15 shuston Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.