.TH Sock_Connect_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sock_Connect_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/Sock_Connect.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Sock_Connect\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBSock_Connect.h\fR,v 1.3 2001/05/24 02:00:50 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Priyanka Gontla <pgontla@ece.uci.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.