.TH SOCK_Connector_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOCK_Connector_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/SOCK_Stream.h"\fR
.br
\fC#include "ace/Time_Value.h"\fR
.br
\fC#include "ace/SOCK_Connector.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_SOCK_Connector\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBSOCK_Connector.h\fR,v 4.24 2001/08/20 04:11:02 shuston Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.