.TH strbuf 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strbuf \- 
.SH SYNOPSIS
.br
.PP
\fC#include <OS.h>\fR
.PP
Inherited by \fBACE_Str_Buf\fR.
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBmaxlen\fR"
.br
.ti -1c
.RI "int \fBlen\fR"
.br
.ti -1c
.RI "void* \fBbuf\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS void * strbuf::buf
.PP
.SS int strbuf::len
.PP
.SS int strbuf::maxlen
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.