.TH Stream_Modules_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stream_Modules_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/Task.h"\fR
.br
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Stream_Head\fR"
.br
.ti -1c
.RI "class \fBACE_Stream_Tail\fR"
.br
.ti -1c
.RI "class \fBACE_Thru_Task\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBStream_Modules.h\fR,v 4.18 2000/11/01 22:17:03 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.