.TH Stream_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stream_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/IO_Cntl_Msg.h"\fR
.br
\fC#include "ace/Message_Block.h"\fR
.br
\fC#include "ace/Time_Value.h"\fR
.br
\fC#include "ace/Module.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Stream\fR"
.br
.ti -1c
.RI "class \fBACE_Stream_Iterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBStream.h\fR,v 4.25 2000/11/01 22:17:03 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt <schmidt@uci.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.