.TH SUN_Proactor_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SUN_Proactor_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/POSIX_Proactor.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBSUN_Proactor.h\fR,v 4.10 2001/07/02 01:03:13 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Alexander Libman 
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.