.TH SV_Message_Queue_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SV_Message_Queue_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/SV_Message.h"\fR
.br
\fC#include "ace/SV_Message_Queue.i"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_SV_Message_Queue\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBSV_Message_Queue.h\fR,v 4.13 2001/06/25 05:05:33 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.