.TH Svc_Conf_Tokens_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc_Conf_Tokens_h \- 
.SH SYNOPSIS
.br
.PP
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_DYNAMIC\fR  257"
.br
.ti -1c
.RI "#define \fBACE_STATIC\fR  258"
.br
.ti -1c
.RI "#define \fBACE_SUSPEND\fR  259"
.br
.ti -1c
.RI "#define \fBACE_RESUME\fR  260"
.br
.ti -1c
.RI "#define \fBACE_REMOVE\fR  261"
.br
.ti -1c
.RI "#define \fBACE_USTREAM\fR  262"
.br
.ti -1c
.RI "#define \fBACE_MODULE_T\fR  263"
.br
.ti -1c
.RI "#define \fBACE_STREAM_T\fR  264"
.br
.ti -1c
.RI "#define \fBACE_SVC_OBJ_T\fR  265"
.br
.ti -1c
.RI "#define \fBACE_ACTIVE\fR  266"
.br
.ti -1c
.RI "#define \fBACE_INACTIVE\fR  267"
.br
.ti -1c
.RI "#define \fBACE_PATHNAME\fR  268"
.br
.ti -1c
.RI "#define \fBACE_IDENT\fR  269"
.br
.ti -1c
.RI "#define \fBACE_STRING\fR  270"
.br
.ti -1c
.RI "#define \fBACE_LPAREN\fR  271"
.br
.ti -1c
.RI "#define \fBACE_RPAREN\fR  272"
.br
.ti -1c
.RI "#define \fBACE_LBRACE\fR  273"
.br
.ti -1c
.RI "#define \fBACE_RBRACE\fR  274"
.br
.ti -1c
.RI "#define \fBACE_STAR\fR  275"
.br
.ti -1c
.RI "#define \fBACE_COLON\fR  276"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_ACTIVE  266
.PP
.SS #define ACE_COLON  276
.PP
.SS #define ACE_DYNAMIC  257
.PP
.SS #define ACE_IDENT  269
.PP
.SS #define ACE_INACTIVE  267
.PP
.SS #define ACE_LBRACE  273
.PP
.SS #define ACE_LPAREN  271
.PP
.SS #define ACE_MODULE_T  263
.PP
.SS #define ACE_PATHNAME  268
.PP
.SS #define ACE_RBRACE  274
.PP
.SS #define ACE_REMOVE  261
.PP
.SS #define ACE_RESUME  260
.PP
.SS #define ACE_RPAREN  272
.PP
.SS #define ACE_STAR  275
.PP
.SS #define ACE_STATIC  258
.PP
.SS #define ACE_STREAM_T  264
.PP
.SS #define ACE_STRING  270
.PP
.SS #define ACE_SUSPEND  259
.PP
.SS #define ACE_SVC_OBJ_T  265
.PP
.SS #define ACE_USTREAM  262
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.