.TH Synch_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Synch_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/ACE.h"\fR
.br
\fC#include "ace/Synch_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Adaptive_Lock\fR"
.br
.ti -1c
.RI "class \fBACE_Auto_Event\fR"
.br
.ti -1c
.RI "class \fBACE_Barrier\fR"
.br
.ti -1c
.RI "class \fBACE_Condition_Attributes\fR"
.br
.ti -1c
.RI "class \fBACE_Condition_Thread_Mutex\fR"
.br
.ti -1c
.RI "class \fBACE_Event\fR"
.br
.ti -1c
.RI "class \fBACE_Guard< ACE_Null_Mutex >\fR"
.br
.ti -1c
.RI "class \fBACE_Lock\fR"
.br
.ti -1c
.RI "class \fBACE_Manual_Event\fR"
.br
.ti -1c
.RI "class \fBACE_Mutex\fR"
.br
.ti -1c
.RI "class \fBACE_Noop_Token\fR"
.br
.ti -1c
.RI "class \fBACE_Null_Barrier\fR"
.br
.ti -1c
.RI "class \fBACE_Null_Condition\fR"
.br
.ti -1c
.RI "class \fBACE_Null_Mutex\fR"
.br
.ti -1c
.RI "class \fBACE_Null_Semaphore\fR"
.br
.ti -1c
.RI "class \fBACE_Read_Guard< ACE_Null_Mutex >\fR"
.br
.ti -1c
.RI "class \fBACE_Recursive_Thread_Mutex\fR"
.br
.ti -1c
.RI "class \fBACE_RW_Mutex\fR"
.br
.ti -1c
.RI "class \fBACE_RW_Thread_Mutex\fR"
.br
.ti -1c
.RI "class \fBACE_Semaphore\fR"
.br
.ti -1c
.RI "struct \fBACE_Sub_Barrier\fR"
.br
.ti -1c
.RI "class \fBACE_Thread_Barrier\fR"
.br
.ti -1c
.RI "class \fBACE_Thread_Mutex\fR"
.br
.ti -1c
.RI "class \fBACE_Thread_Semaphore\fR"
.br
.ti -1c
.RI "class \fBACE_TSS_Adapter\fR"
.br
.ti -1c
.RI "class \fBACE_Write_Guard< ACE_Null_Mutex >\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBSynch.h\fR,v 4.120 2001/10/04 21:39:57 shuston Exp
.PP
Wrappers for various synchronization routines.
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.