.TH Thread_Manager_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Thread_Manager_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Thread.h"\fR
.br
\fC#include "ace/Thread_Adapter.h"\fR
.br
\fC#include "ace/Synch.h"\fR
.br
\fC#include "ace/Unbounded_Queue.h"\fR
.br
\fC#include "ace/Containers.h"\fR
.br
\fC#include "ace/Free_List.h"\fR
.br
\fC#include "ace/Singleton.h"\fR
.br
\fC#include "ace/Log_Msg.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_At_Thread_Exit\fR"
.br
.ti -1c
.RI "class \fBACE_At_Thread_Exit_Func\fR"
.br
.ti -1c
.RI "class \fBACE_Thread_Descriptor\fR"
.br
.ti -1c
.RI "class \fBACE_Thread_Descriptor_Base\fR"
.br
.ti -1c
.RI "class \fBACE_Thread_Manager\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_DEFAULT_THREAD_MANAGER_PREALLOC\fR  0"
.br
.ti -1c
.RI "#define \fBACE_DEFAULT_THREAD_MANAGER_LWM\fR  1"
.br
.ti -1c
.RI "#define \fBACE_DEFAULT_THREAD_MANAGER_INC\fR  1"
.br
.ti -1c
.RI "#define \fBACE_DEFAULT_THREAD_MANAGER_HWM\fR  ACE_DEFAULT_FREE_LIST_HWM"
.br
.ti -1c
.RI "#define \fBACE_DEFAULT_THREAD_MANAGER_LOCK\fR  ACE_SYNCH_MUTEX"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBThread_Manager.h\fR,v 4.129 2001/09/15 13:18:12 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_DEFAULT_THREAD_MANAGER_HWM  ACE_DEFAULT_FREE_LIST_HWM
.PP
.SS #define ACE_DEFAULT_THREAD_MANAGER_INC  1
.PP
.SS #define ACE_DEFAULT_THREAD_MANAGER_LOCK  ACE_SYNCH_MUTEX
.PP
.SS #define ACE_DEFAULT_THREAD_MANAGER_LWM  1
.PP
.SS #define ACE_DEFAULT_THREAD_MANAGER_PREALLOC  0
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.