.TH Timer_Hash_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer_Hash_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Timer_Hash_T.h"\fR
.br
\fC#include "ace/Timer_Heap_T.h"\fR
.br
\fC#include "ace/Timer_List_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Timer_Hash_Upcall\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX> \fBACE_Hash_Upcall\fR"
.br
.ti -1c
.RI "typedef \fBACE_Timer_List_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Hash_Upcall\fR, \fBACE_Null_Mutex\fR> \fBACE_Hash_Timer_List\fR"
.br
.ti -1c
.RI "typedef \fBACE_Timer_Heap_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Hash_Upcall\fR, \fBACE_Null_Mutex\fR> \fBACE_Hash_Timer_Heap\fR"
.br
.ti -1c
.RI "typedef \fBACE_Timer_Hash_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX, \fBACE_Hash_Timer_List\fR> \fBACE_Timer_Hash\fR"
.br
.ti -1c
.RI "typedef \fBACE_Timer_Hash_Iterator_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX, \fBACE_Hash_Timer_List\fR> \fBACE_Timer_Hash_Iterator\fR"
.br
.ti -1c
.RI "typedef \fBACE_Timer_Hash_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX, \fBACE_Hash_Timer_Heap\fR> \fBACE_Timer_Hash_Heap\fR"
.br
.ti -1c
.RI "typedef \fBACE_Timer_Hash_Iterator_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX, \fBACE_Hash_Timer_Heap\fR> \fBACE_Timer_Hash_Heap_Iterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBTimer_Hash.h\fR,v 1.9 2000/11/01 22:17:04 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Darrell Brunsch <brunsch@cs.wustl.edu>
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Timer_Heap_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Hash_Upcall\fR, \fBACE_Null_Mutex\fR> ACE_Hash_Timer_Heap
.PP
.SS typedef \fBACE_Timer_List_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Hash_Upcall\fR, \fBACE_Null_Mutex\fR> ACE_Hash_Timer_List
.PP
.SS typedef \fBACE_Timer_Hash_Upcall\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX> ACE_Hash_Upcall
.PP
.SS typedef \fBACE_Timer_Hash_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX, \fBACE_Hash_Timer_List\fR> ACE_Timer_Hash
.PP
.SS typedef \fBACE_Timer_Hash_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX, \fBACE_Hash_Timer_Heap\fR> ACE_Timer_Hash_Heap
.PP
.SS typedef \fBACE_Timer_Hash_Iterator_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX, \fBACE_Hash_Timer_Heap\fR> ACE_Timer_Hash_Heap_Iterator
.PP
.SS typedef \fBACE_Timer_Hash_Iterator_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX, \fBACE_Hash_Timer_List\fR> ACE_Timer_Hash_Iterator
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.