.TH Timer_Heap_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer_Heap_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Timer_Heap_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Timer_Heap_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX> \fBACE_Timer_Heap\fR"
.br
.ti -1c
.RI "typedef \fBACE_Timer_Heap_Iterator_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX> \fBACE_Timer_Heap_Iterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBTimer_Heap.h\fR,v 4.24 2000/11/01 22:17:04 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Timer_Heap_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX> ACE_Timer_Heap
.PP
.SS typedef \fBACE_Timer_Heap_Iterator_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX> ACE_Timer_Heap_Iterator
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.