.TH Timer_Queue_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer_Queue_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Synch.h"\fR
.br
\fC#include "ace/Timer_Queue_T.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Timer_Node_Dispatch_Info_T\fR<\fBACE_Event_Handler\fR *> \fBACE_Timer_Node_Dispatch_Info\fR"
.br
.ti -1c
.RI "typedef \fBACE_Timer_Node_T\fR<\fBACE_Event_Handler\fR *> \fBACE_Timer_Node\fR"
.br
.ti -1c
.RI "typedef \fBACE_Timer_Queue_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX> \fBACE_Timer_Queue\fR"
.br
.ti -1c
.RI "typedef \fBACE_Timer_Queue_Iterator_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX> \fBACE_Timer_Queue_Iterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBTimer_Queue.h\fR,v 4.30 2001/08/24 21:23:56 bala Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt and Irfan Pyarali
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Timer_Node_T\fR<\fBACE_Event_Handler\fR *> ACE_Timer_Node
.PP
.SS typedef \fBACE_Timer_Node_Dispatch_Info_T\fR<\fBACE_Event_Handler\fR *> ACE_Timer_Node_Dispatch_Info
.PP
.SS typedef \fBACE_Timer_Queue_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX> ACE_Timer_Queue
.PP
.SS typedef \fBACE_Timer_Queue_Iterator_T\fR<\fBACE_Event_Handler\fR *, \fBACE_Event_Handler_Handle_Timeout_Upcall\fR<ACE_SYNCH_RECURSIVE_MUTEX>, ACE_SYNCH_RECURSIVE_MUTEX> ACE_Timer_Queue_Iterator
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.