.TH Time_Value_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Time_Value_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/OS.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBTime_Value.h\fR,v 4.12 2000/11/01 22:17:04 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.