.TH TLI_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TLI_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/IPC_SAP.h"\fR
.br
\fC#include "ace/Addr.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_TLI\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_TLI_TCP_DEVICE\fR  "/dev/tcp""
.br
.ti -1c
.RI "#define \fBACE_XTI_ATM_DEVICE\fR  "/dev/xtisvc0""
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBTLI.h\fR,v 4.12 2000/11/01 22:17:03 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_TLI_TCP_DEVICE  "/dev/tcp"
.PP
.SS #define ACE_XTI_ATM_DEVICE  "/dev/xtisvc0"
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.