.TH Token_Request_Reply_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Token_Request_Reply_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Local_Tokens.h"\fR
.br
\fC#include "ace/Time_Value.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBToken_Request_Reply.h\fR,v 4.14 2001/02/18 16:21:23 schmidt Exp
.PP
Define the format used to exchange messages between the \fBACE_Token\fR Server and its clients.
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt (schmidt@cs.wustl.edu) ,  Tim Harrison (harrison@cs.wustl.edu)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.