.TH Token_Invariants_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Token_Invariants_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Synch.h"\fR
.br
\fC#include "ace/Map_Manager.h"\fR
.br
\fC#include "ace/Local_Tokens.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBToken_Invariants.h\fR,v 4.18 2001/02/18 16:21:23 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Tim Harrison (harrison@cs.wustl.edu)
.PP
Allows applications to test that invariants are always satisfied. Can test mutexes and readers/writer locks. Does not test recursive acquisition.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.