.TH Token_Collection_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Token_Collection_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Map_Manager.h"\fR
.br
\fC#include "ace/Local_Tokens.h"\fR
.br
\fC#include "ace/SString.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SH DETAILED DESCRIPTION
.PP 
.PP
\fBToken_Collection.h\fR,v 4.13 2001/02/18 16:21:23 schmidt Exp
.PP
The \fBACE_Token\fR class offers methods for acquiring, renewing, and releasing a synchronization token on a per-token basis. The ACE_Token_Collection offers an interface for performing operations on groups of tokens as a whole, or on a single token within the collection.
.PP
The atomic group operations are not yet implemented.
.PP
\fBAuthor(s): \fR
.in +1c
 Douglas C. Schmidt (schmidt@cs.wustl.edu) ,  Tim Harrison (harrison@cs.wustl.edu)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.