.TH Unbounded_Queue_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unbounded_Queue_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Node.h"\fR
.br
\fC#include "ace/OS_Memory.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_Unbounded_Queue\fR"
.br
.ti -1c
.RI "class \fBACE_Unbounded_Queue_Iterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBUnbounded_Queue.h\fR,v 4.3 2001/05/03 17:24:01 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Doug Schmidt
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.