.TH UPIPE_Stream_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPIPE_Stream_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Stream.h"\fR
.br
\fC#include "ace/Synch.h"\fR
.br
\fC#include "ace/SPIPE.h"\fR
.br
\fC#include "ace/Message_Queue.h"\fR
.br
\fC#include "ace/UPIPE_Addr.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_UPIPE_Stream\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBACE_Stream\fR<ACE_SYNCH> \fBMT_Stream\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBUPIPE_Stream.h\fR,v 4.12 2000/11/01 22:17:19 coryan Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Gerhard Lenzer ,  Douglas C. Schmidt
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef \fBACE_Stream\fR<ACE_SYNCH> MT_Stream
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.