.TH Version_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Version_h \- 
.SH SYNOPSIS
.br
.PP
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBACE_MAJOR_VERSION\fR  5"
.br
.ti -1c
.RI "#define \fBACE_MINOR_VERSION\fR  2"
.br
.ti -1c
.RI "#define \fBACE_BETA_VERSION\fR  0"
.br
.ti -1c
.RI "#define \fBACE_VERSION\fR  "5.2""
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ACE_BETA_VERSION  0
.PP
.SS #define ACE_MAJOR_VERSION  5
.PP
.SS #define ACE_MINOR_VERSION  2
.PP
.SS #define ACE_VERSION  "5.2"
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.