.TH WFMO_Reactor_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WFMO_Reactor_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Signal.h"\fR
.br
\fC#include "ace/Timer_Queue.h"\fR
.br
\fC#include "ace/Event_Handler.h"\fR
.br
\fC#include "ace/Synch.h"\fR
.br
\fC#include "ace/Reactor_Impl.h"\fR
.br
\fC#include "ace/Message_Queue.h"\fR
.br
\fC#include "ace/Process_Mutex.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "struct \fB_WSANETWORKEVENTS\fR"
.br
.ti -1c
.RI "class \fBACE_Wakeup_All_Threads_Handler\fR"
.br
.ti -1c
.RI "class \fBACE_WFMO_Reactor\fR"
.br
.ti -1c
.RI "class \fBACE_WFMO_Reactor_Handler_Repository\fR"
.br
.ti -1c
.RI "class \fBACE_WFMO_Reactor_Notify\fR"
.br
.ti -1c
.RI "class \fBACE_WFMO_Reactor_Handler_Repository::Common_Info\fR"
.br
.ti -1c
.RI "class \fBACE_WFMO_Reactor_Handler_Repository::Current_Info\fR"
.br
.ti -1c
.RI "class \fBACE_WFMO_Reactor_Handler_Repository::Suspended_Info\fR"
.br
.ti -1c
.RI "class \fBACE_WFMO_Reactor_Handler_Repository::To_Be_Added_Info\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBFD_READ_BIT\fR  0"
.br
.ti -1c
.RI "#define \fBFD_WRITE_BIT\fR  1"
.br
.ti -1c
.RI "#define \fBFD_OOB_BIT\fR  2"
.br
.ti -1c
.RI "#define \fBFD_ACCEPT_BIT\fR  3"
.br
.ti -1c
.RI "#define \fBFD_CONNECT_BIT\fR  4"
.br
.ti -1c
.RI "#define \fBFD_CLOSE_BIT\fR  5"
.br
.ti -1c
.RI "#define \fBFD_QOS_BIT\fR  6"
.br
.ti -1c
.RI "#define \fBFD_GROUP_QOS_BIT\fR  7"
.br
.ti -1c
.RI "#define \fBFD_QOS\fR  (1 << FD_QOS_BIT)"
.br
.ti -1c
.RI "#define \fBFD_GROUP_QOS\fR  (1 << FD_GROUP_QOS_BIT)"
.br
.ti -1c
.RI "#define \fBFD_MAX_EVENTS\fR  8"
.br
.ti -1c
.RI "#define \fBFD_ALL_EVENTS\fR  ((1 << FD_MAX_EVENTS) - 1)"
.br
.ti -1c
.RI "#define \fBWSAEVENT\fR  HANDLE"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef struct \fB_WSANETWORKEVENTS\fR  \fBWSANETWORKEVENTS\fR"
.br
.ti -1c
.RI "typedef struct \fB_WSANETWORKEVENTS\fR *  \fBLPWSANETWORKEVENTS\fR"
.br
.in -1c
.SS Functions

.in +1c
.ti -1c
.RI "int \fBWSAEventSelect\fR (SOCKET s, WSAEVENT hEventObject, long lNetworkEvents)"
.br
.ti -1c
.RI "int \fBWSAEnumNetworkEvents\fR (SOCKET s, WSAEVENT hEventObject, \fBLPWSANETWORKEVENTS\fR lpNetworkEvents)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBWFMO_Reactor.h\fR,v 4.57 2001/09/09 13:22:32 bala Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Irfan Pyarali <irfan@cs.wustl.edu> ,  Tim Harrison <harrison@cs.wustl.edu> ,  and Doug Schmidt <schmidt@cs.wustl.edu>
.PP
.SH DEFINE DOCUMENTATION
.PP 
.SS #define FD_ACCEPT_BIT  3
.PP
.SS #define FD_ALL_EVENTS  ((1 << FD_MAX_EVENTS) - 1)
.PP
.SS #define FD_CLOSE_BIT  5
.PP
.SS #define FD_CONNECT_BIT  4
.PP
.SS #define FD_GROUP_QOS  (1 << FD_GROUP_QOS_BIT)
.PP
.SS #define FD_GROUP_QOS_BIT  7
.PP
.SS #define FD_MAX_EVENTS  8
.PP
.SS #define FD_OOB_BIT  2
.PP
.SS #define FD_QOS  (1 << FD_QOS_BIT)
.PP
.SS #define FD_QOS_BIT  6
.PP
.SS #define FD_READ_BIT  0
.PP
.SS #define FD_WRITE_BIT  1
.PP
.SS #define WSAEVENT  HANDLE
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef struct \fB_WSANETWORKEVENTS\fR *  LPWSANETWORKEVENTS
.PP
.SS typedef struct \fB_WSANETWORKEVENTS\fR  WSANETWORKEVENTS
.PP
.SH FUNCTION DOCUMENTATION
.PP 
.SS int WSAEnumNetworkEvents (SOCKET s, WSAEVENT hEventObject, \fBLPWSANETWORKEVENTS\fR lpNetworkEvents)
.PP
.SS int WSAEventSelect (SOCKET s, WSAEVENT hEventObject, long lNetworkEvents)
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.