.TH XtReactor_h 3 "5 Oct 2001" "ACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XtReactor_h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "ace/pre.h"\fR
.br
\fC#include "ace/Select_Reactor.h"\fR
.br
\fC#include "ace/post.h"\fR
.br

.SS Compounds

.in +1c
.ti -1c
.RI "class \fBACE_XtReactor\fR"
.br
.ti -1c
.RI "class \fBACE_XtReactorID\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
\fBXtReactor.h\fR,v 4.27 2001/09/22 15:28:18 schmidt Exp
.PP
\fBAuthor(s): \fR
.in +1c
 Eric C. Newton's <ecn@clark.net> ,  Kirill Rybaltchenko <Kirill.Rybaltchenko@cern.ch> ,  Douglas C. Schmidt <schmidt@cs.wustl.edu>
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for ACE from the source code.