#----------------------------------------------------------------------------
#	Makefile.Today,v 1.1 1998/12/01 00:52:52 kirthika Exp
#
#	Makefile for the Today library in the DLL example
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------
#	Local macros
#----------------------------------------------------------------------------



SHLIB	= libToday.$(SOEXT) 
	 

FILES 	= Today 



LSRC	= $(addsuffix .cpp,$(FILES))

VLDLIBS = $(LDLIBS:%=%$(VAR))


#----------------------------------------------------------------------------
#	Include macros and targets
#----------------------------------------------------------------------------
include		$(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include		$(ACE_ROOT)/include/makeinclude/macros.GNU
include		$(ACE_ROOT)/include/makeinclude/rules.common.GNU
include		$(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include		$(ACE_ROOT)/include/makeinclude/rules.lib.GNU
include		$(ACE_ROOT)/include/makeinclude/rules.bin.GNU
include		$(ACE_ROOT)/include/makeinclude/rules.local.GNU

#----------------------------------------------------------------------------
#	Local targets
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------
#	Dependencies
#----------------------------------------------------------------------------
# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.



