#ifndef _MISC_H
#define _MISC_H

enum ChatterMenuItem {
	CHATTER_MENU_NAME,
	CHATTER_MENU_IGNORED,
	CHATTER_MENU_HIGHLIGHTED,
	CHATTER_MENU_HIGHLIGHT_COLOR,
	CHATTER_MENU_FRIEND_STATUS,
	CHATTER_MENU_COPY=CHATTER_MENU_FRIEND_STATUS+5,
	CHATTER_MENU_REMOVE_ENTRIES,
	CHATTER_MENU_PM,
	CHATTER_MENU_PROPERTIES,
	CHATTER_MENU_URL_BASE
};

enum FriendLevel {	// level of trust of Chatter
	STRANGER=CHATTER_MENU_FRIEND_STATUS+1,
	FRIEND,
	TRUSTED_FRIEND,
	GOD,
	FRIENDLEVEL_END
};

enum AppSignalType {
	APP_LOGIN,
	APP_LOGOUT,
	APP_QUIT,
	APP_LOGIN_FAILED_ROOM_FULL,
	APP_ROOM_ENTERED
};

#endif	// _MISC_H
