LIBRARY X11
VERSION LIBRARY_VERSION
EXPORTS
 _Xdebug_p=_Xdebug CONSTANT
 _XCreateMutex_fn_p=_XCreateMutex_fn CONSTANT
 _XFreeMutex_fn_p=_XFreeMutex_fn CONSTANT
 _XLockMutex_fn_p=_XLockMutex_fn CONSTANT
 _XUnlockMutex_fn_p=_XUnlockMutex_fn CONSTANT
 _Xglobal_lock_p=_Xglobal_lock CONSTANT
 XActivateScreenSaver
 XAddConnectionWatch
 XAddExtension
 XAddHost
 XAddHosts
 XAddPixel
 XAddToExtensionList
 XAddToSaveSet
 XAllPlanes
 XAllocClassHint
 XAllocColor
 XAllocColorCells
 XAllocColorPlanes
 XAllocIconSize
 XAllocNamedColor
 XAllocSizeHints
 XAllocStandardColormap
 XAllocWMHints
 XAllowEvents
 XAutoRepeatOff
 XAutoRepeatOn
 XBaseFontNameListOfFontSet
 XBell
 XBitmapBitOrder
 XBitmapPad
 XBitmapUnit
 XBlackPixel
 XBlackPixelOfScreen
 XCellsOfScreen
 XChangeActivePointerGrab
 XChangeGC
 XChangeKeyboardControl
 XChangeKeyboardMapping
 XChangePointerControl
 XChangeProperty
 XChangeSaveSet
 XChangeWindowAttributes
 XCheckIfEvent
 XCheckMaskEvent
 XCheckTypedEvent
 XCheckTypedWindowEvent
 XCheckWindowEvent
 XCirculateSubwindows
 XCirculateSubwindowsDown
 XCirculateSubwindowsUp
 XClearArea
 XClearWindow
 XClipBox
 XCloseDisplay
 XCloseIM
 XCloseOM
 XConfigureWindow
 XConnectionNumber
 XContextDependentDrawing
 XContextualDrawing
 XConvertCase
 XConvertSelection
 XCopyArea
 XCopyColormapAndFree
 XCopyGC
 XCopyPlane
 XCreateBitmapFromData
 XCreateColormap
 XCreateFontCursor
 XCreateFontSet
 XCreateGC
 XCreateGlyphCursor
 XCreateIC
 XCreateImage
 XCreateOC
 XCreatePixmap
 XCreatePixmapCursor
 XCreatePixmapFromBitmapData
 XCreateRegion
 XCreateSimpleWindow
 XCreateWindow
 XDefaultColormap
 XDefaultColormapOfScreen
 XDefaultDepth
 XDefaultDepthOfScreen
 XDefaultGC
 XDefaultGCOfScreen
 XDefaultRootWindow
 XDefaultScreen
 XDefaultScreenOfDisplay
 XDefaultString
 XDefaultVisual
 XDefaultVisualOfScreen
 XDefineCursor
 XDeleteContext
 XDeleteModifiermapEntry
 XDeleteProperty
 XDestroyIC
 XDestroyImage
 XDestroyOC
 XDestroyRegion
 XDestroySubwindows
 XDestroyWindow
 XDirectionalDependentDrawing
 XDisableAccessControl
 XDisplayCells
 XDisplayHeight
 XDisplayHeightMM
 XDisplayKeycodes
 XDisplayMotionBufferSize
 XDisplayName
 XDisplayOfIM
 XDisplayOfOM
 XDisplayOfScreen
 XDisplayPlanes
 XDisplayString
 XDisplayWidth
 XDisplayWidthMM
 XDoesBackingStore
 XDoesSaveUnders
 XDrawArc
 XDrawArcs
 XDrawImageString
 XDrawImageString16
 XDrawLine
 XDrawLines
 XDrawPoint
 XDrawPoints
 XDrawRectangle
 XDrawRectangles
 XDrawSegments
 XDrawString
 XDrawString16
 XDrawText
 XDrawText16
 XEHeadOfExtensionList
 XESetBeforeFlush
 XESetCloseDisplay
 XESetCopyGC
 XESetCreateFont
 XESetCreateGC
 XESetError
 XESetErrorString
 XESetEventToWire
 XESetFlushGC
 XESetFreeFont
 XESetFreeGC
 XESetPrintErrorValues
 XESetWireToError
 XESetWireToEvent
 XEmptyRegion
 XEnableAccessControl
 XEqualRegion
 XEventMaskOfScreen
 XEventsQueued
 XExtendedMaxRequestSize
 XExtentsOfFontSet
 XFetchBuffer
 XFetchBytes
 XFetchName
 XFillArc
 XFillArcs
 XFillPolygon
 XFillRectangle
 XFillRectangles
 XFilterEvent
 XFindContext
 XFindOnExtensionList
 XFlush
 XFlushGC
 XFontsOfFontSet
 XForceScreenSaver
 XFree
 XFreeColormap
 XFreeColors
 XFreeCursor
 XFreeExtensionList
 XFreeFont
 XFreeFontInfo
 XFreeFontNames
 XFreeFontPath
 XFreeFontSet
 XFreeGC
 XFreeModifiermap
 XFreePixmap
 XFreeStringList
 XGContextFromGC
 XGeometry
 XGetAtomName
 XGetAtomNames
 XGetClassHint
 XGetCommand
 XGetDefault
 XGetErrorDatabaseText
 XGetErrorText
 XGetFontPath
 XGetFontProperty
 XGetGCValues
 XGetGeometry
 XGetICValues
 XGetIMValues
 XGetIconName
 XGetIconSizes
 XGetImage
 XGetInputFocus
 XGetKeyboardControl
 XGetKeyboardMapping
 XGetModifierMapping
 XGetMotionEvents
 XGetNormalHints
 XGetOCValues
 XGetOMValues
 XGetPixel
 XGetPointerControl
 XGetPointerMapping
 XGetRGBColormaps
 XGetScreenSaver
 XGetSelectionOwner
 XGetSizeHints
 XGetStandardColormap
 XGetSubImage
 XGetTextProperty
 XGetTransientForHint
 XGetVisualInfo
 XGetWMClientMachine
 XGetWMColormapWindows
 XGetWMHints
 XGetWMIconName
 XGetWMName
 XGetWMNormalHints
 XGetWMProtocols
 XGetWMSizeHints
 XGetWindowAttributes
 XGetWindowProperty
 XGetZoomHints
 XGrabButton
 XGrabKey
 XGrabKeyboard
 XGrabPointer
 XGrabServer
 XHeightMMOfScreen
 XHeightOfScreen
 XIMOfIC
 XIconifyWindow
 XIfEvent
 XImageByteOrder
 XInitExtension
 XInitImage
 XInitThreads
 XInsertModifiermapEntry
 XInstallColormap
 XInternAtom
 XInternAtoms
 XInternalConnectionNumbers
 XIntersectRegion
 XKeycodeToKeysym
 XKeysymToKeycode
 XKeysymToString
 XKillClient
 XLastKnownRequestProcessed
 XListDepths
 XListExtensions
 XListFonts
 XListFontsWithInfo
 XListHosts
 XListInstalledColormaps
 XListPixmapFormats
 XListProperties
 XLoadFont
 XLoadQueryFont
 XLocaleOfFontSet
 XLocaleOfIM
 XLocaleOfOM
 XLockDisplay
 XLookupColor
 XLookupKeysym
 XLookupString
 XLowerWindow
 XMapRaised
 XMapSubwindows
 XMapWindow
 XMaskEvent
 XMatchVisualInfo
 XMaxCmapsOfScreen
 XMaxRequestSize
 XMinCmapsOfScreen
 XMoveResizeWindow
 XMoveWindow
 XNewModifiermap
 XNextEvent
 XNextRequest
 XNoOp
 XOMOfOC
 XOffsetRegion
 XOpenDisplay
 XOpenIM
 XOpenOM
 XParseColor
 XParseGeometry
 XPeekEvent
 XPeekIfEvent
 XPending
 XPlanesOfScreen
 XPointInRegion
 XPolygonRegion
 XProcessInternalConnection
 XProtocolRevision
 XProtocolVersion
 XPutBackEvent
 XPutImage
 XPutPixel
 XQLength
 XQueryBestCursor
 XQueryBestSize
 XQueryBestStipple
 XQueryBestTile
 XQueryColor
 XQueryColors
 XQueryExtension
 XQueryFont
 XQueryKeymap
 XQueryPointer
 XQueryTextExtents
 XQueryTextExtents16
 XQueryTree
 XRaiseWindow
 XReadBitmapFile
 XReadBitmapFileData
 XRebindKeysym
 XRecolorCursor
 XReconfigureWMWindow
 XRectInRegion
 XRefreshKeyboardMapping
 XRegisterIMInstantiateCallback
 XRemoveConnectionWatch
 XRemoveFromSaveSet
 XRemoveHost
 XRemoveHosts
 XReparentWindow
 XResetScreenSaver
 XResizeWindow
 XResourceManagerString
 XRestackWindows
 XRootWindow
 XRootWindowOfScreen
 XRotateBuffers
 XRotateWindowProperties
 XSaveContext
 XScreenCount
 XScreenNumberOfScreen
 XScreenOfDisplay
 XScreenResourceString
 XSelectInput
 XSendEvent
 XServerVendor
 XSetAccessControl
 XSetAfterFunction
 XSetArcMode
 XSetAuthorization
 XSetBackground
 XSetClassHint
 XSetClipMask
 XSetClipOrigin
 XSetClipRectangles
 XSetCloseDownMode
 XSetCommand
 XSetDashes
 XSetErrorHandler
 XSetFillRule
 XSetFillStyle
 XSetFont
 XSetFontPath
 XSetForeground
 XSetFunction
 XSetGraphicsExposures
 XSetICFocus
 XSetICValues
 XSetIMValues
 XSetIOErrorHandler
 XSetIconName
 XSetIconSizes
 XSetInputFocus
 XSetLineAttributes
 XSetLocaleModifiers
 XSetModifierMapping
 XSetNormalHints
 XSetOCValues
 XSetOMValues
 XSetPlaneMask
 XSetPointerMapping
 XSetRGBColormaps
 XSetRegion
 XSetScreenSaver
 XSetSelectionOwner
 XSetSizeHints
 XSetStandardColormap
 XSetStandardProperties
 XSetState
 XSetStipple
 XSetSubwindowMode
 XSetTSOrigin
 XSetTextProperty
 XSetTile
 XSetTransientForHint
 XSetWMClientMachine
 XSetWMColormapWindows
 XSetWMHints
 XSetWMIconName
 XSetWMName
 XSetWMNormalHints
 XSetWMProperties
 XSetWMProtocols
 XSetWMSizeHints
 XSetWindowBackground
 XSetWindowBackgroundPixmap
 XSetWindowBorder
 XSetWindowBorderPixmap
 XSetWindowBorderWidth
 XSetWindowColormap
 XSetZoomHints
 XShrinkRegion
 XStoreBuffer
 XStoreBytes
 XStoreColor
 XStoreColors
 XStoreName
 XStoreNamedColor
 XStringListToTextProperty
 XStringToKeysym
 XSubImage
 XSubtractRegion
 XSupportsLocale
 XSync
 XSynchronize
 XTextExtents
 XTextExtents16
 XTextPropertyToStringList
 XTextWidth
 XTextWidth16
 XTranslateCoordinates
 XUndefineCursor
 XUngrabButton
 XUngrabKey
 XUngrabKeyboard
 XUngrabPointer
 XUngrabServer
 XUninstallColormap
 XUnionRectWithRegion
 XUnionRegion
 XUnloadFont
 XUnlockDisplay
 XUnmapSubwindows
 XUnmapWindow
 XUnregisterIMInstantiateCallback
 XUnsetICFocus
 XVaCreateNestedList
 XVendorRelease
 XVisualIDFromVisual
 XWMGeometry
 XWarpPointer
 XWhitePixel
 XWhitePixelOfScreen
 XWidthMMOfScreen
 XWidthOfScreen
 XWindowEvent
 XWithdrawWindow
 XWriteBitmapFile
 XXorRegion
 XcmsAddColorSpace
 XcmsAddFunctionSet
 XcmsAllocColor
 XcmsAllocNamedColor
 XcmsCCCOfColormap
 XcmsCIELabClipL
 XcmsCIELabClipLab
 XcmsCIELabClipab
 XcmsCIELabQueryMaxC
 XcmsCIELabQueryMaxL
 XcmsCIELabQueryMaxLC
 XcmsCIELabQueryMinL
 XcmsCIELabToCIEXYZ
 XcmsCIELabWhiteShiftColors
 XcmsCIELuvClipL
 XcmsCIELuvClipLuv
 XcmsCIELuvClipuv
 XcmsCIELuvQueryMaxC
 XcmsCIELuvQueryMaxL
 XcmsCIELuvQueryMaxLC
 XcmsCIELuvQueryMinL
 XcmsCIELuvToCIEuvY
 XcmsCIELuvWhiteShiftColors
 XcmsCIEXYZToCIELab
 XcmsCIEXYZToCIEuvY
 XcmsCIEXYZToCIExyY
 XcmsCIEXYZToRGBi
 XcmsCIEuvYToCIELuv
 XcmsCIEuvYToCIEXYZ
 XcmsCIEuvYToTekHVC
 XcmsCIExyYToCIEXYZ
 XcmsClientWhitePointOfCCC
 XcmsConvertColors
 XcmsCreateCCC
 XcmsDefaultCCC
 XcmsDisplayOfCCC
 XcmsFormatOfPrefix
 XcmsFreeCCC
 XcmsLookupColor
 XcmsPrefixOfFormat
 XcmsQueryBlack
 XcmsQueryBlue
 XcmsQueryColor
 XcmsQueryColors
 XcmsQueryGreen
 XcmsQueryRed
 XcmsQueryWhite
 XcmsRGBToRGBi
 XcmsRGBiToCIEXYZ
 XcmsRGBiToRGB
 XcmsScreenNumberOfCCC
 XcmsScreenWhitePointOfCCC
 XcmsSetCCCOfColormap
 XcmsSetCompressionProc
 XcmsSetWhiteAdjustProc
 XcmsSetWhitePoint
 XcmsStoreColor
 XcmsStoreColors
 XcmsTekHVCClipC
 XcmsTekHVCClipV
 XcmsTekHVCClipVC
 XcmsTekHVCQueryMaxC
 XcmsTekHVCQueryMaxV
 XcmsTekHVCQueryMaxVC
 XcmsTekHVCQueryMaxVSamples
 XcmsTekHVCQueryMinV
 XcmsTekHVCToCIEuvY
 XcmsTekHVCWhiteShiftColors
 XcmsVisualOfCCC
 XmbDrawImageString
 XmbDrawString
 XmbDrawText
 XmbLookupString
 XmbResetIC
 XmbSetWMProperties
 XmbTextEscapement
 XmbTextExtents
 XmbTextListToTextProperty
 XmbTextPerCharExtents
 XmbTextPropertyToTextList
 Xpermalloc
 XrmCombineDatabase
 XrmCombineFileDatabase
 XrmDestroyDatabase
 XrmEnumerateDatabase
 XrmGetDatabase
 XrmGetFileDatabase
 XrmGetResource
 XrmGetStringDatabase
 XrmInitialize
 XrmLocaleOfDatabase
 XrmMergeDatabases
 XrmParseCommand
 XrmPermStringToQuark
 XrmPutFileDatabase
 XrmPutLineResource
 XrmPutResource
 XrmPutStringResource
 XrmQGetResource
 XrmQGetSearchList
 XrmQGetSearchResource
 XrmQPutResource
 XrmQPutStringResource
 XrmQuarkToString
 XrmSetDatabase
 XrmStringToBindingQuarkList
 XrmStringToQuark
 XrmStringToQuarkList
 XrmUniqueQuark
 XwcDrawImageString
 XwcDrawString
 XwcDrawText
 XwcFreeStringList
 XwcLookupString
 XwcResetIC
 XwcTextEscapement
 XwcTextExtents
 XwcTextListToTextProperty
 XwcTextPerCharExtents
 XwcTextPropertyToTextList
 _XAllocID
 _XAllocIDs
 _XAllocScratch
 _XAllocTemp
 _XAsyncErrorHandler
 _XConnectDisplay
 _XDeqAsyncHandler
 _XEatData
 _XError
 _XFlushIt
 _XFlushGCCache
 _XFreeTemp
 _XGetAsyncData
 _XGetAsyncReply
 _XIOError
 _XInitImageFuncPtrs
 _XLockDisplay
 _XRead
 _XReadEvents
 _XReadPad
 _XRegisterFilterByMask
 _XRegisterFilterByType
 _XRegisterInternalConnection
 _XReply
 _XSend
 _XSetLastRequestRead
 _XUnknownNativeEvent
 _XUnregisterFilter
 _XUnregisterInternalConnection
 _XVIDtoVisual
 _Xthread_init
 _Xthread_waiter
 XkbIgnoreExtension
 XkbOpenDisplay
 XkbQueryExtension
 XkbUseExtension
 XkbLibraryVersion
 XkbSetXlibControls
 XkbGetXlibControls
 XkbSetAtomFuncs
 XkbKeycodeToKeysym
 XkbKeysymToModifiers
 XkbLookupKeySym
 XkbLookupKeyBinding
 XkbTranslateKeyCode
 XkbTranslateKeySym
 XkbSetAutoRepeatRate
 XkbGetAutoRepeatRate
 XkbChangeEnabledControls
 XkbDeviceBell
 XkbForceDeviceBell
 XkbDeviceBellEvent
 XkbBell
 XkbForceBell
 XkbBellEvent
 XkbSelectEvents
 XkbSelectEventDetails
 XkbNoteMapChanges
 XkbNoteNameChanges
 XkbGetIndicatorState
 XkbGetIndicatorMap
 XkbSetIndicatorMap
 XkbGetNamedIndicator
 XkbGetNamedDeviceIndicator
 XkbSetNamedIndicator
 XkbSetNamedDeviceIndicator
 XkbLockModifiers
 XkbLatchModifiers
 XkbLockGroup
 XkbLatchGroup
 XkbSetServerInternalMods
 XkbSetIgnoreLockMods
 XkbVirtualModsToReal
 XkbComputeEffectiveMap
 XkbInitCanonicalKeyTypes
 XkbAllocKeyboard
 XkbFreeKeyboard
 XkbAllocClientMap
 XkbAllocServerMap
 XkbFreeClientMap
 XkbFreeServerMap
 XkbAddKeyType
 XkbAllocIndicatorMaps
 XkbFreeIndicatorMaps
 XkbGetMap
 XkbGetUpdatedMap
 XkbGetMapChanges
 XkbRefreshKeyboardMapping
 XkbGetKeyTypes
 XkbGetKeySyms
 XkbGetKeyActions
 XkbGetKeyBehaviors
 XkbGetVirtualMods
 XkbGetKeyExplicitComponents
 XkbGetKeyModifierMap
 XkbAllocControls
 XkbFreeControls
 XkbGetControls
 XkbSetControls
 XkbAllocCompatMap
 XkbFreeCompatMap
 XkbGetCompatMap
 XkbSetCompatMap
 XkbAllocNames
 XkbGetNames
 XkbSetNames
 XkbChangeNames
 XkbFreeNames
 XkbGetState
 XkbSetMap
 XkbChangeMap
 XkbSetDetectableAutoRepeat
 XkbGetDetectableAutoRepeat
 XkbSetAutoResetControls
 XkbGetAutoResetControls
 XkbCopyKeyType
 XkbCopyKeyTypes
 XkbResizeKeyType
 XkbResizeKeySyms
 XkbResizeKeyActions
 XkbChangeTypesOfKey
 XkbListComponents
 XkbFreeComponentList
 XkbGetKeyboard
 XkbGetKeyboardByName
 XkbAddDeviceLedInfo
 XkbResizeDeviceButtonActions
 XkbAllocDeviceInfo
 XkbFreeDeviceInfo
 XkbNoteDeviceChanges
 XkbGetDeviceInfo
 XkbGetDeviceInfoChanges
 XkbGetDeviceButtonActions
 XkbGetDeviceLedInfo
 XkbSetDeviceInfo
 XkbChangeDeviceInfo
 XkbSetDeviceLedInfo
 XkbSetDeviceButtonActions
 XkbToControl
 XkbSetDebuggingFlags
/* $XConsortium: X11-def.cpp /main/14 1996/12/18 16:53:53 lehors $ */
