/**
*Copyright (c) 2000-2001, Jim Crafton
*All rights reserved.
*Redistribution and use in source and binary forms, with or without
*modification, are permitted provided that the following conditions
*are met:
*	Redistributions of source code must retain the above copyright
*	notice, this list of conditions and the following disclaimer.
*
*	Redistributions in binary form must reproduce the above copyright
*	notice, this list of conditions and the following disclaimer in 
*	the documentation and/or other materials provided with the distribution.
*
*THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
*AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS
*OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
*EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
*PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
*PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
*LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
*NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
*SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*NB: This software will not save the world.
*/

/* Generated by Together */
#include "ApplicationKit.h"
#include "CommonDialogPeer.h"


using namespace VCF;


CommonFileDialog::CommonFileDialog()
{
	m_Peer = NULL;
}

CommonFileDialog::~CommonFileDialog()
{

}


void CommonFileDialog::addFilter(const String & description, const String & extension)
{
	m_Peer->addFilter( description, extension );
}

void CommonFileDialog::setDirectory(const String & directory)
{
	m_Peer->setDirectory( directory );
}
        
void CommonFileDialog::setFileName(const String & filename)
{
	m_Peer->setFileName( filename );
}

String CommonFileDialog::getFileName()
{	
	String result;
	return m_Peer->getFileName();
}

String CommonFileDialog::getDirectory()
{
	
	return m_Peer->getDirectory();
}

String CommonFileDialog::getFileExtension()
{
	return m_Peer->getFileExtension();
}

void CommonFileDialog::setAllowsMultiSelect( const bool& allowsMultiSelect )
{
	this->m_Peer->setAllowsMultiSelect( allowsMultiSelect );
}

void CommonFileDialog::setTitle( const String& title )
{
	this->m_Peer->setTitle( title );
}