// -*- C++ -*-
//
// DomainS_T.cpp,v 1.3 2001/05/31 04:50:09 othman Exp

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

#ifndef _TAO_IDL_DOMAINS_T_CPP_
#define _TAO_IDL_DOMAINS_T_CPP_

#include "DomainS_T.h"

#if !defined (__ACE_INLINE__)
#include "DomainS_T.i"
#endif /* !defined INLINE */


#endif /* ifndef */
