//
// Test.idl,v 1.1 2001/04/08 03:58:43 coryan Exp
//

module Test
{
  /// An interface to send oneway messages
  interface Oneway_Receiver
  {
    /// Return a simple string
    oneway void receive_oneway ();
  };
};
