#
# Makefile.bor,v 1.1 2001/03/11 19:35:18 coryan Exp
#

MAKEFILES = Reconnect.bor \
	Shutdown.bor \
	Observer.bor \
	BCast.bor \
	Timeout.bor \
	Wildcard.bor \
	Negation.bor \
	Disconnect.bor \
	MT_Disconnect.bor \
	Atomic_Reconnect.bor \
	Bitmask.bor \
	Complex.bor \
	Gateway.bor \
	Control.bor \
	Random.bor

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
