#
# Makefile.bor,v 1.1 2001/03/11 19:35:18 coryan Exp
#

MAKEFILES = \
	Throughput.bor \
	Connect.bor \
	Inversion.bor \
	Latency.bor \
	Latency_Server.bor

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
