LIBRARY SM
VERSION LIBRARY_VERSION
EXPORTS
 SmFreeProperty
 SmFreeReasons
 SmcClientID
 SmcCloseConnection
 SmcDeleteProperties
 SmcGetIceConnection
 SmcGetProperties
 SmcInteractDone
 SmcInteractRequest
 SmcModifyCallbacks
 SmcOpenConnection
 SmcProtocolRevision
 SmcProtocolVersion
 SmcRelease
 SmcRequestSaveYourself
 SmcRequestSaveYourselfPhase2
 SmcSaveYourselfDone
 SmcSetErrorHandler
 SmcSetProperties
 SmcVendor
 SmsCleanUp
 SmsClientHostName
 SmsClientID
 SmsDie
 SmsGenerateClientID
 SmsGetIceConnection
 SmsInitialize
 SmsInteract
 SmsProtocolRevision
 SmsProtocolVersion
 SmsRegisterClientReply
 SmsReturnProperties
 SmsSaveComplete
 SmsSaveYourself
 SmsSaveYourselfPhase2
 SmsSetErrorHandler
 SmsShutdownCancelled
/* $XConsortium: SM-def.cpp /main/3 1996/05/07 13:15:21 kaleb $ */
