// corbaloc.idl,v 1.2 2000/09/14 23:41:06 doccvs Exp

module corbaloc
{
  
  interface Status
  {
    // = TITLE
    //     A simple interface to check the status of 
    //     connection between the client and the server.
    //
    // = DESCRIPTION
    //     Prints out the status.

    boolean print_status ();
    // Return <true == 0> if the server received the 
    // request from the client.
        
  };
};

