// Foo.idl,v 1.1 1998/09/16 01:01:04 schmidt Exp
//===============================================================================
//
// = FILENAME
//     Foo.idl
//
//==================================================================================

// IDL

interface A
{
  long doit();
};

module Outer
{
  interface B
    {
      long doit();
    };

  module Inner
    {
      interface C
        {
          long doit();
        };
    };
};
