/* -*- C++ -*- */
// UDP.idl
// UDP.idl,v 1.1 2001/04/09 21:39:27 mk1 Exp

interface UDP
{
  // = TITLE
  //    Defines an interface that encapsulates operations that
  //    return the current time of day and shuts down the server.

  oneway void invoke (in string client_name,
                      in UDP udpHandler,
                      in long request_id);
  // Returns the current time of day on another machine.

  oneway void shutdown ();
  // Shutdown the application.
};


