/**
*Copyright (c) 2000-2001, Jim Crafton
*All rights reserved.
*Redistribution and use in source and binary forms, with or without
*modification, are permitted provided that the following conditions
*are met:
*	Redistributions of source code must retain the above copyright
*	notice, this list of conditions and the following disclaimer.
*
*	Redistributions in binary form must reproduce the above copyright
*	notice, this list of conditions and the following disclaimer in 
*	the documentation and/or other materials provided with the distribution.
*
*THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
*AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS
*OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
*EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
*PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
*PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
*LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
*NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
*SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*NB: This software will not save the world.
*/

/* Generated by Together */

#include "ApplicationKit.h"



using namespace VCF;

DropTarget::DropTarget( Control* component )
{
	INIT_EVENT_HANDLER_LIST(DropTargetDraggingOver)
	INIT_EVENT_HANDLER_LIST(DropTargetDropped)
	INIT_EVENT_HANDLER_LIST(DropTargetLeft)
	INIT_EVENT_HANDLER_LIST(DropTargetEntered)

	this->m_dropTargetPeer = UIToolkit::getDefaultUIToolkit()->createDropTargetPeer();
	if ( NULL != m_dropTargetPeer ){
		m_dropTargetPeer->setDropTarget( this );
		m_dropTargetPeer->registerTarget( component );
	}
}


DropTarget::~DropTarget()
{
	if ( NULL != m_dropTargetPeer ){
		delete m_dropTargetPeer;
		m_dropTargetPeer = NULL;
	}
}

void DropTarget::getSupportedActions()
{
	if ( NULL != m_dropTargetPeer ){
		delete m_dropTargetPeer;
	}
	m_dropTargetPeer = NULL;
}

void DropTarget::processEvents( Event* event )
{
	if ( NULL != event ){
		unsigned long eventType = event->getType();
		switch ( eventType ){
			case DROPTARGET_EVENT_ENTERED:{
				fireOnDropTargetEntered( (DragEvent*)event ); 
			}
			break;

			case DROPTARGET_EVENT_DROPPED:{
				fireOnDropTargetDropped( (DropEvent*)event ); 
			}
			break;			
		}
	}
}

DropTargetPeer* DropTarget::getDropTargetPeer()
{
	return this->m_dropTargetPeer;
}