#----------------------------------------------------------------------------
#       Makefile,v 4.6 1999/04/17 13:33:39 levine Exp
#
#       Makefile for the client programs that test the ACE network services
#----------------------------------------------------------------------------

DIRS  = Logger \
        Naming \
        Tokens

#----------------------------------------------------------------------------
#       Include macros and targets
#----------------------------------------------------------------------------

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nolocal.GNU
