#
# Makefile for building the TAO obsvcs tests
# Makefile.bor,v 1.15 2001/09/19 10:12:55 doccvs Exp
#

DIRS = \
        AVStreams \
        Concurrency \
	FaultTolerance \
	Event \
	EC_Throughput \
	EC_Multiple \
	EC_Basic \
	EC_Mcast \
	EC_Custom_Marshal \
	Event_Latency \
        ior_corbaname \
        IOR_MCast \
        LoadBalancing \
	Property \
        Simple_Naming \
        Time \
	Trading

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
