//
// tmplinst.cpp,v 1.1 1998/09/16 00:26:34 schmidt Exp
//

// The contents of this file REALLY should be generated by the IDL
// compiler, but that functionality isn't available yet.

#include "cubitC.h"

ACE_RCSID(IDL_Cubit, tmplinst, "tmplinst.cpp,v 1.1 1998/09/16 00:26:34 schmidt Exp")

#if defined (ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION)
#elif defined (ACE_HAS_TEMPLATE_INSTANTIATION_PRAGMA)
#endif /* ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION */
