// Foo.idl,v 1.2 1999/04/28 06:54:03 irfan Exp
// ================================================================
//
// = FILENAME
//     Foo.idl
//
// ================================================================

// IDL

interface Foo
{
  long doit ();
  // A simple twoway operation, the idea is to verify that the server
  // can be located.

  oneway void simply_doit ();
  // A simple oneway operation, the idea is to measure any differences
  // to the previous one.

  void timed_operation (in unsigned long timeout);
  // A timed operation.

  void shutdown ();
  // Shutdown the server.
};
