/* Generated by Together */

#ifndef BUTTONPEER_H
#define BUTTONPEER_H



namespace VCF{

class Image;

class ButtonPeer : public VCF::ControlPeer {
public:    

    virtual Image* getImage() = 0;

    virtual void setImage( Image* image ) = 0;

    virtual void getState() = 0;

    virtual void setState() = 0;
};

}
#endif //BUTTONPEER_H