/* Generated by Together */


#ifndef COMBOBOXPEER_H
#define COMBOBOXPEER_H



namespace VCF{


class ListItem;

class APPKIT_API ComboBoxPeer : public ControlPeer {
    

public:
    virtual void addItem( ListItem * item ) = 0;
    virtual void insertItem( const unsigned long& index, ListItem * item ) = 0;
};

}
#endif //COMBOBOXPEER_H