/* Generated by Together */


#ifndef FILLSTATE_H
#define FILLSTATE_H



namespace VCF{


enum FillStyle{
	FILL_NONE = 0,		
	FILL_SOLID,
	FILL_DIAGONAL,
	FILL_CROSS,
	FILL_DIAGCROSS,
	FILL_HORZ,
	FILL_VERT
};
class GRAPHICSKIT_API FillState : public Object {

public:

	FillState(){
		m_style = FILL_SOLID;
	};
	virtual ~FillState(){};

    Color m_Color;
    FillStyle m_style;
};

};

#endif //FILLSTATE_H