/* Generated by Together */


#ifndef FONTSTATE_H
#define FONTSTATE_H


namespace VCF{

class GRAPHICSKIT_API FontState : public Object {

public:
   FontState();
   virtual ~FontState();

   void init();

   virtual String toString();

   Color m_color;
   bool m_bold;
   bool m_underlined;
   bool m_strikeOut;
   bool m_italicized;
   double m_height;
   /**
   *range of 0.0..360.0
   */
   double m_angle;
   String m_name;
};

};
#endif //FONTSTATE_H_H