/* Generated by Together */

#ifndef WINDOWPEER_H
#define WINDOWPEER_H



namespace VCF{

/** @interface */

class APPKIT_API WindowPeer : public VCF::ControlPeer {
public:
	virtual ~WindowPeer(){};

	virtual Rect* getClientBounds() = 0;

	virtual void  setClientBounds( Rect* bounds ) = 0;

	virtual void close() = 0;

	virtual void setFrameStyle( const FrameStyleType& frameStyle ) = 0;

	virtual void setFrameTopmost( const bool& isTopmost ) = 0;
};

};
#endif //WINDOWPEER_H