/* Generated by Together */

#ifndef CLASSFACTORY_H
#define CLASSFACTORY_H
#include "COMObject.h"

namespace VCFCOM{
/**
 * Base implementation of IClassFactory and IClassFactory2 
 */
class ClassFactory : public VCFCOM::COMObject {
};

}
#endif //CLASSFACTORY_H