/* Generated by Together */

#ifndef CONNECTIONPOINTCONTAINER_H
#define CONNECTIONPOINTCONTAINER_H
#include "COMObject.h"
namespace VCFCOM{
/**
 * Base implementation of IConnectionPointContainer 
 */
class ConnectionPointContainer : public COMObject {
};

}
#endif //CONNECTIONPOINTCONTAINER_H