/* Generated by Together */

#ifndef CONNECTIONPOINT_H
#define CONNECTIONPOINT_H
#include "COMObject.h"
namespace VCFCOM{
class ConnectionPoint : public COMObject {
};

}
#endif //CONNECTIONPOINT_H