/* Generated by Together */

#ifndef DISPATCHOBJECT_H
#define DISPATCHOBJECT_H
#include "COMObject.h"
namespace VCFCOM{
/**
 * base implementation of IDispatch 
 */
class DispatchObject : public COMObject {
};

}
#endif //DISPATCHOBJECT_H