/* Generated by Together */

#ifndef VIEWABLEOBJECT_H
#define VIEWABLEOBJECT_H
#include "COMObject.h"

namespace VCFCOM{
/**
 * base implemementation of IViewObject and IViewObject2 
 */
class ViewableObject : public VCFCOM::COMObject {
};

}
#endif //VIEWABLEOBJECT_H