#----------------------------------------------------------------------------
#       Makefile.vac,v 4.2 2001/05/18 18:41:58 shuston Exp
#
#       Makefile for building libACE using Visual Age C++ Incremental compiler
#----------------------------------------------------------------------------

all:
	vacbld_r ace.icc -sev=w

realclean:
	vacbld_r ace.icc -clean
