//
// Test.idl,v 1.1 2001/03/31 03:58:21 coryan Exp
//

module Test
{
  /// A very simple interface
  interface Sleep_Service
  {
    /// Sleep for @c microseconds
    void go_to_sleep (in unsigned long microseconds);

    /// A method to shutdown the ORB
    /**
     * This method is used to simplify the test shutdown process
     */
    oneway void shutdown ();
  };
};
