//
// test.idl,v 1.1 2000/01/07 04:44:07 irfan Exp
//

interface test
{
  typedef sequence<octet> data;
  oneway void method (in unsigned long request_number,
                      in data d,
                      in unsigned long work);

  oneway void shutdown ();
};
