# $XFree86: xc/programs/Xserver/hw/xfree86/vga256/drivers/mga/util/Makefile,v 1.1.2.1 1997/05/09 09:09:14 hohndel Exp $



all:	stormdwg

stormdwg:	stormdwg.c
	cc -o stormdwg stormdwg.c

clean:
	rm -f *.o stormdwg

