// MCast.idl,v 1.1 2001/09/05 22:07:49 doccvs Exp

module MCast
{
  
  interface Server
  {
    // = TITLE
    //
    // = DESCRIPTION
    //     Prints out the status.

    boolean connect_server ();
    // Return <true> if the server received the 
    // request from the client.
    
  };

};
