#----------------------------------------------------------------------------
#
#       Makefile,v 1.5 1998/08/01 00:31:31 gonzo Exp
#
#	@(#)Makefile	1.1	10/18/96
#
#	Makefile for the ACE+SNMP examples directory
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------
#	Local macros
#----------------------------------------------------------------------------

DIRS  =	get \
	next \
	set \
	trap \
	walk 

#----------------------------------------------------------------------------
#	macros and targets
#----------------------------------------------------------------------------

include	$(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include	$(ACE_ROOT)/include/makeinclude/macros.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.common.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.nested.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.nolocal.GNU
