//
// tmplinst.cpp,v 1.3 1998/08/03 18:59:22 gonzo Exp
//

// The contents of this file REALLY should be generated by the IDL
// compiler, but that functionality isn't available yet.

#include "orbsvcs/orbsvcs/CosConcurrencyControlC.h"

ACE_RCSID(Concurrency, tmplinst, "tmplinst.cpp,v 1.3 1998/08/03 18:59:22 gonzo Exp")

#if defined (ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION)
#elif defined (ACE_HAS_TEMPLATE_INSTANTIATION_PRAGMA)
#endif /* ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION */
