/**
*Copyright (c) 2000-2001, Jim Crafton
*All rights reserved.
*Redistribution and use in source and binary forms, with or without
*modification, are permitted provided that the following conditions
*are met:
*	Redistributions of source code must retain the above copyright
*	notice, this list of conditions and the following disclaimer.
*
*	Redistributions in binary form must reproduce the above copyright
*	notice, this list of conditions and the following disclaimer in 
*	the documentation and/or other materials provided with the distribution.
*
*THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
*AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS
*OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
*EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
*PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
*PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
*LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
*NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
*SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*NB: This software will not save the world.
*/




#ifndef COMPONENTEVENT_H
#define COMPONENTEVENT_H


namespace VCF{


#define COMPONENT_EVENT_CREATED				CUSTOM_EVENT_TYPES + 403
#define COMPONENT_EVENT_DELETED				CUSTOM_EVENT_TYPES + 404

/**
*ComponentEvent are events generated by changes made to the component.
*Currently there are 2 types, one for the component being created, and
*one for component deletion.
*
*@version 1.0
*@author Jim Crafton
*/
class APPKIT_API ComponentEvent : public Event {
public:
	ComponentEvent( Object * source):
		Event( source ){
	};

	ComponentEvent( Object* source, const unsigned long& eventType ):
		Event( source, eventType ){
	};

	virtual ~ComponentEvent(){};

};

};
#endif //COMPONENTEVENT_H