#
# Makefile.bor,v 1.1 2001/05/26 02:09:24 doccvs Exp
#

MAKEFILES = \
	TradingLib.bor \
	colocated_test.bor \
	export_test.bor \
	import_test.bor

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
