#----------------------------------------------------------------------------
#       Makefile,v 4.11 2001/08/17 17:23:14 bala Exp
#
#	Makefile for the apps directory
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------
#	Local macros
#----------------------------------------------------------------------------

INFO  = README

DIRS  = Gateway \
        gperf \
	drwho

# The following directories aren't compiled by default since haven't
# finished integrating it into ACE...
#
# Orbix-Examples

#----------------------------------------------------------------------------
#	Include macros and targets
#----------------------------------------------------------------------------

include	$(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include	$(ACE_ROOT)/include/makeinclude/macros.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.common.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.nested.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.nolocal.GNU

