/**
*Copyright (c) 2000-2001, Jim Crafton
*All rights reserved.
*Redistribution and use in source and binary forms, with or without
*modification, are permitted provided that the following conditions
*are met:
*	Redistributions of source code must retain the above copyright
*	notice, this list of conditions and the following disclaimer.
*
*	Redistributions in binary form must reproduce the above copyright
*	notice, this list of conditions and the following disclaimer in 
*	the documentation and/or other materials provided with the distribution.
*
*THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
*AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS
*OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
*EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
*PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
*PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
*LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
*NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
*SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*NB: This software will not save the world.
*/

/* Generated by Together */

#ifndef DEFAULTTREEITEM_H
#define DEFAULTTREEITEM_H



namespace VCF
{



#define DEFAULTTREEITEM_CLASSID		"3126B224-2819-11d4-B53A-00C04F0196DA"

class APPKIT_API DefaultTreeItem : public TreeItem {
public:

	BEGIN_CLASSINFO(DefaultTreeItem, "VCF::DefaultTreeItem", "VCF::TreeItem", DEFAULTTREEITEM_CLASSID)	
	END_CLASSINFO(DefaultTreeItem)	
	
	DefaultTreeItem( const String& caption="", Control* owningControl=NULL, TreeModel* model=NULL );

	virtual ~DefaultTreeItem();

	EVENT_HANDLER_LIST(ItemPaint);
	EVENT_HANDLER_LIST(ItemChanged);
	EVENT_HANDLER_LIST(ItemSelected);
	EVENT_HANDLER_LIST(ItemAdded);
	EVENT_HANDLER_LIST(ItemDeleted);

	virtual void addItemPaintHandler( EventHandler* handler ){
		ADD_EVENT_IMPL(ItemPaint) 
	}

	virtual void addItemChangedHandler( EventHandler* handler ){
		ADD_EVENT_IMPL(ItemChanged) 
	}

	virtual void addItemSelectedHandler( EventHandler* handler ){
		ADD_EVENT_IMPL(ItemSelected) 
	}

	virtual void addItemAddedHandler( EventHandler* handler ){
		ADD_EVENT_IMPL(ItemAdded) 
	}

	virtual void addItemDeletedHandler( EventHandler* handler ){
		ADD_EVENT_IMPL(ItemDeleted) 
	}
    
	virtual void removeItemPaintHandler( EventHandler* handler ){
		REMOVE_EVENT_IMPL(ItemPaint) 
	}

	virtual void removeItemChangedHandler( EventHandler* handler ){
		REMOVE_EVENT_IMPL(ItemChanged) 
	}

	virtual void removeItemSelectedHandler( EventHandler* handler ){
		REMOVE_EVENT_IMPL(ItemSelected) 
	}

	virtual void removeItemAddedHandler( EventHandler* handler ){
		REMOVE_EVENT_IMPL(ItemAdded) 
	}

	virtual void removeItemDeletedHandler( EventHandler* handler ){
		REMOVE_EVENT_IMPL(ItemDeleted) 
	}

	FIRE_EVENT(ItemPaint,ItemEvent)
	FIRE_EVENT(ItemChanged,ItemEvent)
	FIRE_EVENT(ItemSelected,ItemEvent)
	FIRE_EVENT(ItemAdded,ItemEvent)
	FIRE_EVENT(ItemDeleted,ItemEvent)

	virtual bool containsPoint( Point * pt );

	virtual Image* getImage();

    virtual unsigned long getIndex();

    virtual void* getData();

	virtual void setData( void* data );	

    virtual Color* getTextColor();

    virtual void setTextColor(Color* color);

    virtual void setTextBold(const bool& bold);

    virtual bool getTextBold();

    virtual bool isLeaf();

	virtual bool isRoot();

    virtual TreeItem* getParent();

	virtual void setParent( TreeItem* parent );

    virtual TreeItem* getNextChildNodeItem();

    virtual TreeItem* getPrevChildNodeItem();

    virtual String getCaption();

	virtual void setCaption( const String& caption );

	virtual Enumerator<TreeItem*>* getChildren();

	void init();

	virtual void addChild( TreeItem* child );

	virtual void insertChild( const unsigned long& index, TreeItem* child );
	
	virtual void deleteChild( TreeItem* child );

	virtual void deleteChild( const unsigned long& index );

	virtual void clearChildren();

	virtual Model* getModel();

	virtual void setModel( Model* model );

	virtual void setIndex( const unsigned long& index );

	virtual void paint( GraphicsContext* context, Rect* paintRect );
	
	virtual bool isSelected();

	virtual void setSelected( const bool& selected );

	virtual bool isExpanded() {
		return m_isExpanded;
	}

	virtual void expand( const bool& isExpanded );

	virtual ulong32 getLevel();

	virtual Rect* getBounds() {
		return &m_bounds;
	}

	virtual Control* getControl() {
		return m_owningControl;
	}

	virtual ulong32 getImageIndex() {
		return m_imageIndex;
	}

	virtual void setImageIndex( const ulong32& imageIndex );

	virtual void setControl( Control* control );

	virtual ulong32 getSelectedImageIndex() {
		return m_selectedImageIndex;
	}

	virtual void setSelectedImageIndex( const ulong32& selectedImageIndex );

	virtual ulong32 getExpandedImageIndex() {
		return m_expandedImageIndex;
	}

	virtual void setExpandedImageIndex( const ulong32& expandedImageIndex );

	virtual bool canPaint() {
		return true;	
	}
private:    
    bool m_textBold;
    Color m_TextColor;
	String m_caption;
	TreeItem* m_parent;
	Image* m_image;
	void* m_userData;
	TreeModel* m_treeModel;
	unsigned long m_index;
	EnumeratorContainer<std::vector<TreeItem*>,TreeItem*> m_enumContainer; 
	std::vector<TreeItem*> m_childNodeItems;
	bool m_selected;
	bool m_isExpanded;
	Rect m_bounds;
	Control* m_owningControl;
	ulong32 m_imageIndex;
	ulong32 m_selectedImageIndex;
	ulong32 m_expandedImageIndex;
};

};

#endif //DEFAULTTREEITEM_H